.azure-pipelines/scripts/models/collect_log_model.py
Signed-off-by: Sun, Xuehao <xuehao.sun@intel.com>
Remove redundant print information on benchmark
=> Azure-Pipeline: Remove redundant print information

docs/adaptor.md
Improved document for adaptor.py
No API changed
=> Improved document for adaptor.py

neural_compressor/experimental/common/torch_utils.py, neural_compressor/experimental/component.py, neural_compressor/experimental/data/__init__.py, neural_compressor/experimental/data/datasets/bert_dataset.py, neural_compressor/experimental/data/datasets/coco_dataset.py, neural_compressor/experimental/data/datasets/dataset.py, neural_compressor/experimental/data/filters/__init__.py, neural_compressor/experimental/data/filters/coco_filter.py, neural_compressor/experimental/data/filters/filter.py
Improved docstring for API helper:
No API changed 
Change files:
neural_compressor/experimental/common/torch_utils.py
neural_compressor/experimental/component.py
neural_compressor/experimental/data/__init__.py
neural_compressor/experimental/data/datasets/bert_dataset.py
neural_compressor/experimental/data/datasets/coco_dataset.py
neural_compressor/experimental/data/datasets/dataset.py
neural_compressor/experimental/data/filters/__init__.py
neural_compressor/experimental/data/filters/coco_filter.py
neural_compressor/experimental/data/filters/filter.py
=> Update docstrings for some experimental files

README.md
documentation
fix invalid link in readme
No
=> Fix invalid link in README

.azure-pipelines/scripts/ut/compare_coverage.sh, .azure-pipelines/scripts/ut/env_setup.sh
UT
Workaround for dataset download issue
=> fix cifar-10 download random issue

.github/workflows/publish.yml, sphinx-requirements.txt
bug fix 
fix build error
build succeed
action status
no
=> fix build error

neural_compressor/experimental/data/datasets/__init__.py
no API changed or not
improve docstring for dataset/__init__.py
=> add docstring for dataset __init__

.azure-pipelines/scripts/codeScan/pyspelling/lpot_dict.txt, docs/framework_yaml.md, docs/pythonic_style.md, docs/user_yaml.md
Signed-off-by: Gao, Qun <qun.gao@intel.com>
Documentation
Add user_yaml.md, framework_yaml.md, and pythonic_style.md
No risk
No need. 
No dependency.
=> add three doc: framework_yaml.md, user_yaml.md, and pythonic_style.md

neural_compressor/experimental/model_conversion.py
This commit fixes pydocstyle errors in `model_conversion.py`
=> fix pydocstyle

neural_compressor/experimental/distillation.py
=> Fixed docstring issue

neural_compressor/adaptor/tf_utils/graph_rewriter/generic/pre_optimize.py, neural_compressor/model/onnx_model.py
bug fix
JIRA ticket: ILITV-2445
"SpaceToBatchND" + "Conv2D" or "DepthwiseConv2dNative" + "BatchToSpaceND" can be fused to improve the performance of the related model .
No.
=> Enable dilated contraction fusion for ITEX

.azure-pipelines/scripts/ut/env_setup.sh, neural_compressor/adaptor/tensorflow.yaml, neural_compressor/adaptor/tf_utils/quantize_graph/qdq/fuse_qdq_bn.py, neural_compressor/adaptor/tf_utils/quantize_graph/quantize_graph_bn.py, test/tfnewapi/test_tensorflow_graph_qdq_bn_fusion.py
Signed-off-by: Li, Chenda <chenda.li@intel.com>
Feature
API not changed 
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2436
_QuantizedFusedBatchNorm+LeakyRelu can be fused
Pre-CI Test
=> Enable QDQ-adapted _QuantizedFusedBatchNorm+LeakyRelu fusion

neural_compressor/adaptor/pytorch.py
Signed-off-by: Wang, Chang1 <chang1.wang@intel.com>
=> fix ipex quantization

.azure-pipelines/scripts/models/generate_report.sh, .azure-pipelines/template/model-template.yml
Signed-off-by: Sun, Xuehao <xuehao.sun@intel.com>
Set the status to "Failed" when performance gap in the Model-Test
use `condition: succeededOrFailed()` replace `continueOnError: true`
status will be "Failed", not "Warning"
=> Fix Model-Test pipeline status

neural_compressor/adaptor/tensorflow.py, neural_compressor/adaptor/tensorflow.yaml, neural_compressor/adaptor/tf_utils/graph_converter.py, neural_compressor/adaptor/tf_utils/graph_rewriter/bf16/bf16_convert.py
Signed-off-by: Li, Chenda <chenda.li@intel.com>
Feature
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2446
_MklFusedBatchMatMulV2 can be converted to BF16
Pre-CI Test
=> Enable _MklFusedBatchMatMulV2 BF16 conversion

docs/source/pruning.md, docs/source/validated_model_list.md, examples/pytorch/nlp/huggingface_models/text-classification/pruning/pytorch_pruner/eager/README.md, examples/pytorch/nlp/huggingface_models/text-classification/pruning/pytorch_pruner/eager/bert_mini_mrpc_1xchannel.yaml, examples/pytorch/nlp/huggingface_models/text-classification/pruning/pytorch_pruner/eager/bert_mini_sst2_1xchannel.yaml
Documentation & examples
Corrected pruning.md links, updated per channel examples.
=> Pruning doc refinements

examples/pytorch/image_recognition/CNN-2/distillation/eager/README.md, examples/pytorch/image_recognition/CNN-2/distillation/eager/main.py, examples/pytorch/image_recognition/CNN-2/distillation/eager/requirements.txt
Added distributed training support for distillation of MobileNetV2.
JIRA ticket: [Support multiple node examples with INC](https://jira.devtools.intel.com/browse/ILITV-2307)
introduced accelerate
=> Added distributed training support for distillation of CNN-2.

neural_compressor/adaptor/tf_utils/graph_rewriter/generic/pre_optimize.py
bug fix
JIRA ticket: ILITV-2461
The NTM-One-Shot tuning issue can be fixed.
No.
=> Fix NTM-One-Shot failed with KeyError

neural_coder/__main__.py
fix a bug in launcher (enable multi-item input) and reorganize format
fix a bug in launcher (enable multi-item input) and reorganize format
no risk
locally
no
=> Neural Coder launcher debug

neural_coder/coders/autoinc/eval_func.py, neural_coder/interface.py
bug fix
Some debug for HuggingFace run_qa support
No
Locally
No
=> Neural Coder debug for HuggingFace run_qa.py

.azure-pipelines/model-test.yml, .azure-pipelines/scripts/models/collect_log_all.py, .azure-pipelines/scripts/models/collect_log_model.py, .azure-pipelines/scripts/models/generate_report.sh
Signed-off-by: Sun, Xuehao <xuehao.sun@intel.com>
modify azure Model-Test pipeline failure condition
modify html report link
when perf_gap > 5% and ratio > 5% will cause failure
html report: click `Tuning Strategy` `Tuning Time` `Tuning Count`, INT8 and FP32 `top1` will download the tuning-info.log
Model-Test Pipeline succeed
=> modify Model-Test pipeline

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/util.py, neural_compressor/config.py, neural_compressor/experimental/__init__.py, neural_compressor/experimental/export/__init__.py, neural_compressor/experimental/export/torch2onnx.py, neural_compressor/experimental/export/utils.py, neural_compressor/model/torch_model.py, test/export/test_torch2onnx.py
New Export with API 2.0. We remove calibration data loader from export API.
=> New Export with API 2.0

neural_compressor/adaptor/tensorflow.yaml, neural_compressor/adaptor/tf_utils/quantize_graph/qdq/fuse_qdq_matmul.py
feature
JIRA ticket: [ILITV-2489](https://jira.devtools.intel.com/browse/ILITV-2489)
'Square', 'Sum', 'SparseSegmentSqrtN' can be converted to BF16.
No.
=> Support 'Square', 'Sum', 'SparseSegmentSqrtN' BF16

neural_coder/backends/nano_bf16.yaml, neural_coder/backends/nano_bf16_channels_last.yaml, neural_coder/backends/nano_bf16_ipex.yaml, neural_coder/backends/nano_bf16_ipex_channels_last.yaml, neural_coder/backends/nano_fp32_channels_last.yaml, neural_coder/backends/nano_fp32_ipex.yaml, neural_coder/backends/nano_fp32_ipex_channels_last.yaml, neural_coder/backends/nano_gpu_to_cpu.yaml, neural_coder/backends/nano_int8.yaml, neural_coder/backends/nano_jit_bf16.yaml, neural_coder/backends/nano_jit_bf16_channels_last.yaml, neural_coder/backends/nano_jit_bf16_ipex.yaml, neural_coder/backends/nano_jit_bf16_ipex_channels_last.yaml, neural_coder/backends/nano_jit_fp32.yaml, neural_coder/backends/nano_jit_fp32_channels_last.yaml, neural_coder/backends/nano_jit_fp32_ipex.yaml, neural_coder/backends/nano_jit_fp32_ipex_channels_last.yaml, neural_coder/backends/nano_onnxruntime_fp32.yaml, neural_coder/backends/nano_onnxruntime_int8_qlinear.yaml, neural_coder/backends/nano_openvino_fp32.yaml, neural_coder/backends/nano_openvino_int8.yaml
features
not change
Enable BigDL nano API
Tested locally
=> Enable BigDL Nano API in Neural Coder

neural_coder/docs/release_notes/v0.4.md
=> fix some typos in rls note readme

neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
bug fix
JIRA ticket: ILITV-2496
5 ITEX OOB models benchmark issue can be fixed.
Pre-CI and OOB extension test.
No.
=> Fix ITEX OOB model benchmark issue

docs/source/validated_model_list.md
Documentation change.
Updated multi-nodes distillation results of MobileNetV2-0.35 and CNN-2 examples.
JIRA ticket: [Support multiple node examples with INC](https://jira.devtools.intel.com/browse/ILITV-2307)
=> Updated multi-nodes distillation results of MobileNetV2-0.35 and CNN-2 examples

test/itex/test_tensorflow_itex_basic.py
bug fix
JIRA ticket: ILITV-2480
ITEX benchmark UT check will not has issue when unexcepted log file exist.
UT test.
No.
=> Enhance ITEX benchmark UT check

examples/.config/model_params_onnxrt_win.json, neural_compressor/experimental/benchmark.py
bug fix
JIRA ticket: [ILITV-2479](https://jira.devtools.intel.com/browse/ILITV-2479)
CI pass
Trigger Windows CI
None
=> Fix Windows multi-instance bug

test/strategy/test_sigopt.py
Signed-off-by: yiliu30 <yi4.liu@intel.com>
- Bug fix
Fixed the UTs of sigopt strategy for the new API
None
Pre-CI
None
=> Fixed the UTs of sigopt strategy for the new API

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
bug fix 
add Startup to dict
Spellcheck Scan
Spellcheck Scan
No
=> update spell check dict

neural_compressor/config.py, neural_compressor/experimental/benchmark.py, neural_compressor/experimental/component.py, neural_compressor/training.py
bug fix
No API changed
fixed calibration sampling size setting error
set calibration sampling size successfully
Local tested
=> Fixed calibration sampling size error and IPEX examples error

neural_compressor/adaptor/tensorflow.py, test/quantization/test_tensorflow_qat.py
Signed-off-by: zehao-intel <zehao.huang@intel.com>
API changed or not: No
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2515
the expected behavior that triggered by this PR :Fix UT
how to reproduce the test (including hardware information):UT, preci
any library dependency introduced or removed; No
=> Fix QAT UT issues

docs/source/_static/custom.css, docs/source/_templates/layout.html
Add version in IO system
Add version
Add version 
click IO
no
=> Add version in IO system

docs/source/validated_model_list.md
documentation 
update partial NVidia A100 CUDA EP ONNX QDQ accuracy data with per-channel
=> update partial NVidia A100 CUDA EP ONNX QDQ accuracy data

examples/tensorflow/style_transfer/arbitrary_style_transfer/quantization/ptq/style_tune.py
Signed-off-by: Gao, Qun <qun.gao@intel.com>
- bug fix DATASETS => Datasets
- NO API changes
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2530
- No risks associated. 
- Run the main.py
- No dependency changes.
=> Modify DATASETS => Datasets to match  NEW API naming

docs/source/validated_model_list.md
documentation 
update partial NVidia A100 CUDA EP ONNX QDQ accuracy data
=> update partial A100 CUDA accuracy data

neural_compressor/adaptor/ox_utils/util.py
Signed-off-by: yuwenzho <yuwen.zhou@intel.com>
bug fix
Defect/regression:
TypeError: type numpy.ndarray doesn't define _round_ method
Profile: 
Report: https://inteltf-jenk.sh.intel.com/view/lpot-release/job/intel-lpot-validation-top-release-v2.0/3/artifact/report.html
commit id: ae3cf5638ca96052032f11dca2120dce5c8d0316
log:
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-release-v2.0/3/artifact/linux/onnxrt/mobilenetv2-12/onnxrt-mobilenetv2-12-linux-clx8280-tune.log
Framework: onnx
Framework version: 1.13.1
JIRA ticket: [ILITV-2528](https://jira.devtools.intel.com/browse/ILITV-2528)
extension test: mobilenetv2-12
NO
=> Fix onnxrt numpy round bug

.azure-pipelines/scripts/models/env_setup.sh, .azure-pipelines/scripts/ut/env_setup.sh, examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/utils_qa.py, examples/onnxrt/object_detection/onnx_model_zoo/DUC/quantization/ptq/main.py, examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq/main.py, examples/pytorch/nlp/huggingface_models/common/examples/question-answering/utils_qa.py, examples/pytorch/nlp/huggingface_models/question-answering/distillation/eager/utils_qa.py, examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/utils_qa.py, examples/pytorch/nlp/huggingface_models/question-answering/pruning/pattern_lock/eager/utils_qa.py, examples/pytorch/nlp/huggingface_models/question-answering/pruning/pytorch_pruner/eager/utils_qa.py, examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/utils_qa.py, examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/utils_qa.py, examples/pytorch/nlp/huggingface_models/text-classification/pruning/magnitude/eager/callback/trainingmonitor.py, examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/maskrcnn_benchmark/modeling/rpn/anchor_generator.py, examples/tensorflow/object_detection/yolo_v3/quantization/ptq/utils.py, neural_compressor/data/datasets/dummy_dataset_v2.py, neural_compressor/experimental/data/datasets/dummy_dataset_v2.py, neural_compressor/experimental/metric/coco_tools.py, neural_compressor/metric/coco_tools.py, neural_compressor/strategy/bayesian.py, test/adaptor/tensorflow_adaptor/test_tensorflow_graph_matmul_fusion.py, test/adaptor/tensorflow_adaptor/test_tensorflow_grappler_pass.py, test/tfnewapi/test_tensorflow_fuse_reshape_transpose.py, test/tfnewapi/test_tensorflow_graph_qdq_matmul_fusion.py
bug fix
Some numpy dtype are deprecated, need to update. 
> https://pypi.org/project/numpy/1.24.0/ 
> https://dev.azure.com/lpot-inc/neural-compressor/_build/results?buildId=6500&view=logs&j=aff40fc6-1d0e-52aa-b4b9-bb1d69413565&t=703464d3-22ee-50e8-40c6-50824d22184f 
> "module 'numpy' has no attribute 'float'" 
CI pass
CI test
No
=> update numpy dtype

neural_compressor/adaptor/torch_utils/util.py
fix mse_v2 bug on PT1.13
[ILITV-2545](https://jira.devtools.intel.com/browse/ILITV-2545)
UT pass.
=> fix mse_v2 bug on PT1.13

docs/source/distillation.md, docs/source/distillation_quantization.md, docs/source/orchestration.md
Signed-off-by: Xinyu Ye <xinyu.ye@intel.com>
Fixed broken links in documentation.
API not changed.
=> Fixed broken links.

neural_compressor/experimental/model_conversion.py, test/model/test_model_conversion.py, test/quantization/test_tensorflow_qat.py
Signed-off-by: Huang, Zehao <zehao.huang@intel.com>
API changed or not: No
JIRA ticket: 2513, 2552
the expected behavior that triggered by this PR : fix ut
=> Fix TF QAT Related UT Issues

neural_compressor/pruner/criteria.py, neural_compressor/pruner/pruners.py
Signed-off-by: YIYANGCAI <yiyang.cai@intel.com>
Bug fix
=> Refine pruning API reaction when obtain wrong pruner type.

.azure-pipelines/code-scan.yml, .azure-pipelines/scripts/codeScan/pydocstyle/pydocstyle.sh, .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
validation 
support multiple path pydocstyle scan
CI test
No
=> support multiple path pydocstyle scan

docs/source/_static/custom.css
modify footer style in IO
modify footer style in IO
click link 
display normal
no
=> modify footer style in IO

examples/tensorflow/object_detection/yolo_v3/quantization/ptq/infer_detections.py
bug fix
JIRA ticket: [ILITV-2535](https://jira.devtools.intel.com/browse/ILITV-2535)
this example succeeds to pass tests
CI
None
=> fix yolo_v3 registry bug

examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/README.md, examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/requirements.txt, examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue.py
bug fix
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2543)
model pytorch version >=1.12.0+cpu
no
no
=> readme and requirement fix

.azure-pipelines/code-scan.yml, .azure-pipelines/model-test.yml, .azure-pipelines/scripts/models/collect_log_model.py, .azure-pipelines/scripts/models/run_benchmark_common.sh, .azure-pipelines/template/model-template.yml
validation 
Update model test CI status. When model test failed with perf gap, do not upload artifacts, so pipeline will works with 'Rerun failed jobs'
CI performs as expect.
CI
No
=> Enhance model test CI status

docs/source/FX.md
Enhance document  
No API changed
Enhance the document of FX.md
=> Improve FX.md

docs/source/NAS.md
Signed-off-by: Xinyu Ye <xinyu.ye@intel.com>
Documentation
=> refined NAS document.

docs/source/tensorboard.md
Signed-off-by: Gao, Qun <qun.gao@intel.com>
- Docs refinement. 
- No API changes.
- Refine tensorboard.md file to meet new doc requirement. 
- No risk expected. 
- No test required. 
- No dependency changes.
=> reformat tensorboard.md to meet new doc requirement

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
Change GPT-J example configure setting  
No API changed
Change GPT-J example configure setting  
example run successfully 
Local test
=> Change the GPT-J example configure setting

docs/source/distributed.md
docs refine
- distributed.md
1. Title: Capitalize the first letter & Modify title name
2. Add content list
3. Fix the relative path link of files
=> distributed.md doc refine

examples/tensorflow/object_detection/yolo_v3/quantization/ptq/infer_detections.py, neural_compressor/experimental/data/transforms/transform.py
bug fix
JIRA ticket: [ILITV-2535](https://jira.devtools.intel.com/browse/ILITV-2535)
This PR is just to revert the incorrect old commit. Please see https://github.com/intel/neural-compressor/pull/361 to see the proposed solution, where we adapt new api functionalities to old api examples.
Rebuild https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-release-v2.0/99/
None
=> Fix yolo registry postprocess bug

neural_coder/backends/pytorch_inc_dynamic_quant.yaml, neural_coder/backends/pytorch_inc_dynamic_quant_fp8.yaml, neural_coder/backends/pytorch_inc_static_quant_fx_fp8.yaml, neural_coder/coders/autoinc/autoinc_harness.py, neural_coder/interface.py, neural_coder/utils/handle_user_input.py
Neural Coder bug fix
Neural Coder bug fix
Neural Coder bug fix
Locally
No
=> Neural Coder bug fix

README.md
modify CONTRIBUTING.md link 
modify CONTRIBUTING.md link 
link work
click link
no
=> modify CONTRIBUTING.md link in README.md

examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/export.py, examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/main.py, examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/qa_dynamic.yaml, examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/requirements.txt, examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/trainer_qa.py, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq/export.py, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq/glue_dynamic.yaml, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq/main.py, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq/requirements.txt
Signed-off-by: yuwenzho <yuwen.zhou@intel.com>
fix example
hf_bert-base-uncased_dynamic has no acc
[ILITV-2470](https://jira.devtools.intel.com/browse/ILITV-2470)
hf_bert-base-uncased_dynamic failed with DATASETS import
[ILITV-2529](https://jira.devtools.intel.com/browse/ILITV-2529)
extension test on huggingface text classification and question answering models
no
=> Fix ORT old API examples

examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/run_qa_no_trainer_pruneOFA.py
Remove invalid code  
No API changed
=> Removed invalid code

examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/dlrm_s_pytorch.py, examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/run_benchmark.sh, examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_static/fx/run_asr.py
=> fix dlrm and asr benchmark

neural_coder/backends/pytorch_inc_huggingface_optimum_dynamic.yaml, neural_coder/backends/pytorch_inc_huggingface_optimum_static.yaml
yaml file change
Neural Coder update Optimum backend yaml files to reflect Optimum 1.6 API design change
Neural Coder update Optimum backend yaml files to reflect Optimum 1.6 API design change
Locally
No
=> Neural Coder update Optimum backend yaml files to reflect Optimum 1.6 API design change

examples/tensorflow/oob_models/quantization/ptq/README.md, examples/tensorflow/oob_models/quantization/ptq/tf_benchmark.py
bug fix
JIRA ticket: ILITV-2582
[release2nd][tf2.11.0] wide_deep failed TypeError
OOB wide_deep tuning failed issue can be fixed.
UT, Pre-CI and OOB extension test. 
No.
=> Fix OOB wide_deep tuning failed issue

neural_compressor/adaptor/tf_utils/graph_converter.py
Fixed typo.
interation -> interaction
=> Fix typo in graph_converter.py

.azure-pipelines/scripts/models/env_setup.sh, .azure-pipelines/scripts/models/run_mxnet_models_trigger.sh, neural_compressor/experimental/benchmark.py
validation
Fix CI mxnet issue
CI pass
CI test
No
=> Fix CI mxnet issue

examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/requirements.txt, examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_glue.py, examples/pytorch/object_detection/ssd_resnet34/quantization/ptq/fx/python/main.py, examples/pytorch/object_detection/ssd_resnet34/quantization/qat/fx/run_benchmark.sh, examples/pytorch/object_detection/ssd_resnet34/quantization/qat/fx/ssd/main.py
bug fix
bert_large_RTE: https://jira.devtools.intel.com/browse/ILITV-2534
ssd_resnet34_fx: https://jira.devtools.intel.com/browse/ILITV-2577
ssd_resnet34_qat_fx: https://jira.devtools.intel.com/browse/ILITV-2578
=> fix pytorch example bugs

neural_coder/extensions/neural_compressor_ext_lab/neural_compressor_ext_lab/labextension/package-lock.json, neural_coder/extensions/neural_compressor_ext_lab/neural_compressor_ext_lab/labextension/package.json, neural_coder/extensions/neural_compressor_ext_lab/package-lock.json, neural_coder/extensions/neural_compressor_ext_lab/package.json, neural_coder/extensions/neural_compressor_ext_lab_alibaba/package-lock.json, neural_coder/extensions/neural_compressor_ext_lab_alibaba/package.json
bug fix
modify neural coder security
no security issues
no security issues
no
=> modify neural coder security

neural_compressor/utils/pytorch.py
Signed-off-by: Wang, Chang1 <chang1.wang@intel.com>
=> Remove inference for ipex load function

examples/pytorch/nlp/huggingface_models/text-classification/distillation/eager/run_glue_no_trainer_distillation.py, examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/distillation_for_quantization/fx/run_glue_no_trainer.py, examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/prune_once_for_all/fx/run_glue_no_trainer_pruneOFA.py, neural_compressor/adaptor/torch_utils/util.py, neural_compressor/experimental/common/criterion.py
Signed-off-by: XuhuiRen <xuhui.ren@intel.com>
typo fix
no changes on APIs
some code typos when running the example
=> Fixed GPU  and CPU device mixed issue and some typos in the newapi example

.github/workflows/publish.yml, README.md, docs/build_docs/build.sh, docs/build_docs/update_html.py
bug fix for online document
1. correct the versions.html path in all html files.
2. fix git operation error issue.
=> Fix online document build issue

examples/pytorch/recommendation/dlrm/quantization/ptq/fx/README.md, examples/pytorch/recommendation/dlrm/quantization/ptq/fx/dlrm_s_pytorch_tune.py, examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/README.md, examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/dlrm_s_pytorch.py, examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_static/fx/README.md
improve readme.
remove the extra code for dlrm ipex example.
=> Fix recommendation and speech_recognition README

examples/pytorch/object_detection/ssd_resnet34/quantization/ptq/fx/README.md, examples/pytorch/object_detection/ssd_resnet34/quantization/ptq/ipex/README.md, examples/pytorch/object_detection/ssd_resnet34/quantization/qat/fx/README.md
Fix the document for Pytorch examples
None
None
None
None
=> Fix document

neural_coder/coders/tensorflow/inc.py, neural_coder/interface.py, neural_coder/utils/device.py, neural_coder/utils/handle_user_input.py
bug fix
fix tensorflow_inc loading error
bug fix
locally
no
=> Neural  Coder fix tensorflow_inc loading error

neural_compressor/data/datasets/dummy_dataset_v2.py, neural_compressor/experimental/data/datasets/dummy_dataset_v2.py
bug fix
module 'numpy' has no attribute 'bool'
model test pass
extension test
no
=> Replace the np.bool with python built-in bool

neural_compressor/model/tensorflow_model.py, test/model/test_model.py
Signed-off-by: zehao-intel <zehao.huang@intel.com>
API changed or not: No
JIRA ticket: 2635
the expected behavior that triggered by this PR : Fix UT
how to reproduce the test (including hardware information): Preci
any library dependency introduced or removed: No
=> Fix UT of TF QAT Model

neural_compressor/model/torch_model.py, neural_compressor/pruner/pruner_legacy/gradient_sensitivity.py
Fixed bug of pruned weight won't be updated in back propagation with torch as framework.
Signed-off-by: Xinyu Ye <xinyu.ye@intel.com>
Bug fix.
API not changed.
=> Fixed bug of pruned weight won't be updated in back propagation with torch as framework.

neural_compressor/experimental/common/model.py, neural_compressor/experimental/component.py
bug fix
No API changed
Adapt old API to get  framework from yaml configure file
we can run scheduler with yaml configure file.
Local test
=> Fixed scheduler framework error with old API

requirements.txt, setup.py
others
NA
CI passes
CI
remove invalid dependencies.
=> remove invalid requirements

test/export/test_onnx_qlieanr_to_qdq.py
bug fix
**Defect/regression:** 
export/test_onnx_qlieanr_to_qdq.py
AssertionError: Framework is not detected correctly from model format. This could be caused by unsupported model or inappropriate framework installation.
**Profile:** 
Report: https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-nightly/774/artifact/report.html
commit id: e9798e130f0f7d6b1339e26660b257401baf90d6
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-nightly/774/artifact/unittest/ut_tf_2.11.0_pt_1.13.1+cpu.log
**Framework:** onnx
**Framework version:** 1.13.1
JIRA ticket: [ILITV-2638](https://jira.devtools.intel.com/browse/ILITV-2638)
UT test
NO
=> Fix UT test_onnx_qlieanr_to_qdq failure

examples/.config/model_params_onnxrt.json
Signed-off-by: yuwenzho <yuwen.zhou@intel.com>
example
ORT squeezenet_qdq needs to be supported by newapi
JIRA ticket: [ILITV-2591](https://jira.devtools.intel.com/browse/ILITV-2591)
extension test: squeezenet_qdq
no
=> ORT squeezenet_qdq support new api

neural_compressor/adaptor/torch_utils/util.py
Fix bug of export scale info, before the scale info is collected from last sample.
=> fix bug of export scale info

examples/pytorch/image_recognition/torchvision_models/self_distillation/eager/README.md, examples/pytorch/image_recognition/torchvision_models/self_distillation/eager/main.py
Update self-distillation example code and README  
No API changed
Remove invalid code and enhancement README
Local tested
=> Update self distillation example code and README

examples/README.md
Signed-off-by: YIYANGCAI <yiyang.cai@intel.com>
documentations
=> Fixed old pruning examples link bugs.

neural_compressor/adaptor/torch_utils/hawq_metric.py
=> add bias and using standards random initial metric in hessian computation

.azure-pipelines/scripts/ut/collect_log.sh, .azure-pipelines/scripts/ut/env_setup.sh, .azure-pipelines/scripts/ut/run_basic_adaptor.sh, .azure-pipelines/scripts/ut/run_basic_ipex.sh, .azure-pipelines/scripts/ut/run_basic_itex.sh, .azure-pipelines/scripts/ut/run_basic_others.sh, .azure-pipelines/scripts/ut/run_basic_pruning.sh, .azure-pipelines/scripts/ut/ut_fwk_version.sh, .azure-pipelines/template/ut-template.yml, .azure-pipelines/ut-basic-no-cover.yml, .azure-pipelines/ut-basic.yml
validation
Enhance CI with multiple fwk version test support
CI pass
CI
No
=> multiple fwk version ut test support

.azure-pipelines/ut-basic.yml
validation
fix CI UT coverage minor issue
CI pass
CI
No
=> fix CI UT coverage minor issue

docs/source/validated_model_list.md
update model perf data
update validated_model_list.md
update data 
no need test
no
=> update V2.0 release data

examples/pytorch/image_recognition/torchvision_models/optimization_pipeline/prune_and_ptq/fx/main.py, examples/pytorch/image_recognition/torchvision_models/optimization_pipeline/qat_during_prune/eager/main.py, neural_compressor/adaptor/pytorch.py, neural_compressor/experimental/export/torch2onnx.py, neural_compressor/model/torch_model.py
add reduce range for export, fix bug in example.
make sure onnx model accuracy correct on machine without vnni.
=> add reduce range for export

examples/pytorch/diffusion_model/diffusers/textual_inversion/README.md
It's not necessary anymore to be logged in to download the model. Might be confusing for the reader :-)
=> No need to be logged in for model download

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, docs/source/quantization_mixed_precision.md
Documentation enhancement.  
No API changed
=> Update quantization with mixed precision document

docs/source/fp8.md
Signed-off-by: XuhuiRen <xuhui.ren@intel.com>
Fix typos.
=> Fix typos in FP8.md

neural_coder/docs/SupportMatrix.md
bug fix 
no
modify invalid link
valid link
click link
no
=> modify invalid link

examples/README.md
Signed-off-by: zehao-intel <zehao.huang@intel.com>
API changed or not： No
JIRA ticket: NA
the expected behavior that triggered by this PR : As title
how to reproduce the test (including hardware information): preci
any library dependency introduced or removed: No
=> Fix Readme Link Issue of TF Object Detection Examples

neural_compressor/adaptor/pytorch.py
Signed-off-by: Cheng, Zixuan <zixuan.cheng@intel.com>
- add torch version limit >=1.12.0
- change input from dict to namedtuple
JIRA ticket: https://jira.devtools.intel.com/browse/NLPTOOLKIU-393
=> Improve code for getting example inputs for IPEX backend

README.md, examples/README.md
documentation 
fix example README.md link
=> update example README.md link

neural_compressor/adaptor/pytorch.py
change list to tuple in example_input, because jit only allows tensor or tuple of tensor.
=> change list to tuple

examples/pytorch/recommendation/dlrm/quantization/ptq/fx/dlrm_s_pytorch_tune.py
bug fix.
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/3885/artifact/linux/pytorch/dlrm_fx/pytorch-dlrm_fx-linux-clx250-tune.log
dlrm_fx tuning process miss the eval function.
=> Fix dlrm fx example

examples/pytorch/diffusion_model/diffusers/textual_inversion/distillation_for_quantization/README.md, examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/README.md, examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/main.py, examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/requirements.txt
Supported multi-nodes for QAT on ResNet.
Signed-off-by: Xinyu Ye <xinyu.ye@intel.com>
Supported multi-nodes for an example.
API not changed.
=> Supported multi-nodes for QAT on ResNet.

neural_coder/extensions/neural_compressor_ext_lab/neural_compressor_ext_lab/labextension/package-lock.json, neural_coder/extensions/neural_compressor_ext_lab/package-lock.json, neural_coder/extensions/neural_compressor_ext_lab_alibaba/package-lock.json, neural_coder/extensions/neural_compressor_ext_lab_alibaba/package.json
Signed-off-by: Yue, Wenjiao <wenjiao.yue@intel.com> 
bug fix 
modify neural coder security 
no security issues 
no security issues 
no
=> Neural coder security

examples/.config/model_params_onnxrt_win.json, examples/.config/model_params_pytorch_win.json, examples/.config/model_params_tensorflow_win.json, examples/onnxrt/object_detection/onnx_model_zoo/DUC/quantization/ptq/main.py
validation
add new model in windows
add new model in windows 
extension test
no
=> add new models in windows

examples/pytorch/image_recognition/torchvision_models/distillation/eager/README.md, examples/pytorch/image_recognition/torchvision_models/distillation/eager/main.py, examples/pytorch/image_recognition/torchvision_models/distillation/eager/requirements.txt
Added distributed training support for distillation of Resnet50.
introduced accelerate
=> Added distributed training support for distillation of Resnet50.

neural_compressor/adaptor/tf_utils/graph_converter.py, neural_compressor/utils/utility.py
bug fix
JIRA ticket: ILITV-2711
The OOM issue can be fixed.
Pre-CI and model test.
No.
=> Release calibration model memory to fix OOM for tensorflow

neural_compressor/utils/logger.py, test/utils/test_logger.py
Signed-off-by: spycsh <sihan.chen@intel.com>
UT
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-weekly/97/artifact/unittest/coverage_results/htmlcov/d_68928affcedb69ac_logger_py.html
coverage up
None
None
=> add UT for logger

.azure-pipelines/model-test.yml
Signed-off-by: XuehaoSun <xuehao.sun@intel.com>
Add new Azure agent pool for Model-Test
MODEL_PERF_TEST onnx, mxnet and pytorch model.
MODEL_PERF_TEST_TF for TensorFlow model.
Azure pipeline Model-Test succeed.
=> Add new Azure agent pool for Model-Test

neural_compressor/model/tensorflow_model.py
bug fix
JIRA ticket: ILITV-2651
[TF1.15.0-up3] yolo_v3 module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'  can be fixed.
No.
=> Fix list_physical_devices issue for yolo_v3 model

examples/.config/model_params_onnxrt_win.json
validation
add hf_roberta-base_dynamic to windows
no 
no
no
=> add hf_roberta-base_dynamic to windows

examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/README.md, examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/run_tuning.sh
=> update yolo_v3 readme

examples/README.md
documentation 
update example readme
=> update example readme

README.md
documentation update
update the link of APIs.
=> Update for APIs link in README.md

examples/.config/model_params_pytorch.json, examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/main.py
bug fix
JIRA ticket: [ILITV-2727](https://jira.devtools.intel.com/browse/ILITV-2727)
=> Fixed distributed dataloader caused QAT benchmark issue

neural_compressor/adaptor/tf_utils/graph_rewriter/generic/convert_add_to_biasadd.py, neural_compressor/adaptor/tf_utils/graph_rewriter/generic/split_shared_input.py, neural_compressor/adaptor/tf_utils/quantize_graph/quantize_graph_for_intel_cpu.py, neural_compressor/adaptor/tf_utils/quantize_graph/quantize_graph_matmul.py
bug fix
JIRA ticket: ILITV-2725
Customer models quantization issues can be fixed.
Pre-CI and OOB extension test.
No.
=> Fix customer LSTM model quantization issues

examples/README.md, examples/tensorflow/image_recognition/tensorflow_models/distillation/README.md, examples/tensorflow/image_recognition/tensorflow_models/distillation/main.py, examples/tensorflow/image_recognition/tensorflow_models/distillation/run_distillation.sh, neural_compressor/data/transforms/transform.py, neural_compressor/experimental/data/transforms/transform.py
feature
JIRA ticket: ILITV-2723
Enable tensorflow newapi distillation example.
Pre-CI and model test.
No.
=> Enable tensorflow newapi distillation example

neural_compressor/adaptor/tensorflow.py
bug fix
JIRA ticket: ILITV-2726
The tensorflow tf nightly v2.13 can run well with INC.
Pre-CI and OOB extension test.
No.
=> Support tensorflow v2.13 version

neural_compressor/adaptor/onnxrt.py
feature
API changed
Enhancement memory usage for ONNXRT quantization
JIRA ticket: [ILITV-2709](https://jira.devtools.intel.com/browse/ILITV-2709)
no
=> Enhancement memory usage for ONNXRT quantization

neural_compressor/config.py
=> Fixed the docstring miss

neural_compressor/pruner/patterns.py, test/pruning/test_pruning_regs.py
Signed-off-by: YIYANGCAI <yiyang.cai@intel.com>
=> Fixed bug when regularization is applied and zero elements overflows.

.azure-pipelines/template/docker-template.yml, neural_compressor/__init__.py
validation 
fix force stop workspace clean issue
CI
CI
No
=> fix force stop workspace clean issue

neural_compressor/config.py, neural_compressor/strategy/strategy.py, test/config/test_config.py
bug fix 
add default value for recipes
=> add default value for recipes

docs/source/mixed_precision.md, docs/source/quantization_mixed_precision.md
documentation
minor document fix
=> minor document fix

neural_compressor/adaptor/onnxrt.py, neural_compressor/adaptor/ox_utils/util.py
bug fix
JIRA ticket: [ILITV-2612](https://jira.devtools.intel.com/browse/ILITV-2612)
=> Enable onnx model quantization with trt ep

examples/onnxrt/image_recognition/unet/quantization/ptq/main.py
=> fix onnx unet

neural_compressor/strategy/strategy.py, neural_compressor/strategy/utils/tuning_sampler.py, neural_compressor/strategy/utils/tuning_space.py
=> Remove some useless log

neural_compressor/adaptor/onnxrt.py
bug fix 
API not changed 
ORT domain detection failed for large model
local test
no
=> Fix ORT domain detection failure for large model

neural_compressor/adaptor/onnxrt.py, neural_compressor/adaptor/ox_utils/quantizer.py, neural_compressor/experimental/benchmark.py, neural_compressor/model/onnx_model.py, test/model/test_onnx_model.py
feature
Refine ORT QDQ graph
JIRA ticket: [ILITV-2734](https://jira.devtools.intel.com/browse/ILITV-2734)
extension test of QDQ models
no
=> Refine ORT QDQ quantization graph

examples/onnxrt/image_recognition/onnx_model_zoo/fcn/quantization/ptq/README.md
=> Fix example readme

neural_compressor/conf/config.py, test/config/test_config.py
Remove version check in user yaml schema.
No API changed
Schema will not check the version in user yaml. 
JIRA ticket: [#2588](https://jira.devtools.intel.com/browse/ILITV-2588)
Not check the version in user yaml file. 
Local test
=> Remove version check in user yaml schema

neural_compressor/contrib/strategy/tpe.py
bug fix  
JIRA ticket: [ILITV-2738](https://jira.devtools.intel.com/browse/ILITV-2738)
Pre-CI
None
=> fix KeyError for tpe tuning

examples/helloworld/tf_example1/README.md, examples/helloworld/tf_example5/README.md, examples/helloworld/tf_example6/README.md, examples/tensorflow/image_recognition/SavedModel/mobilenet_v1/quantization/ptq/README.md, examples/tensorflow/image_recognition/SavedModel/mobilenet_v2/quantization/ptq/README.md
documentation 
fix imagenet dataset prepare path
=> fix imagenet dataset prepare path

.azure-pipelines/template/docker-template.yml, .azure-pipelines/template/ut-template.yml, .azure-pipelines/ut-basic-no-cover.yml, .azure-pipelines/ut-ncoder.yml, .azure-pipelines/ut-ux.yml, neural_compressor/__init__.py
validation
CI enhance for the interrupt cases
=> CI enhance for the interrupt cases

test/scheduler/test_oneshot.py, test/scheduler/test_orchestration.py
add UT test for distillation_for_quantization with gpu
=> add UT for distillation_for_quantization with gpu

.azure-pipelines/template/docker-template.yml, .azure-pipelines/ut-ncoder.yml, .azure-pipelines/ut-ux.yml, neural_compressor/version.py, setup.py
validation 
minor fix for CI workspace clean
CI pass
CI
No
=> minor fix for CI workspace clean

examples/.config/model_params_pytorch.json, examples/README.md, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/LICENSE, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/PeleeNet_README.md, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/README.md, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/main.py, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/peleenet.py, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/requirements.txt, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_benchmark.sh, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_tuning.sh, examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/README.md, examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/requirements.txt, examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_benchmark.sh, examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_translation.py, examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_tuning.sh
Migrate NLP translation and peleenet examples to INC new API
README refined
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2625
N/A
extension test
**topologies in this PR**:peleenet, t5_WMT_en_ro, marianmt_WMT_en_ro
N/A
=> migrate translation and peleenet examples

neural_compressor/benchmark.py
JIRA ticket: [NLPTOOLKIU-445](https://jira.devtools.intel.com/browse/NLPTOOLKIU-445)
=> enhance benchmark

docs/build_docs/build.sh
documentation
fix link issue in README.md & user_guide.md for online document.
=> fix link issue in README.md & user_guide.md

.azure-pipelines/docker/DockerfileCodeScan.devel
validation 
Freeze the bandit version into v1.7.4 to keep CI working. And the version limit will be removed after issue fix. 
CI pass
CI
No
=> freeze the bandit version

neural_compressor/adaptor/ox_utils/quantizer.py, neural_compressor/adaptor/ox_utils/util.py, neural_compressor/strategy/utils/tuning_space.py, test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
bug fix
improve quantization speed for LLM and fix config
=> improve quantization speed for LLM

examples/pytorch/nlp/huggingface_models/text-classification/distillation/eager/requirements.txt, examples/pytorch/nlp/huggingface_models/text-classification/distillation/eager/run_glue_no_trainer_distillation.py
fix the version limitation and the code
=> bug fix for distillation on text classification example

examples/README.md
remove extra part in examples README
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2720
=> remove extra part in examples README

neural_compressor/experimental/metric/metric.py, test/data/test_exp_transformers.py, test/metric/test_exp_metrics.py
improve UT coverage
neural_compressor/experimental/metric/metric.py
neural_compressor/experimental/data/transforms/imagenet_transform.py
Line 81%->85%, branch 71% -> 80% 
UT 
No
=> Improve transform and metric UT

docs/source/migration.md, examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py, examples/tensorflow/image_recognition/tensorflow_models/efficientnet-b0/quantization/ptq/main.py, neural_compressor/config.py
bug fix 
No API changed
fixed variable name error for “op_name_dict" 
JIRA ticket: [#2769](https://jira.devtools.intel.com/browse/ILITV-2769)
Quantize model successfully for tensorflow framework
local tested
=> fixed variable name error

neural_compressor/compression/pruner/criteria.py
bug fix
JIRA ticket: None
Issue: [#592](https://github.com/intel/neural-compressor/issues/592)
None
CI and example tests
None
=> Pruning magnitude criterion bugfix.

neural_compressor/adaptor/onnxrt.py, neural_compressor/adaptor/ox_utils/calibration.py, neural_compressor/adaptor/ox_utils/util.py
bug fix
JIRA ticket: 
https://jira.devtools.intel.com/browse/ILITV-2767
https://jira.devtools.intel.com/browse/ILITV-2768
pre-ci and extension test pass
extension test
no
=> Fix ort adaptor

neural_compressor/data/dataloaders/tensorflow_dataloader.py
bug fix
JIRA ticket: https://github.com/intel/neural-compressor/issues/617
The tensorflow dataloader issue can be fixed.
Pre-CI and model test.
No.
=> Fix tensorflow dataloader issue

neural_compressor/compression/pruner/README.md
=> readme typo fix

neural_compressor/compression/pruner/utils.py, test/pruning_2.x/test_pruning_criteria.py, test/pruning_2.x/test_pruning_regs.py, test/pruning_2.x/test_pruning_types.py
=> add unit test for algorithm part

examples/onnxrt/image_recognition/mobilenet_v2/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/mobilenet_v3/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/onnx_model_zoo/alexnet/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/onnx_model_zoo/caffenet/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/onnx_model_zoo/densenet/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/onnx_model_zoo/efficientnet/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/onnx_model_zoo/googlenet/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/onnx_model_zoo/inception/quantization/ptq_static/requirements.txt
others, no API change 
Remove onnx/onnxruntime version limit
Models run successfully. 
CI
onnx/onnxruntime version update, no impact to the BoM.
=> Remove onnx/onnxruntime version limit

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md
Documentation 
No API change
Refine the format of SmoothQuant results
No impact
Only documentation, check spell 
No
=> refine smooth quant readme

neural_compressor/compression/pruner/README.md
documentation
fix typos of pruner doc(readme)
=> Pruner doc fix

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, README.md, docs/source/publication_list.md, docs/source/user_guide.md
documentation 
1. Update feature doc links, 
2. Update publication
No
CI
No
=> update links for documentation

docs/source/tuning_strategies.md
documentation 
JIRA ticket: [ILITV-2743](https://jira.devtools.intel.com/browse/ILITV-2743)
Pre-CI
None
=> Update the doc for tuning strategy

test/scheduler/test_orchestration.py
Enhancement UT  
No API changed
Add orchestration UT case with distillation, pruning and qat
Support oneshot training with distillation, pruning and qat.
local tested
=> Add orchestration UT case with distillation, pruning and qat

neural_compressor/adaptor/ox_utils/operators/concat.py, neural_compressor/adaptor/ox_utils/operators/ops.py, neural_compressor/adaptor/ox_utils/operators/split.py, neural_compressor/conf/pythonic_config.py, test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py, test/config/test_pythonic_config.py, test/data/test_exp_dataloader.py
enhance ut and bug fix
enhance ut and bug fix
pre-ci test and ut coverage test pass
pre-ci test and ut coverage test
no
=> Improve UT coverage and fix bug

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md
Documentation
No API change
fix incorrect link
no impact
Only documentation, check spell
no
=> fix incorrect link

examples/pytorch/image_recognition/ResNet50/pruning/eager/README.md, examples/pytorch/image_recognition/ResNet50/pruning/eager/run_resnet50_prune.sh, examples/pytorch/image_recognition/ResNet50/pruning/eager/train.py
bugfix
add no cuda option for multinode cpu training
user will be able to set device themselves.
CI and example test
no
=> enhance resnet50 pruning examples

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, examples/pytorch/image_recognition/ResNet50/pruning/eager/README.md, examples/pytorch/image_recognition/ResNet50/pruning/eager/train.py
Example enabling
Enabled multi-nodes pruning of ResNet50 on cpu device.
results on multi-nodes is comparable with single node.
follow readme
=> Enabled multi-nodes pruning of ResNet50 on cpu device.

examples/.config/model_params_onnxrt.json, examples/onnxrt/object_detection/onnx_model_zoo/faster_rcnn/quantization/ptq_static/README.md, examples/onnxrt/object_detection/onnx_model_zoo/faster_rcnn/quantization/ptq_static/main.py, examples/onnxrt/object_detection/onnx_model_zoo/mask_rcnn/quantization/ptq_static/README.md, examples/onnxrt/object_detection/onnx_model_zoo/mask_rcnn/quantization/ptq_static/main.py, examples/onnxrt/object_detection/onnx_model_zoo/ssd/quantization/ptq_static/README.md, examples/onnxrt/object_detection/onnx_model_zoo/ssd/quantization/ptq_static/data_utils.py, examples/onnxrt/object_detection/onnx_model_zoo/ssd_mobilenet_v1/quantization/ptq_static/README.md, examples/onnxrt/object_detection/onnx_model_zoo/ssd_mobilenet_v1/quantization/ptq_static/data_utils.py, examples/onnxrt/object_detection/onnx_model_zoo/tiny_yolov3/quantization/ptq_static/README.md, examples/onnxrt/object_detection/onnx_model_zoo/tiny_yolov3/quantization/ptq_static/main.py, examples/onnxrt/object_detection/onnx_model_zoo/yolov3/quantization/ptq_static/README.md, examples/onnxrt/object_detection/onnx_model_zoo/yolov3/quantization/ptq_static/main.py, examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq_static/README.md, examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq_static/main.py, examples/onnxrt/object_detection/ssd_mobilenet_v1/quantization/ptq_static/README.md, examples/onnxrt/object_detection/ssd_mobilenet_v1/quantization/ptq_static/data_utils.py, examples/onnxrt/object_detection/ssd_mobilenet_v2/quantization/ptq_static/README.md, examples/onnxrt/object_detection/ssd_mobilenet_v2/quantization/ptq_static/data_utils.py
document
API not change
Update coco dataset path in ort obj detection example
/tf_dataset2/datasets/coco2017/coco  8
/tf_dataset/dataset/coco_dataset/raw-data   8
 --> /tf_dataset2/datasets/coco2017/coco/val2017
no regression in acc & perf 
extension test 
no
=> Update coco dataset path in ort obj detection example

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, docs/source/quantization.md, neural_compressor/quantization.py
documentation of quantization 
No API changed
Improve quantization document
=> Improve quantization document

neural_compressor/utils/pytorch.py
change assert is_int8_model to warning
sometimes the loaded model may be a pure bf16 model, we should allow this situation.
no error in model test.
N/A
N/A
=> change assert to warning

docs/source/get_started.md, docs/source/user_guide.md, examples/.config/model_params_pytorch.json, examples/README.md, examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
documentation 
Update user guide structure, fix some description in docs 
No
CI
No
=> Update user guide structure

neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
bug fix 
API not changed 
ILITV-2783: ITEX oneDNN graph crash on ResNet101 model for QDQ dtype mismatch before and after MaxPool
Fixed oneDNN graph crash issue.
pre-CI and OOB extension test.
No.
=> Fix ITEX oneDNN graph crash issue for MaxPool QDQ dtype mismatch

neural_compressor/experimental/pruning_v2.py, neural_compressor/experimental/pytorch_pruner/logger.py, test/pruning_1.x_v2/test_tensorflow_pruning.py
ut-test
add ut-test to fix code coverage issues.
Improve related source codes' code coverage to target ratio. 
Pre-CI
None
=> Pruning code coverage ut-test modification

neural_compressor/adaptor/onnxrt.py, neural_compressor/model/onnx_model.py, neural_compressor/strategy/utils/constant.py
bug fix 
Fix ORT query fw capability
extension test pass
extension test
No
=> Fix ORT query fw capability

examples/onnxrt/nlp/bert/quantization/ptq_dynamic/README.md, examples/onnxrt/nlp/bert/quantization/ptq_static/README.md, examples/onnxrt/nlp/distilbert/quantization/ptq_dynamic/README.md, examples/onnxrt/nlp/distilbert/quantization/ptq_static/README.md, examples/onnxrt/nlp/mobilebert/quantization/ptq_dynamic/README.md, examples/onnxrt/nlp/mobilebert/quantization/ptq_static/README.md, examples/onnxrt/nlp/onnx_model_zoo/BiDAF/quantization/ptq_dynamic/README.md, examples/onnxrt/nlp/onnx_model_zoo/BiDAF/quantization/ptq_dynamic/main.py, examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/README.md, examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/export.py, examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/README.md, examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/export.py, examples/onnxrt/nlp/roberta/quantization/ptq_static/README.md, examples/onnxrt/nlp/roberta/quantization/ptq_static/export.py
documentation
Refine ORT example doc: gpt2, roberta, bidaf mobilebert
doc update
manual test
no
=> Refine ORT example doc

examples/onnxrt/body_analysis/onnx_model_zoo/arcface/quantization/ptq_static/README.md, examples/onnxrt/body_analysis/onnx_model_zoo/emotion_ferplus/quantization/ptq_static/README.md, examples/onnxrt/body_analysis/onnx_model_zoo/ultraface/quantization/ptq_static/README.md
doc fix
Update model prepare process
model list: arcface, emotion_ferplus, ultraface
doc update
manual test
no
=> Fix ORT example doc

neural_compressor/data/dataloaders/dataloader.py, neural_compressor/data/datasets/dataset.py, neural_compressor/data/filters/filter.py, neural_compressor/data/transforms/transform.py, neural_compressor/experimental/data/datasets/dataset.py, neural_compressor/experimental/data/filters/filter.py, neural_compressor/experimental/data/transforms/transform.py, neural_compressor/experimental/metric/metric.py, neural_compressor/metric/metric.py
the expected behavior that triggered by this PR ： as title
preci, extension of helloword/tf_example2
No
=> Add Keras to the Framework Checklist

neural_compressor/adaptor/ox_utils/quantizer.py
Fixed typo in log info  
No API changed
Fixed typo in log info 
Log with right format
Local tested
=> fixed typo for log

examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/README.md, examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/run_qa_no_trainer_pruneOFA.py
bug fix
fixed stage2 model load error and updated readme.
example test pass
follow the readme
=> fixed ofa stage2 model load error and updated readme

neural_compressor/adaptor/pytorch.py
accuracy regression fix
change wrong qconfig of dynamic quantization to correct one.
UT pass and accuracy recover
local test
No
=> fix accuracy regression of dynamic quantization

neural_compressor/config.py
Docstring polish
Docstring polish
Docstring is polished
pre-ci
no
=> Docstring polish

examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/run_qa_no_trainer_pruneOFA.py
bug fix.  
Fixed issue of dataloader not prepared before evaluation.
pass extension test.
follow the readme
=> Fixed issue of dataloader not prepared before evaluation.

.azure-pipelines/scripts/models/collect_log_model.py, .azure-pipelines/scripts/models/run_benchmark_common.sh
Only judge whether performance is lower than the previous 10%
Only judge whether performance is lower than the previous 10% in pipeline benchmark stage, not report stage
update Pre-CI logic.
Pre-CI Model-Test pipeline
no
=> Update Azure Pre-CI Model-Test benchmark logic

neural_compressor/config.py
config docstring fix
Fix config.py docstring format issue.
The related class docstring can be showcased well.
Just docstring format change, pydocstyle check.
No.
=> Fix docstring format

neural_compressor/config.py
documentation 
Align MixedPrecisionConfig docstring format
Align MixedPrecisionConfig docstring format
pre-ci
no
=> Align MixedPrecisionConfig docstring format

neural_compressor/config.py
documentation
Added docstring for distillation criterion config.
pass spell check
spell check
=> Added docstring for distillation criterion config.

docs/source/migration.md, neural_compressor/__init__.py, neural_compressor/benchmark.py, neural_compressor/conf/pythonic_config.py, neural_compressor/config.py, neural_compressor/mix_precision.py, neural_compressor/quantization.py
Rename private class with '_' 
API changed
Rename private class with '_' 
Run quantization/benchmark/mixed_precision successfully.
Local tested
=> Rename private class

neural_compressor/config.py
documentation
API changed: None
Make polish for pruning config's docstring.
Users can understand config's details more easily.
PreCI tests
None
=> Pruning config docstring polish

neural_compressor/config.py
add docstring
ExportConfig&Torch2ONNXConfig docstring polish
N/A
N/A
N/A
=> ExportConfig&Torch2ONNXConfig docstring polish

neural_compressor/config.py, test/requirements.txt
Improve docstring of config.py
No API changed
Improve docstring of config.py
Run PTQ/mixed_precision/benchmark successfully 
Local tested
=> Improve docstring of config.py

.azure-pipelines/scripts/models/run_benchmark_common.sh, README.md, docs/source/validated_model_list.md
documentation
1. Update main page 
2. Update results page
NA
CI
No
=> update main page readme

README.md, conda_meta/basic/meta.yaml, conda_meta/full/meta.yaml, neural_compressor/version.py
documentation
bump release version into v2.1
bump binary version
CI
No
=> bump release version into v2.1

README.md
documentation 
update main page format
=> update main page format

docs/build_docs/build.sh, docs/source/export.md, docs/source/platform_configuration.md, docs/source/validated_model_list.md
documentation 
Fix online doc format issues:
a. fix tab format
b. fix link to md file
=> fix tab format, fix link to md file

docs/source/smooth_quant.md
documentation   
update the value distribution of auto tuning smoothquant
no risk
spell test
no
=> update alpha distribution of auto tuning smoothquant

neural_compressor/quantization.py, neural_compressor/training.py
documentation
No API changed
Doc enhancement
=> Fixed the wrong description

neural_compressor/quantization.py
documentation
No API changed
Fixed typo for quantization docstring.
The docstring should correctly describe the quantization process.
=> Fixed typo for quantization docstring

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, docs/source/smooth_quant.md, neural_compressor/compression/pruner/README.md
documentation 
fix smooth quant doc
None
None
=> fix smooth quant doc

.azure-pipelines/scripts/ut/collect_log.sh, .azure-pipelines/scripts/ut/compare_coverage.sh, examples/.config/model_params_onnxrt_win.json, examples/.config/model_params_pytorch_win.json, examples/.config/model_params_tensorflow_win.json
Validation bug fix
Update window test config to support new api.
Pre-CI Bug fix: 
zero before the decimal point cannot be displayed.
coverage details cannot be displayed.
Windows test supports new api.
Pre-CI
No
=> fix window test config and pre-ci ut coverage

examples/tensorflow/nlp/bert_large_squad/quantization/ptq/README.md, examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/README.md, examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/run_benchmark.sh, examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/run_tuning.sh, neural_compressor/data/transforms/transform.py
Jira: https://jira.devtools.intel.com/browse/ILITV-2813
API not changed.
As title
mlperf bert could be run on bert_large_squad_model_zoo example
Preci
No
=> Support mlperf Bert Model on TF backend

examples/.config/model_params_pytorch.json, examples/README.md, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/LICENSE, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/PeleeNet_README.md, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/README.md, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/main.py, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/peleenet.py, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/requirements.txt, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_benchmark.sh, examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_tuning.sh
add peleenet to pytorch examples after fixing the problem
https://jira.devtools.intel.com/browse/ILITV-2786
N/A
extension test
N/A
=> add peleenet to pytorch examples

.azure-pipelines/ut-basic.yml
fix pre-ci ut-coverage docker config issue
fix pre-ci ut-coverage docker config issue
pruning base test succeed
pre-ci
no
=> update pre-ci ut-coverage docker config

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/pytorch_ipex.yaml, neural_compressor/adaptor/torch_utils/model_wrapper.py, neural_compressor/adaptor/torch_utils/smooth_quant.py, neural_compressor/utils/pytorch.py, test/algorithm/test_smooth_quant.py, test/ipex/test_adaptor_ipex.py
enhance smoothquant and ipex op_type capability.
1. support setting matmul op_type in ipex.
2. support load func for SmoothQuant QDQ model on stock PT.
UT pass
local test
N/A
=> Enhance smoothquant and ipex op_type capability.

neural_compressor/compression/pruner/model_slim/auto_slim.py, neural_compressor/compression/pruner/model_slim/pattern_analyzer.py, neural_compressor/compression/pruner/model_slim/weight_slim.py, test/pruning_2.x/test_auto_slim.py
bugfix
Fix a bug in auto slim when processing linear layers whose bias attribute is None.
Able to slim non-bias linear layers
PreCI
None
=> Fix bug for slim non-bias linear layers.

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/smooth_quant.py, neural_compressor/adaptor/torch_utils/util.py
bug fix
mse_v2 failed on transformers models due to input is a instance of UserDict. 
SmoothQuant failed when setting weight, need to convert tensor to Parameter
UT pass
local test
N/A
=> fix mse_v2 failure and sq failure

neural_compressor/adaptor/pytorch.py
add new feature
API changed
Add operators statistics for IPEX backend
Statistics int8 ops for IPEX backend.
Local tested.
=> Add operators statistics for IPEX backend

examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/README.md, examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/scripts/bertmini_sst2_2in4.sh, examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/scripts/bertmini_sst2_4x1.sh, examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/scripts/bertmini_sst2_perchannel.sh, examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/scripts/distilbert_mrpc_2in4.sh, examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/scripts/distilbert_mrpc_4x1.sh
=> pruning scripts typofix

examples/README.md
documentation
Add gptj example link to doc
no
pre-ci
no
=> Add gptj example link to doc

neural_compressor/adaptor/ox_utils/calibration.py
bug fix
[ILITV-2873](https://jira.devtools.intel.com/browse/ILITV-2873)
ONNX mask_rcnn quantize failed
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-weekly/116/artifact/linux/onnxrt/mask_rcnn/onnxrt-mask_rcnn-linux-clx8280-tune.log
onnx 1.13.0 onnxruntime 1.14.1
pass extension test of ONNXRT mask_rcnn
extension test
no
=> Fix ONNXRT mask_rcnn quantize failed

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
[ILITV-2856](https://jira.devtools.intel.com/browse/ILITV-2856)
=> fix clm examples regression

neural_compressor/benchmark.py
fix benchmark iteration issue
N/A
extension test
=> fix benchmark iteration issue

examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py, neural_compressor/adaptor/onnxrt.py, neural_compressor/adaptor/ox_utils/calibration.py, neural_compressor/adaptor/ox_utils/quantizer.py, neural_compressor/adaptor/ox_utils/util.py, neural_compressor/algorithm/smooth_quant.py, test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
feature
Add mul absorbing function for smooth quant of onnxrt adaptor
UT pass
UT, local LLM test
no
=> Add mul absorbing for smooth quant of onnxrt adaptor

examples/README.md
documentation 
Update model link
=> update example link

.azure-pipelines/scripts/ut/env_setup.sh
validation 
Fix CI issue caused by protobuf new version issue.
=> fix for CI issue

examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py, examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/run_ffn_slim_pipeline.py, examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/run_mha_slim_pipeline.py, neural_compressor/compression/__init__.py, neural_compressor/compression/callbacks.py, neural_compressor/compression/pruner/model_slim/README.md, neural_compressor/compression/pruner/model_slim/__init__.py, neural_compressor/compression/pruner/model_slim/auto_slim.py, neural_compressor/compression/pruner/model_slim/pattern_analyzer.py, neural_compressor/compression/pruner/model_slim/weight_slim.py, neural_compressor/experimental/compression/pruning.py, neural_compressor/training.py, test/pruning_2.x/test_auto_slim.py
bug fix
Auto slim and pruning new api's import method will cause torch to be default import, thus relocate them to fix this bug
auto slim's import logic should fit nc's current ones.
PreCI
None
=> Fix slim & pruning torch import issue.

examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/utils/datasets.py
bug fix
Yolo_v3 accuracy is wrong due to labels are not matched exactly.
Accuracy improved
local test
=> bug fix of yolo_v3 labels

docs/source/smooth_quant.md, examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/README.md, examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/main.py, examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/README.md
bug fix
Readme is not correct to fit new design and enhance example capability to support more models.
Existing test pass.
local test on other kind of model in torchvision, such as densenet121.
=> fix document, example readme and code

docs/source/validated_model_list.md, examples/README.md
documentation 
Specify ONNX model zoo in validated model list
no
=> Specify ONNX model zoo in validated model list

neural_compressor/adaptor/ox_utils/calibration.py
bug fix
Fix onnx Clip node bug
no
=> Fix onnx Clip node bug

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/README.md
=> fix clm readme

.azure-pipelines/scripts/models/env_setup.sh, .azure-pipelines/scripts/models/run_onnxrt_models_trigger.sh, .azure-pipelines/scripts/models/run_pytorch_models_trigger.sh, .azure-pipelines/scripts/models/run_tensorflow_models_trigger.sh, .azure-pipelines/scripts/ut/env_setup.sh, .azure-pipelines/scripts/ut/ut_fwk_version.sh
validation
1. Update CI FWs version. 
2. Freeze horovod version for TF spr-base CI test. 
CI pass
CI
No
=> CI FWs version update

neural_compressor/adaptor/pytorch.py
1. Modify the built-in inference func replace calib func that was missed before
2. Correct the logical order of q_dataloader and q_func
=> fix pytorch adaptor issue

neural_coder/backends/keras_inc.yaml, neural_coder/backends/onnx_inc_dynamic_quant.yaml, neural_coder/backends/onnx_inc_static_quant_qdq.yaml, neural_coder/backends/onnx_inc_static_quant_qlinear.yaml, neural_coder/coders/tensorflow/inc.py
feature
For TF and ONNX framework
Coder support new API
NA
No
=> Adapt Neural Coder to INC New API TF and ONNX part

examples/helloworld/tf_example7/README.md, examples/helloworld/tf_example7/test.py
Jira: [ILITV-2887](https://jira.devtools.intel.com/browse/ILITV-2887)
Fix 
Extension
No
=> Fix Regression of Helloworld Example tf_example7

neural_compressor/adaptor/tensorflow.py, neural_compressor/adaptor/tensorflow.yaml, neural_compressor/adaptor/tf_utils/graph_rewriter/generic/convert_add_to_biasadd.py, neural_compressor/adaptor/tf_utils/util.py, test/tfnewapi/test_tensorflow_graph_conv_fusion.py
feature
Support the new spr-base version '2.11.0202317'
No regression issues will be found when using the new spr-base version.
No.
=> Support new spr-base version '2.11.0202317'

examples/.config/model_params_pytorch.json, examples/README.md, examples/onnxrt/nlp/roberta/quantization/ptq_static/requirements.txt, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/requirements.txt, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/requirements.txt, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/run_tuning.sh, examples/pytorch/nlp/huggingface_models/text-classification/export/fx/requirements.txt, examples/pytorch/speech_recognition/whisper_large/quantization/ptq_dynamic/fx/run_whisper_large.py
documentation 
1. add deps accelerate to adopt transformers==4.29.0
2. support gpt-j-6B_sq in test
3. add openai/whisper-large into example list
CI pass
CI
No
=> Update examples deps and readme

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/util.py
bug fix
Modify the built-in inference func replace calib func that was missed before
=> fix ipex adaptor remaining issue

.azure-pipelines/scripts/ut/ut_fwk_version.sh
validation 
update tf 2.12.0 from intel-tensorflow into stock tensorflow to avoid distribute issue
CI pass
CI
No
=> install official tensorflow 2.12 for CI test

neural_compressor/compression/callbacks.py, test/distillation/test_distillation_2.x.py
API  not changed
Jira: [ILITV-2889](https://jira.devtools.intel.com/browse/ILITV-2889)
Fix
Extension
No
=> Fix Regression of TF Distillation Example

neural_compressor/adaptor/ox_utils/util.py
bug fix
Fix fold scale bug
bert_base pass
no
=> Fix fold scale bug

test/distillation/test_distillation_2.x.py, test/mixed_precision/test_mixed_precision_keras_model.py
Jiar: [ILITV-2904](https://jira.devtools.intel.com/browse/ILITV-2904)
Shorten running time of UTs
PreCI
No
=> Optimize the Running time of Keras Mix-precision UTs

neural_compressor/adaptor/pytorch.py
origin : if we don't provide the eval_func, the model will not be deepcoied, it will cause we use prepared_model as the smooth quant input.
current: add condition to check, if it used smoothquant, will deepcopy it to avoid the error.
root cause:  smoothquant order after get quantizable ops. IPEX adaptor quantization will covert model to prepared model when get quantizable  op capalibities
=> fix smoothquant deepcopy issue

.azure-pipelines/scripts/ut/run_basic_adaptor.sh, .azure-pipelines/scripts/ut/run_basic_adaptor_tfnewapi.sh, .azure-pipelines/scripts/ut/run_basic_ipex.sh, .azure-pipelines/scripts/ut/run_basic_itex.sh, .azure-pipelines/scripts/ut/run_basic_others.sh, .azure-pipelines/scripts/ut/run_basic_pruning.sh, .azure-pipelines/scripts/ut/run_ncoder.sh, .azure-pipelines/scripts/ut/run_ux.sh, .azure-pipelines/scripts/ut/ut_fwk_version.sh, test/distributed/test_distributed_metrics.py
validation
1. update TF version into intel tf to avoid core dump issue. 
2. limit TF version for TF distribute test
Template setting before root cause, to make sure the CI work smoothly. 
CI
CI pass
No
=> limit TF version for TF distribute test

neural_compressor/adaptor/tensorflow.py, test/mixed_precision/test_mixed_precision_keras_model.py
Add assertion to prevent customers from using dynamic quantization on TF framework.
As titled
PreCI
No
=> Add Check of Dynamic Quantization for TF Adaptor

examples/keras/image_recognition/inception_resnet_v2/quantization/ptq/main.py, examples/keras/image_recognition/inception_v3/quantization/ptq/main.py, examples/keras/image_recognition/mobilenet_v2/quantization/ptq/main.py, examples/keras/image_recognition/resnet101/quantization/ptq/main.py, examples/keras/image_recognition/resnet50/quantization/ptq/main.py, examples/keras/image_recognition/resnet50_fashion/quantization/ptq/main.py, examples/keras/image_recognition/resnetv2_101/quantization/ptq/main.py, examples/keras/image_recognition/resnetv2_50/quantization/ptq/main.py, examples/keras/image_recognition/vgg16/quantization/ptq/main.py, examples/keras/image_recognition/vgg19/quantization/ptq/main.py, examples/keras/image_recognition/xception/quantization/ptq/main.py
Jira:[ILITV-2905](https://jira.devtools.intel.com/browse/ILITV-2905)
As title
Fix
Extension
No
=> Fix Accuracy Regression of Keras Model inception_resnet_v2

neural_compressor/strategy/basic.py, neural_compressor/strategy/strategy.py, neural_compressor/utils/utility.py, test/strategy/test_bayesian.py, test/strategy/test_mse.py, test/strategy/test_quant_level.py, test/strategy/test_random.py
bug fix
Fixed tuning config comparison
Fixed tuning config comparison and skipped the evaluated tuning config
Pre-CI
None
=> Fixed tuning config comparison

neural_compressor/adaptor/pytorch.py
bug fix
Fallbacked convolutions in stats are not correct for Resnet18.
=> fix pt stats bug

requirements.txt, setup.py
add deprecated version limit when installing because some lower version may cause errors  
related JIRA: https://jira.devtools.intel.com/browse/NLPTOOLKIU-607
=> add deprecated version limit

neural_compressor/adaptor/pytorch.py
=> change error to warning

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, README.md, docs/source/publication_list.md, docs/source/quantization.md
documentation 
update readme and publications
=> update readme and publications

examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/run_qa_no_trainer.py, examples/pytorch/nlp/huggingface_models/translation/pruning/eager/requirements.txt, examples/pytorch/object_detection/yolo_v5/pruning/eager/README.md
=> refine pruning example info

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/smooth_quant.py, test/algorithm/test_smooth_quant.py
bug fix
resolve out-of-memory caused by smoothquant.
ut pass
local test
=> resolve memory issue

neural_compressor/adaptor/ox_utils/operators/gather.py, neural_compressor/adaptor/ox_utils/operators/matmul.py, test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py, test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py, test/config/test_pythonic_config.py
enhancement
Enhance MatMul and Gather quantization
whisper model can have good accuracy
no
=> Enhance MatMul and Gather quantization

neural_compressor/adaptor/pytorch_ipex.yaml, neural_compressor/strategy/utils/tuning_sampler.py, neural_compressor/strategy/utils/tuning_space.py, test/strategy/test_tuning_space_v2.py
bug fix
1. fix op_type mismatch issue caused by PR recently
2. support tuple op_name fallback 
3. change fallback op_name info from debug mode to info mode
UT pass
UT
N/A
=> fix bug in ipex fallback

neural_compressor/benchmark.py, neural_compressor/model/tensorflow_model.py, neural_compressor/quantization.py, neural_compressor/utils/neural_insights_utils.py, test/model/test_model.py
Feature
Added model_path property to TensorflowBaseModel
Model path accessible via model_path property if INC Model instance has been created using model path.
UTs
None
=> Add model_path property to TensorflowBaseModel

neural_compressor/adaptor/onnxrt_cuda.yaml, neural_compressor/adaptor/ox_utils/operators/activation.py, neural_compressor/adaptor/ox_utils/operators/binary_op.py, neural_compressor/adaptor/ox_utils/operators/concat.py, neural_compressor/adaptor/ox_utils/operators/direct_q8.py, neural_compressor/adaptor/ox_utils/operators/matmul.py, neural_compressor/adaptor/ox_utils/operators/norm.py, neural_compressor/adaptor/ox_utils/operators/ops.py, neural_compressor/adaptor/ox_utils/operators/reduce.py, neural_compressor/adaptor/ox_utils/operators/split.py, neural_compressor/adaptor/ox_utils/operators/unary_op.py, neural_compressor/adaptor/ox_utils/quantizer.py, test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
feature
Add fp16 ops for onnxrt adaptor
Add fp16 ops for onnxrt adaptor
test with GPU and onnxruntime-gpu
no
=> Add fp16 ops for onnxrt adaptor

examples/README.md
documentation
add example links
for quick lookup of examples
None
None
=> Update tensorflow sq llm example links

setup.py
=> Add missing comma to Neural Insights packages list

examples/.config/model_params_tensorflow.json, examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/run_tuning.sh
validation 
support non-sq test for TF LLM examples
extension test pass
extension test 
No
=> support non sq TF LLM

test/requirements.txt
Signed-off-by: Maciej Szankin <maciej.szankin@intel.com>
=> Update DyNAS-T to 1.3.0

docs/source/smooth_quant.md
=> Edit support matrix doc

neural_compressor/experimental/export/torch2onnx.py
In this PR we enable the possibility to give a dictionary as model inputs for the ONNX export, allowing the ONNX export of model such as GPT2, for which an ordered tuple is not enough : needs to explicitely specify the input names as so that the `attention_mask` are not considered as [`past_key_values`](https://github.com/huggingface/transformers/blob/v4.29.2/src/transformers/models/gpt2/modeling_gpt2.py#L1051)
=> Allow dictionary model inputs for onnx export

neural_compressor/adaptor/ox_utils/operators/gather.py
bug fix
Fix corner case of Gather op during quantization
pre-ci pass
local example test
no
=> Fix Gather op

.azure-pipelines/scripts/models/generate_report.sh, .azure-pipelines/scripts/ut/collect_log.sh
Adjust Pre CI test gap detection range.
Unit test -0.05%
Model test ±8%
No
Pre CI
No
=> Adjust Pre CI test gap detection range

neural_compressor/utils/utility.py
bug fix
quantization process exits early with Python 3.11
Pre-CI and Ext Test
None
=> Fixed timeout

examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py, examples/pytorch/nlp/huggingface_models/question-answering/model_slim/README.md, examples/pytorch/nlp/huggingface_models/question-answering/model_slim/requirements.txt, examples/pytorch/nlp/huggingface_models/question-answering/model_slim/run_qa_no_trainer_auto_slim.py, neural_compressor/compression/pruner/__init__.py, neural_compressor/compression/pruner/model_slim/README.md, neural_compressor/compression/pruner/model_slim/pattern_analyzer.py, neural_compressor/compression/pruner/model_slim/weight_slim.py, neural_compressor/compression/pruner/patterns.py, neural_compressor/compression/pruner/pruners.py, test/pruning_2.x/test_auto_slim.py
Documentation
Remove redundant codes related to debug, refine docstring in functions
Documentation refinements
PreCI
None
=> Refine auto slim code docstrings and readme.

neural_compressor/adaptor/onnxrt.py, neural_compressor/adaptor/ox_utils/calibration.py, neural_compressor/adaptor/tensorflow.py, neural_compressor/adaptor/tf_utils/util.py, neural_compressor/utils/utility.py, neural_insights/components/diagnosis/diagnosis.py
bug fix
- Update the min/max activation filename: `dequan_min_max.pkl` -> `activation_min_max.pkl`
- Fixed the dequantize function
Pre-CI
None
=> Fixed inspect tensor

neural_compressor/adaptor/ox_utils/smooth_quant.py, test/algorithm/test_smooth_quant.py
bug fix
min/max should be different with alpha tuning
value_info should be added for ORT integration
min/max are different with alpha tuning
value_info is added
pre-ci, extension
no
=> Fix onnxrt smooth quant

neural_coder/extensions/neural_compressor_ext_vscode/package.json, neural_insights/gui/package-lock.json
CVE fix
fix webpack CVE-2023-28154 and 	nth-check CVE-2021-3803
CVE fixed
manually test
version update.
=> Bump version of webpack and nth-check for CVE fix

examples/onnxrt/image_recognition/unet/quantization/ptq_static/requirements.txt, neural_compressor/model/onnx_model.py
bug fix
Enhance model check for LLM
Unet pass test with onnx 1.14.0  onnxrt 1.14.1
pre-ci, extension test
no
=> Enhance model check for LLM

neural_compressor/adaptor/pytorch.py
fix fx bf16 op stat mistake for dynamic models
JIRA: https://jira.devtools.intel.com/browse/ILITV-2934
=> fix fx bf16 op stat issue

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/requirements.txt
add pytest to language-modeling requirements for new transformers version
=> add pytest to requirements

neural_compressor/config.py
bug fix
No API changed 
Fixed typo
=> Fixed typo

neural_compressor/adaptor/ox_utils/calibration.py, neural_compressor/adaptor/ox_utils/smooth_quant.py
=> Fix LLM weight get

neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py, neural_compressor/adaptor/tf_utils/graph_util.py
bug fix
Jira: [ILITV-2956](https://jira.devtools.intel.com/browse/ILITV-2956)
Fix bug
Extension, PreCI
No
=> Fix Crash in inserting Q / DQ around MaxPool for TF Adaptor

examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_static/run_tuning.sh, neural_compressor/model/onnx_model.py
bug fix
Fix unet model
Unet model pass test
local test
no
=> Fix unet model

neural_solution/launcher.py
security fix
Fix security issue according to Checkmarx for Neural Solution
- Command Injection
- Resource Injection due to port checking
- File operation without validation.
no
=> Fix security issue according to Checkmarx for Neural Solution

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, examples/README.md
documentation
API not change
Add onnxrt layoutlmft & layoutlmv3 to example README
CI test
CI test
no
=> Add onnxrt layoutlmft & layoutlmv3 to example README

neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
bug fix
as title
Fix
Extension
No
=> Fix Regression of SSD_resnet50 Caused by Maxpooling on ITEX Mode

examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
[bug fix](https://jira.devtools.intel.com/browse/ILITV-2971)
=> fix example example_inputs type

neural_compressor/adaptor/pytorch.py
bug fix
Fixed the torch block detection 
Pre-CI and [EXT test](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation/271475/)
None
=> Fixed the block detection

neural_insights/test/components/model/tensorflow/test_frozen_pb.py
Code format fixes (pylint)
Ignored false error with missing mocked parameter
Pylint test to pass
Manual pytest execution. It will be also tested in CI.
No
=> Ignore false error with missing mocked parameter

neural_insights/gui/src/components/Warning/Warning.js, neural_insights/web/app/static/js/main.bd15131f.js.LICENSE.txt
bug fix
Neural Insights: fix close button in alerts
button is visible
manually
no
=> Neural Insights: fix close button in alerts

README.md, docs/source/diagnosis.md, docs/source/user_guide.md, neural_insights/README.md, third-party-programs.txt
others
Bump release version into v2.2.  
Some update in documentations.
=> Bump release version into v2.2

neural_compressor/compression/distillation/criterions.py, test/distillation/test_distillation_2.x.py
feature 
Supported add hook for root module in intermediate layers KD.
support add hook for root module in intermediate layers KD
pass UT
=> Supported add hook for root module in intermediate layers KD.

.azure-pipelines/model-test.yml, .azure-pipelines/scripts/models/env_setup.sh, .azure-pipelines/scripts/models/run_model_trigger_common.sh, .azure-pipelines/scripts/models/run_onnxrt_models_trigger.sh, .azure-pipelines/scripts/models/run_pytorch_models_trigger.sh, .azure-pipelines/scripts/models/run_tuning_common.sh, examples/.config/model_params_pytorch.json, examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/main.py, examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/main.py, examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/main.py
validation 
transfer some CI models into new API
CI pass
CI
No
=> transfer some CI models into 2.x API

docs/source/validated_model_list.md
documentation
API changed or not: not
Updated multimode distillation results
no
=> Update multimode distillation results

neural_insights/gui/package-lock.json
fix CVE 
fix CVE of neural insights by update nth-check version
CI pass
NA
version update.
=> update nth-check version to fix CVE

neural_compressor/compression/pruner/patterns.py
bug fix
Heng reported the bug to me. And it can be reproduced. Here is the fix.
Fix bug
Extension
No
=> Fix Regression of TF ViT Pruning

neural_compressor/model/onnx_model.py
bug fix
GPTJ failed since large_model judgement error
GPTJ pass
local test
no
=> Fix large_model judgement

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/model_wrapper.py, neural_compressor/adaptor/torch_utils/weight_only.py, neural_compressor/model/torch_model.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py, test/quantization/test_weight_only_quantization.py
feature
add WeightOnlyLinear for weight-only approach to allow low memory inference.
UT pass
local test
N/A
=> add WeightOnlyLinear for low memory inference.

neural_compressor/adaptor/tensorflow.py
Bug fix
Please convert the dump result from bf16 format to fp32, if needed.
Pre-CI on SPR
None
=> Fixed the TF inspect tensor

README.md, docs/source/get_started.md, examples/helloworld/tf_example7/README.md, examples/helloworld/tf_example7/test.py
Bug fix
Fix Quickstart Example on Readme of homepage
Because there is no extension test for a readme example, please test it locally
PreCI, Local test
No
=> Fix Quickstart Example on Readme

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/weight_only.py, neural_compressor/config.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
feature
support full range for 4 bit sym -8, use -scale to make sure fake sym quantization can be recovered.
UT pass
local test UT
N/A
=> support full range for 4 bit sym -8

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, docs/source/quantization_weight_only.md, neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/model_wrapper.py, neural_compressor/adaptor/torch_utils/util.py, neural_compressor/adaptor/torch_utils/weight_only.py, neural_compressor/model/torch_model.py, neural_compressor/utils/pytorch.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py, test/model/test_model_pytorch.py
Enhance WeightOnlyLinear capability
support compress_dim, compress_bits and to_half
UT pass
local test
N/A
=> Enhance WeightOnlyLinear capability

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/model_wrapper.py, neural_compressor/adaptor/torch_utils/teq.py, neural_compressor/adaptor/torch_utils/weight_only.py, neural_compressor/config.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py, test/quantization/test_weight_only_quantization.py
Add feature that support Trainable Equivalent Transformation (TEQ)
currently not support layer-wise setting.
Trainable Equivalent Transformation (TEQ)
=> support TEQ quantization method

neural_coder/extensions/neural_compressor_ext_lab/neural_compressor_ext_lab/labextension/package.json, neural_coder/extensions/neural_compressor_ext_lab/package.json
upgrade semver version in neural coder
no
upgrade semver versio
no cve warning
check cve warning
no
=> upgrade semver version

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/gptq.py, neural_compressor/adaptor/torch_utils/model_wrapper.py, neural_compressor/adaptor/torch_utils/weight_only.py, neural_compressor/model/torch_model.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
feature 
support perm in WeightOnlyLinear to support gptq
UT pass
local test
N/A
=> support perm in WeightOnlyLinear

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/weight_only.py, neural_compressor/model/torch_model.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
bug fix
support gptq model compression with saved scale
UT pass, model outputs are allclose.
=> support gptq model compression with saved scale

examples/pytorch/nlp/huggingface_models/text-classification/pruning/hpo/run_glue_no_trainer.py
bug fix
fix hpo example bug
None
None
=> fix hpo exmple

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/pytorch_cpu.yaml, neural_compressor/adaptor/torch_utils/model_wrapper.py, neural_compressor/adaptor/torch_utils/teq.py, neural_compressor/adaptor/torch_utils/weight_only.py, test/quantization/test_weight_only_quantization.py
TEQ  related APIs have some changes
support TEQ layerwise setting config
=> support TEQ layerwise config.

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_clm.py, examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/run_qa.py, examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py, examples/pytorch/nlp/huggingface_models/summarization/quantization/ptq_dynamic/fx/run_summarization.py, examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_glue.py, examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_glue.py, examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py, examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue.py, examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_translation.py
fix for transformers 4.31.0 accelerate dataloader
extension test
local test passed
=> fix example dataloader for transformers 4.31.x

neural_compressor/adaptor/torch_utils/smooth_quant.py
bug fix
smoothquant got failed when fetching example_inputs, need break after 1 iteration from dataloader.
test pass.
local test
=> fix PT gpt-j-6B_sq/bloom-560m_sq failed with SQ

examples/tensorflow/image_recognition/resnet_v2/quantization/qat/README.md, examples/tensorflow/image_recognition/resnet_v2/quantization/qat/requirements.txt, examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/efficientnet-b0/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/inception_resnet_v2/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/inception_v1/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/inception_v2/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/inception_v4/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v1/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v3/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/resnet101/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/mixed_precision/README.md, examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_101/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_152/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_50/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/vgg16/quantization/ptq/README.md, examples/tensorflow/image_recognition/tensorflow_models/vgg19/quantization/ptq/README.md
Docs refine
Remove the incorrect 'cd' commands in installing dependencies.
PRECI
No
=> Refine Docs for TF Image Recognition Models

neural_compressor/adaptor/pytorch.py
bug fix
folding=None is not applied auto setting, which caused opt-6.7b-sq is not applied with smoothquant.
model accuracy pass
local test
=> fix folding=None issue

conda_meta/neural_insights/meta.yaml, conda_meta/neural_solution/meta.yaml
fix conda dependencies
`neural_compressor` -> `neural-compressor`
No
conda install neural-solution
no
=> fix conda dependencies

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/smooth_quant.py
bug fix
fix sq bug when eval_func=None
=> fix sq bug when model inplace=True or alpha=auto

.azure-pipelines/scripts/models/env_setup.sh
use protobuf==4.23.4
use protobuf==4.23.4
pre-ci test succeed.
pre-ci model test
no
=> fix pre-ci protobuf version

examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py, examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/scripts/run_bloom_pruning.sh, examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/scripts/run_gptj_pruning.sh, examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/scripts/run_llama_pruning.sh, examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/scripts/run_llm_sparsegpt.sh, examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/scripts/run_opt_pruning.sh, neural_compressor/compression/pruner/patterns/ninm.py, neural_compressor/compression/pruner/patterns/nxm.py, neural_compressor/compression/pruner/pruners/sparse_gpt.py, neural_compressor/compression/pruner/pruning.py, neural_compressor/compression/pruner/utils.py
bug fix
fix JIRA:
https://jira.devtools.intel.com/browse/ILITV-3100
https://jira.devtools.intel.com/browse/ILITV-3101
=> fix llm scripts and pruning import issue

neural_compressor/adaptor/torch_utils/smooth_quant.py
bug fix
No API changed
Fixed typo in forward function in smoothquant
=> Fixed typo in forward function in smoothquant

neural_compressor/adaptor/torch_utils/smooth_quant.py, test/algorithm/test_smooth_quant.py
feature update
introduced a new method to perform alpha auto-tuning in smooth_quant
ut and llm validation
no
=> create a new branch for auto-tuning pr

docs/build_docs/build.sh
document
fix the missed web pages of neural_insights, neural_solution
=> fix miss pages of neural_insights, neural_solution

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
=> GPTQ evaluation on CPU

docs/source/quantization_weight_only.md, neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/weight_only.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
feature
add mse_range for RTN algorithm of weight only quantization
pass UT
local test passed
=> add mse_range for weight_only RTN algo

neural_compressor/adaptor/pytorch.py, test/adaptor/pytorch_adaptor/test_adaptor_pytorch_1.x.py
Support "inspect tensor" feature for FX model 
No API changed
Inspect tensor value correctly
=> PT FX inspect tensor

neural_compressor/adaptor/onnxrt.py, test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py, test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
bug fix and enhancement
API not change
Enhance ONNXRT backend check.
Fix UT failure with onnxrt MixedPrecision test.
Check if ONNXRT backend EP is available. Warn if not available.
Test MixedPrecision when EP is available.
CI test
No
=> Enhance ONNXRT backend check

neural_compressor/strategy/strategy.py, test/algorithm/test_smooth_quant.py
validation
add accuracy test for smoothquant to avoid accuracy issue in pre-ci
ut pass
=> add accuracy test for smoothquant

examples/helloworld/tf_example1/requirements.txt, examples/helloworld/tf_example3/requirements.txt, examples/helloworld/tf_example5/requirements.txt, examples/helloworld/tf_example6/requirements.txt, examples/helloworld/tf_example7/requirements.txt
bug fix
protobuf 4.24.0 segmentation fault with TF 2.13.0
Install 4.24.1 or <=4.23.4.
run helloworld 1
protobuf exclude 4.24.0
=> fix protobuf version

examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/run_qa_no_trainer_pruneOFA.py, examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/prune_once_for_all/fx/run_glue_no_trainer_pruneOFA.py
bug fix
bug fix jira ILITV-3109
None 
None
=> pattern lock pruning example bug fix

neural_compressor/adaptor/ox_utils/weight_only.py
bug fix
issue: variables are not defined
Fix awq issue
CI test
no
=> Fix awq issue

neural_compressor/adaptor/torch_utils/layer_wise_quant/utils.py
bug fix
fix layer-wise quant ut fail when accelerate==0.22
None
None
=> fix layer-wise quant ut fail

examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt, examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt, examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt, examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt, examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
security issue fix
update requirements version for tf2onnx
example pass
tf2onnx example
No
=> update requirements version for tf2onnx

neural_compressor/adaptor/pytorch.py, neural_compressor/experimental/component.py
bug fix
No API changed
Fixed no qat_optype_wise attribute in two shot training.
Run two shot optimization successfully 
Local test
=> Fixed two shot training issue which no qat_optype_wise attribute

docs/source/quantization_weight_only.md, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/README.md, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_gptj_mlperf_int4.py, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_gptj_mlperf_int4.sh
documentation, examples
- Adding more detailed user-defined arguments in gptq mlperf scripts.
- Update details in documentations about per-channel quantization, *group_size=-1*, etc.
None
Spell check, etc.
None>
=> Refine documents of GPTQ MLPerf examples

examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/main.py
bug fix
Disable BF16 to fix inception_v3 accuracy regression issue.
Extension test
No
=> Fix inception_v3 Accuracy Regression Issue

examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py, neural_compressor/adaptor/onnxrt.py, neural_compressor/adaptor/ox_utils/operators/concat.py, neural_compressor/model/onnx_model.py, test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
bug fix and enhancement
API not change
1. Fix layoutlmv3 quantization bug by enhancing check for Concat op.
2. Enhance `find_ffn_matmul` function in ONNXRT adaptor and enhance albert quantization config.
3. Optimized the saving name of external data in the ONNXModel save function for large models.
UT test and extension test
no
=> Enhance ONNXRT adaptor and fix bugs

neural_compressor/adaptor/torch_utils/smooth_quant.py, test/algorithm/test_smooth_quant.py
bug fix
fix the issue of tuple-type input
UT
=> sq move_input_to_device tuple issue

examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
bug fix
failed since ITREX structure change
=> Fix example dependency

docs/source/quantization_weight_only.md, examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py, neural_compressor/adaptor/onnxrt.py, neural_compressor/adaptor/ox_utils/weight_only.py, neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/awq.py, neural_compressor/adaptor/torch_utils/weight_only.py, neural_compressor/model/torch_model.py, test/adaptor/onnxrt_adaptor/test_weight_only_adaptor.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
rename configs for woq:
sym_full_range --> enable_full_range
mse_range --> enable_mse_search
auto_scale --> enable_auto_scale
ut pass
=> rename configs for woq

neural_compressor/compression/pruner/criteria.py, neural_compressor/compression/pruner/patterns/base.py, neural_compressor/compression/pruner/patterns/ninm.py, neural_compressor/compression/pruner/patterns/nxm.py, neural_compressor/compression/pruner/pruners/progressive.py
bug fix
fix pruning bugs:
* pruning ut sparsity issue with pt, ninm pattern sparsity did not match the target sparsity
* tensorflow pruning example failed
None
None
=> fix pruning

README.md, docs/build_docs/build.sh, docs/build_docs/source/_templates/footer.html, docs/build_docs/source/_templates/layout.html, docs/build_docs/source/conf.py
documentation
IT ask to online doc support adobe analytics to help get summary of access.
1. update to support adobe analytics
2. support to convert md link to html link for all cases.
=> support abode analytics

neural_compressor/adaptor/pytorch_cpu.yaml, neural_compressor/adaptor/torch_utils/smooth_quant.py, test/algorithm/test_smooth_quant.py
bug fix
fix bug when trace failed
https://jira.devtools.intel.com/browse/ILITV-3152
UT pass
=> fix bug when trace failed

examples/README.md, examples/notebook/tensorflow/resnet/README.md, examples/notebook/tensorflow/resnet/resnet_benchmark.py, examples/notebook/tensorflow/resnet/resnet_quantization.ipynb
TF notebook example
TF notebook example
Users can have a quickstart notebook example of quantization by Intel Neural Compressor in Tensorflow
Run the jupyter notebook
None
=> add tf resnet quantization notebook

examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/README.md, examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py, examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_sparsegpt.py
=> refine readme

.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt, docs/source/quantization_weight_only.md, docs/source/validated_model_list.md
documentation
add validated WOQ results
=> add validated WOQ results

neural_compressor/compression/pruner/patterns/base.py, neural_compressor/compression/pruner/patterns/ninm.py, neural_compressor/compression/pruner/patterns/nxm.py
bug fix
fix pruning kthvalue error
None
None
=> fix pruning kthvalue error

neural_compressor/adaptor/pytorch.py
bug fix
No API changed
Fixed inspect tensor issue for non output of torch functional op
inspect tensor successfully for mobilenet_v2
Local tested
=> Fixed inspect tensor issue for non output of torch functional op

.azure-pipelines/scripts/ut/run_basic_api.sh, neural_compressor/adaptor/pytorch.py
validation 
add missed test cases 
CI pass
CI
No
=> fix CI issue

examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_static/fx/run_asr.py, neural_compressor/adaptor/torch_utils/smooth_quant.py, test/algorithm/test_smooth_quant.py
bug fix
[[v2.3 release rc1][PT smooth quant][regression] ssd-resnet34 SQ failed with AssertionError](https://jira.devtools.intel.com/browse/ILITV-3153)
=> fix device issue of sq

neural_solution/examples/custom_models_optimized/tf_example1/task_request.json, neural_solution/examples/custom_models_optimized/tf_example1/task_request_distributed.json, neural_solution/examples/custom_models_optimized/tf_example1/test.py, neural_solution/examples/hf_models_grpc/README.md, neural_solution/frontend/gRPC/client.py, neural_solution/frontend/gRPC/server.py
bug fix and documentation
- Update Neural Solution example
-  Fix grpc port issue
NS Pre-CI
None
=> Update Neural Solution example & fix grpc port issue

docs/source/quantization_weight_only.md
=> refine document

test/distillation/test_distillation_2.x.py
distillation UT
remove temp files
Pre-CI
None
=> Enhance distillation UnitTest

neural_compressor/adaptor/torch_utils/weight_only.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py, test/algorithm/test_smooth_quant.py
bug fix
wrong scale got for nf4&fp4
UT pass
=> fix bug in nf4/fp4

neural_compressor/utils/neural_insights_utils.py, setup.py
bug fix
Bug fix for registering TF models in Neural Insights
TF models can be added to Neural insights.
Execution of TF model's quantization with diagnosis.
None
=> Fix get_model_path output for TF models

test/ipex/test_adaptor_ipex.py
add some checks for ipex quantization ut.
=> Add check for ipex quantization ut

test/adaptor/pytorch_adaptor/test_adaptor_pytorch_1.x.py, test/adaptor/pytorch_adaptor/test_adaptor_pytorch_2.x.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py, test/quantization/test_weight_only_quantization.py
ut enhancement
Add/review test results checkers for each test function.
Rewrite the invalid/out-of-date test.
UT pass
=> enhance ut quality

docs/source/quantization_weight_only.md
documentation
add intro of 4 method
=> add intro of 4 woq methods

examples/tensorflow/graph_networks/graphsage/quantization/ptq/main.py
Bug fix
GraphSage model will give BF16 output when running on TF new API.
This PR is to fix error caused by it.
GraphSage model will be able to run on TF new API.
No
=> Fix BF16 Output for TF GraphSage Example

test/objective/test_objective.py
ut improvement for objective
add assertion
ut pass
locat test passed
=> ut improve for objective

test/itex/test_keras_in_keras_out.py, test/itex/test_tensorflow_qdq_convert_to_onnx_qdq.py, test/tfnewapi/test_tf_spr_base_distributed_tf_dataloader.py
UT enhancement
Enhance UT for ITEX and TF New API
Enhance UT
PreCI
No
=> Enhance UT for ITEX and TF New API

.azure-pipelines/scripts/ut/env_setup.sh
validation 
downgrade onnxruntime-extensions version to avoid core dump issue
CI pass
CI
No
=> downgrade onnxruntime-extensions version

README.md
documentation
add FP8 quantization link in README.md
=> add FP8 quantization link in README.md

neural_compressor/adaptor/torch_utils/smooth_quant.py, neural_compressor/adaptor/torch_utils/util.py
bug fix
[Bug in smooth_quant.py #1265](https://github.com/intel/neural-compressor/issues/1265)
UT pass
=> fix bug in get/set_module(reported by user)

neural_compressor/adaptor/pytorch.py
bug fix
change capability check logic to fetch custom Linear
=> support falcon woq quantization

.azure-pipelines/scripts/ut/run_basic_api.sh, .azure-pipelines/scripts/ut/run_basic_others.sh
validation 
close NAS test in CI temporary due to invalid link
=> close NAS test in CI temporary due to invalid link

neural_compressor/adaptor/torch_utils/smooth_quant.py, test/algorithm/test_smooth_quant.py
bug fix
Enhance the calibration part by code upgrading and removing save_input_output_values. It will save memory access for smoothquant.
=> [regression fix] sq enhance calibration part 

test/hpo/test_hpo.py
validation 
Close the unstable UT test in CI, will add back after fix the issue.
=> Close the unstable UT test in CI

conda_meta/basic/meta.yaml, conda_meta/neural_insights/meta.yaml, conda_meta/neural_solution/meta.yaml, neural_compressor/version.py
=> bump master version into v2.4

neural_compressor/adaptor/torch_utils/smooth_quant.py
=> fix sq auto bug

docs/source/validated_model_list.md
documentation 
minor fix for table title
=> minor fix for table title 

examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/utils/download_librispeech.py
Fixed typo.
destnation -> destination
=> Fix typo in download_librispeech.py

docs/source/quantization.md, neural_compressor/adaptor/onnxrt.py, neural_compressor/config.py, test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
enhance
Add npu into config
no
=> Enhance config for DML EP

docs/source/smooth_quant.md
documentation
update 'validated models' of smoothquant readme file
=> update sq doc

test/hpo/test_hpo.py
bug fix
fix hpo ut bo fail when param already register
None
None
=> fix hpo ut fail

examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/run_quant.sh, examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/run_quant.sh, examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/run_quant.sh
bug fix
fix tensorflow example scripts typo
model test pass
local test related examples
No
=> fix tensorflow example scripts typo

docs/source/smooth_quant.md
documentation,
following up pr1301. the data relevant to llama2-7b-chat is yet to be updated.
=> sq readme update

neural_insights/gui/package-lock.json
update packages to fix security issue
=> Neural Insights: update packages

docs/source/validated_model_list.md
documentation 
Update v2.3 release data
Perf PDT review pass
Measured on SPR node
No
=> Update v2.3 release data

docs/source/smooth_quant.md
documentation
update the description of smoothquant auto-tuning method.
=> doc update

docs/source/quantization_weight_only.md, docs/source/tuning_strategies.md
documentation 
To follow up on the https://github.com/intel/neural-compressor/pull/1328
update woq tuning document
Pre-CI
None
=> Update woq tuning document

.azure-pipelines/scripts/models/env_setup.sh
validation 
freeze ruamel.yaml==0.17.40 version for CI test
CI pass 
CI
No
=> freeze ruamel_yaml version for CI test

examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/main.py
=> Fix ONNXRT tokenizer of language modeling example

examples/.config/model_params_onnxrt.json, examples/README.md, examples/onnxrt/image_recognition/beit/quantization/ptq_static/README.md, examples/onnxrt/image_recognition/beit/quantization/ptq_static/beit_modeling_finetune.py, examples/onnxrt/image_recognition/beit/quantization/ptq_static/main.py, examples/onnxrt/image_recognition/beit/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/beit/quantization/ptq_static/requirements.txt, examples/onnxrt/image_recognition/beit/quantization/ptq_static/run_benchmark.sh, examples/onnxrt/image_recognition/beit/quantization/ptq_static/run_quant.sh
example
API not change
ONNXRT quantization example of [BERT Pre-Training of Image Transformers](https://arxiv.org/abs/2106.08254)(BEiT) model
It was first released in https://github.com/microsoft/unilm/tree/master/beit.
CI, extension test
No
=> Add BEiT ONNXRT example

neural_compressor/experimental/distillation.py
bug fix
modify import path for Criterions, fix the distill bug cause of remove api 1.0.
None
None
=> fix distill api 1.0 bug

docs/source/smooth_quant.md
documentation
refine model result table of sq readme: add llama2-13b-hf result
no  library dependency introduced or removed
=> [Documentation] refine model result table of sq readme

docs/source/quantization_weight_only.md
=> add link to ITREX for weight-only performance

.azure-pipelines/scripts/ut/run_basic_adaptor.sh, .azure-pipelines/scripts/ut/run_basic_adaptor_tfnewapi.sh, .azure-pipelines/scripts/ut/run_basic_api.sh, .azure-pipelines/scripts/ut/run_basic_itex.sh, .azure-pipelines/scripts/ut/run_basic_others.sh, .azure-pipelines/scripts/ut/run_basic_pt_pruning.sh, .azure-pipelines/scripts/ut/run_basic_tf_pruning.sh, .azure-pipelines/scripts/ut/run_basic_v2.1_ipex.sh, .azure-pipelines/scripts/ut/run_ncoder.sh, .azure-pipelines/scripts/ut/run_neural_insights.sh, .azure-pipelines/scripts/ut/run_neural_solution.sh, examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/requirements.txt, test/pruning_with_tf/pruning_1.x_v1/test_tensorflow_distributed_pruning.py, test/pruning_with_tf/pruning_1.x_v1/test_tensorflow_pruning.py, test/pruning_with_tf/pruning_1.x_v2/test_tensorflow_pruning.py, test/tfnewapi/test_tf_spr_base_distributed_pruning.py
bug fix
1. Temporary fix for pytorch bert large dataset load.  
https://github.com/huggingface/datasets/issues/6330  
2.  Enhance UT dataset path check.  
3.  Add some logs into UT test, make it easier to identify issues.
=> Fix for pytorch bert large dataset load

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/signround/signround.py
=> save some resource in signround

examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/requirements.txt
update requirements
add version limit for import error
extension test passed
=> Update requirements for 3dunt example

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/util.py
bug fix
add is not selected by config when smoothquant is enabled.
UT pass
local check
=> support kl for add

neural_compressor/adaptor/torch_utils/util.py
bug fix
This previous support was enabled by changing IPEX source code. The add support will be added back when ipex2.1.1 is release.
=> revert previous add support for sq ipex

docs/source/quantization.md, examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/README.md, examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/main.py, examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/run_benchmark.sh, examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/run_quant.sh, neural_compressor/adaptor/onnxrt.py
enhance
Support dml quantization and add example
local windows platform
=> Support dml quantization and add example

neural_solution/frontend/gRPC/server.py
bug fix
Fix Neural Solution grpc parameter name: "task_monitor_portq" -> "task_monitor_port"
NS UT
none
=> Fix Neural Solution parameter name

neural_solution/backend/scheduler.py, neural_solution/backend/utils/utility.py, neural_solution/examples/hf_models/task_request.json, neural_solution/examples/hf_models_grpc/README.md, neural_solution/examples/hf_models_grpc/task_request.json, neural_solution/frontend/gRPC/client.py, neural_solution/frontend/gRPC/server.py, neural_solution/test/backend/utils/test_utility.py
bug fix
fix Neural solution some issues
- custom quantized model  download
- huggingface model example requirements
- grpc port and readme
ns-ut
None
=> Update Neural Solution based on v2.4 release test

.azure-pipelines/scripts/ut/run_itrex.sh
validation
update itrex CI test scope
=> update itrex CI test scope

.azure-pipelines/scripts/ut/run_itrex.sh
validation 
adapt to ITREX UT test
CI pass
CI
No
=> adapt to ITREX UT test

docs/source/quantization.md
documentation
Enhance doc for DmlExecutionProvider
=> Enhance doc for DmlExecutionProvider

neural_compressor/utils/pytorch.py
bug fix
API changed not
fix model(example_inputs) positions
Pre-CI
None
=> Fix ipex model inference on restoration from json

neural_compressor/adaptor/ox_utils/util.py, test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
enhance 
to_numpy function will crash if torch is not installed
=> enhance onnx data format check

test/adaptor/pytorch_adaptor/test_adaptor_pytorch_2.x.py
bug fix 
Fix block detector UT
Pre-CI
None
=> Fix block detector UT

neural_compressor/adaptor/ox_utils/smooth_quant.py, test/algorithm/test_smooth_quant_onnx.py
bug fix
https://github.com/intel/neural-compressor/issues/1427
=> Add clip for onnxrt smoothquant

examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/main.py, examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/main.py
bug fix 
Fix fster rcnn tf examples. The bugs are caused by change of detected names of input/output.
Fix bug
No
=> Fix Faster RCNN TF Examples

examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
bug fix
This issue is caused by version conflict of dependency.
Fix TF2ONNX Example SSD MobileNet V1
Extension test
No
=> Fix TF2ONNX Example SSD MobileNet V1

neural_compressor/adaptor/pytorch.py
bug fix
fix bug when ipex version is not the same as torch
UT pass
local tested
=> check ipex version instead of torch version

examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/README.md, examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/README.md
documentation
API not change
Remind user to install `tesseract-ocr` to prevent the error message ` tesseract is not installed or it's not in your PATH.` when preparing model.
CI
no
=> Update ONNXRT layoutlmv2 example README

neural_insights/gui/src/components/Diagnosis/Diagnosis.scss, neural_insights/gui/src/components/OpDetails/OpDetails.scss, neural_insights/gui/src/components/OpList/OpList.js
bug fix
* fix displaying PyTorch models
* fix displaying long OP name
\-
manually
\-
=> Neural Insights - minor fixes

test/algorithm/test_smooth_quant.py
bug fix
peft upgration changes module type.
pre-ci pass
=> fix peft error in ut

examples/notebook/pytorch/Quick_Started_Notebook_of_INC_for_Pytorch.ipynb, examples/notebook/pytorch/benchmark.py
=> fix pt notebook benchmark

neural_compressor/adaptor/onnxrt.py
bug fix
API not change
Enhance ONNXRT log info
CI
no
=> Enhance ONNXRT log info

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
examples
format fix for llm example scripts
=> format fix for llm example scripts

docs/source/smooth_quant.md, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/ipex/README.md, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/ipex/requirements.txt, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/ipex/run_llama2_sq.py
examples
llama2-7b and llama2-13b SmoothQuant with Intel® Neural Compressor and Intel® Extension for PyTorch.
Run llama2-7b and llama2-13b with INC SmoothQuant recipes and get the int8 model with expected accuracy.  
Local test
No
=> add llama2 examples for smoothquant

neural_compressor/adaptor/torch_utils/smooth_quant.py
bug fix
This will avoid alpha-space generation failure when alpha step_size is small(eg, 0.001).
=> [Bug] fix alpha-space generation

examples/tensorflow/nlp/large_language_models/quantization/ptq/gpt-j/main.py, neural_compressor/adaptor/tf_utils/smooth_quant_calibration.py, test/model/test_model.py
bug fix
The previous API is removed. Update importing.
Fix UT
PreCI
No
=> Fix UT autotrackable import issue for TF2.14

neural_compressor/adaptor/ox_utils/calibration.py, neural_compressor/adaptor/ox_utils/smooth_quant.py, neural_compressor/adaptor/ox_utils/util.py, neural_compressor/adaptor/ox_utils/weight_only.py
enhancement
Add progress bar for woq and sq
=> Add progress bar for woq and sq

neural_compressor/utils/pytorch.py, test/model/test_model_pytorch.py
bug fix
[Torch/IPEX 2.1.0][CI] UT issue](https://jira.devtools.intel.com/browse/ILITV-3309)
UT pass when torch=2.1
=> [bug fix] Torch/IPEX 2.1.0][CI] UT issue

docs/source/smooth_quant.md
=> [Doc] blockwise autotuning doc update

neural_solution/examples/hf_models_grpc/README.md
documentation 
Update Neural Solution grpc example README.
None
=> Update NS grpc example README

neural_compressor/adaptor/torch_utils/model_wrapper.py, neural_compressor/torch/quantization/layers.py
bug fix
No API changed
Unify the attribute name in WeightOnlyLinear class
=> Unify the attribute name in WeightOnlyLinear class

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/README.md, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/eval.py, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/requirements.txt, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/signround/README.md, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/signround/requirements.txt
=> refine docs, update requirements

examples/onnxrt/body_analysis/onnx_model_zoo/arcface/quantization/ptq_static/prepare_model.py, examples/onnxrt/body_analysis/onnx_model_zoo/emotion_ferplus/quantization/ptq_static/prepare_model.py, examples/onnxrt/body_analysis/onnx_model_zoo/ultraface/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/alexnet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/caffenet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/densenet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/efficientnet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/fcn/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/googlenet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/inception/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/mnist/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/mobilenet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/resnet50/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/squeezenet/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/vgg16/quantization/ptq_static/prepare_model.py, examples/onnxrt/image_recognition/onnx_model_zoo/zfnet/quantization/ptq_static/prepare_model.py, examples/onnxrt/nlp/onnx_model_zoo/BiDAF/quantization/ptq_dynamic/prepare_model.py, examples/onnxrt/nlp/onnx_model_zoo/bert-squad/quantization/ptq_dynamic/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/DUC/quantization/ptq_static/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/faster_rcnn/quantization/ptq_static/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/mask_rcnn/quantization/ptq_static/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/ssd/quantization/ptq_static/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/ssd_mobilenet_v1/quantization/ptq_static/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/tiny_yolov3/quantization/ptq_static/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/yolov3/quantization/ptq_static/prepare_model.py, examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq_static/prepare_model.py
bug fix 
Update model link of ONNX model zoo
extension test
no
=> Update model link of ONNX model zoo

conda_meta/basic/meta.yaml, conda_meta/neural_insights/meta.yaml, conda_meta/neural_solution/meta.yaml, docs/source/llm_recipes.md, neural_compressor/version.py
others  
bump master version into v2.5
=> bump master version into v2.5

neural_compressor/common/base_config.py, test/3x/torch/test_config.py
feature
Add regular expression matching in "to_config_mapping" for base config
Pre-CI
None
=> Add regular expression matching for base config

docs/source/llm_recipes.md
update LLM recipes documentation
update Llama-2-13b-hf status
no
no
no
=> update Llama-2-13b-hf status

docs/source/quantization.md, examples/README.md
=> update doc for xpu

examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/run_qa_no_trainer.py
API changed or not: Fixed https://github.com/intel/neural-compressor/issues/1520
None
=> Set model to `training` mode before accelerate prepare

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
others
fix trust remote for llm case
=> fix trust remote

neural_compressor/adaptor/torch_utils/awq.py, neural_compressor/adaptor/torch_utils/teq.py, neural_compressor/adaptor/torch_utils/weight_only.py
features  
No API changed
Quantize weight with in-place mode in weight-only quantization
Weight-only quantization successfully. 
Local tested
=> Quantize weight with in-place mode in weight-only quantization

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/README.md
Fixed https://github.com/intel/neural-compressor/issues/1522
Local-test
None
=> Update the eval script

examples/notebook/tensorflow/vgg19_ibean/inc_quantize_vgg19.ipynb
bug fix
https://jira.devtools.intel.com/browse/ILITV-3306
test locally
=> fix model url, adapt to inc api

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
examples
change the example's code logic
=> Modify gptq example logic

.azure-pipelines/scripts/codeScan/pylint/pylint.sh, docs/source/releases_info.md, neural_compressor/adaptor/keras.py, neural_compressor/tensorflow/algorithms/static_quantize/keras.py
bug fix
This is a known issue of keras > 2.14.
The Keras official team gives a workaround: https://github.com/keras-team/tf-keras/issues/44
We use this to fix the bugs in some Keras example models.
Fix the bugs in some Keras example models.
Extension test
No
=> Fix Keras Deserialization Issue of Lambda Layers

neural_compressor/adaptor/torch_utils/weight_only.py
bug fix
Fix bug when using inplace mode. 
Without cat, weight is not updated.
UT pass
=> fix bug when using inplace mode

neural_compressor/adaptor/torch_utils/teq.py
add inputs dtype "torch.Tensor" option for teq train dataloader.
=> Update TEQ train dataloader

docs/source/quantization_weight_only.md
documentation
fix table format issue
local test
=> fix table format

.azure-pipelines/model-test.yml, .azure-pipelines/scripts/ut/env_setup.sh, .azure-pipelines/scripts/ut/run_itrex.sh
validation 
Freeze CI transformers<=4.36.2 to avoid adaption issue temporary.
=> freeze CI transformers==4.36.2

.azure-pipelines/scripts/ut/3x/collect_log_3x.sh, .azure-pipelines/scripts/ut/collect_log.sh, .azure-pipelines/ut-3x-pt.yml, .azure-pipelines/ut-basic-no-cover.yml, .azure-pipelines/ut-basic.yml
validation 
remove binary build cache to fix the coverage collect issue in CI.
=> remove build cache

neural_compressor/common/base_config.py, neural_compressor/onnxrt/quantization/config.py, neural_compressor/tensorflow/quantization/config.py, neural_compressor/torch/quantization/config.py, test/3x/onnxrt/test_config.py
enhancement
refine config for auto-detecting backend and device
UT pass
=> refine config for auto-detecting backend and device

neural_compressor/common/utils/constants.py
Enhancement
Add all supported algo names in advance to avoid triggering all tests.
Pre-CI
None
=> Add more algo names in advance

neural_compressor/common/base_config.py, neural_compressor/onnxrt/quantization/config.py, neural_compressor/torch/algorithms/weight_only/rtn.py
Refine base config for 3.x
params_list can be used to specify which params can be tunning
=> Refine base config for 3.x

.azure-pipelines/scripts/codeScan/pylint/pylint.sh
validation 
add deps for pylint scan
CI pass
NA
NA
=> add deps for pylint scan

neural_compressor/config.py, neural_compressor/mix_precision.py, neural_compressor/quantization.py, neural_compressor/strategy/auto.py, neural_compressor/strategy/strategy.py, neural_compressor/strategy/utils/tuning_space.py, neural_compressor/training.py
Fix https://github.com/intel/neural-compressor/issues/1617
=> Fixed the best qmodel recovery issue

.azure-pipelines/scripts/ut/3x/run_3x_tf.sh
bug fix
include common UT case in TF 3x CI test
CI pass
NA
NA
=> include common UT case in TF 3x CI test

test/algorithm/test_smooth_quant.py
bug fix
The tests function should be instance methods rather than class methods
Pre-CI
None
=> Fixed smooth quant's UTs

neural_compressor/torch/quantization/__init__.py, neural_compressor/torch/quantization/autotune.py, neural_compressor/torch/quantization/config.py, test/3x/torch/quantization/habana_fp8/test_fp8.py
bug fix
add fp8 autotune ut and fix bug in autotune (autotune returns the fp32 model)
UT pass
=> add fp8 autotune ut and fix bug in autotune

.azure-pipelines/scripts/ut/run_itrex.sh, neural_compressor/adaptor/pytorch.py
bug fix
fix a minor issue for itrex-ut.
=> sq bug-fix for itrex-ut

neural_compressor/model/torch_model.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor_pytorch.py
=> Support export compressed model for AutoRound [2.x]

examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/main.py
bug fix
The TF ViT example can't meet accuracy goal after PR 1632.
This PR is to fall back a MatMul Op so that ViT will meet the accuracy.
No
=> Fix Accuray Regression of TF ViT Example

examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/prepare_model.py, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/requirements.txt, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/prepare_model.py, examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/requirements.txt
bug fix
Fix onnxrt example bug: bart export failure
extension test
no
=> Fix onnxrt example bug: bart export failure

examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
fix fp32 example input issue
for bert_large_ipex/distilbert_base_ipex
local test passed
=> fix qa ipex example fp32 example input issue

neural_compressor/torch/algorithms/smooth_quant/smooth_quant.py, test/3x/torch/quantization/test_smooth_quant.py
add more ut to smooth_quant for 3.x API
minor fix on sq script
ut pass
=> add more ut to smooth_quant for 3.x API

neural_compressor/adaptor/tf_utils/graph_rewriter/int8/fuse_matmul_requantize.py
bug fix
Update conditions of getting min-max during TF MatMul requantize to fix a bug found when quantizing urlnet.
UT
No
=> Update Conditions of Getting min-max during TF MatMul Requantize

neural_compressor/model/tensorflow_model.py
Fix TF issues caused by the way of loading saved_model.
Fixed below TF examples:
Fix examples
Extension test
No
=> Fix TF saved_model issues

.azure-pipelines/model-test.yml, .azure-pipelines/scripts/fwk_version.sh, .azure-pipelines/scripts/models/env_setup.sh, .azure-pipelines/scripts/ut/env_setup.sh, .azure-pipelines/scripts/ut/run_basic_adaptor.sh, .azure-pipelines/scripts/ut/run_basic_api.sh, .azure-pipelines/scripts/ut/run_basic_others.sh, .github/checkgroup.yml
validation 
CI test FW version update
CI pass with new FW versions 
CI
No
=> CI test FW version update

examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/prepare_model.py, examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/requirements.txt, examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/prepare_model.py, examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/requirements.txt
bug fix
Fix code_detection example export issue
=> Fix code_detection example export issue

neural_compressor/torch/utils/environ.py, test/3x/torch/test_auto_accelerator.py
bug fix 
API changed or not: Fixed the auto device detection
tests
```bash
pytest  test_auto_accelerator.py -k test_get_device
```
None
=> Fixed the auto device detection

examples/onnxrt/nlp/huggingface_model/token_classification/layoutlm/quantization/ptq_dynamic/main.py, examples/onnxrt/nlp/huggingface_model/token_classification/layoutlm/quantization/ptq_static/main.py, neural_compressor/adaptor/ox_utils/operators/split.py
bug fix
Fix onnxrt split op failed with bug `list index out of range`
extension test
no
=> Fix onnxrt split op

README.md
Documentation
Add "What's New" section in Readme to highlight some messages.  WOQ support on Gaudi2 is highlighted this time,  rendered [link](https://github.com/intel/neural-compressor/blob/thuang6/readme_gaudi2_support/README.md)
=> Highlight WOQ support on Gaudi2 in Readme 

README.md, docs/source/installation_guide.md, third-party-programs.txt
documentation 
v2.5 release validated FW version update
=> validated FW version update

conda_meta/basic/meta.yaml
=> update conda numpy version

docs/source/llm_recipes.md
=> update LLM recipes

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
bug fix
follow https://github.com/intel/neural-compressor/pull/1707
=> Fix lm_eval import from itrex [3.x]

examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py, examples/pytorch/nlp/huggingface_models/language-modeling/quantization/signround/eval.py
=> Fix lm_eval import from itrex

neural_compressor/torch/algorithms/weight_only/gptq.py, neural_compressor/torch/utils/auto_accelerator.py
feature
Refact gptq to support runing on gaudi
None
local test pass
habana_frameworks
=> Refact gptq to support runing on gaudi

neural_compressor/model/torch_model.py
=> WOQ models export workaround for autoround different device

.azure-pipelines/scripts/ut/run_itrex.sh, conda_meta/basic/meta.yaml, conda_meta/neural_insights/meta.yaml, conda_meta/neural_solution/meta.yaml, neural_compressor/version.py
=> bump version into v2.6

docs/source/validated_model_list.md
=> fix model name

neural_compressor_ort/algorithms/layer_wise/core.py, test/onnxrt/requirements.txt
bug fix
ONC upgrade transformers
CI
no
=> ONC upgrade transformers

test/3x/torch/quantization/test_static_quant.py, test/3x/torch/quantization/weight_only/hqq/test_hqq_cpu.py, test/3x/torch/quantization/weight_only/hqq/test_hqq_cuda.py, test/3x/torch/quantization/weight_only/test_autoround.py, test/3x/torch/quantization/weight_only/test_awq.py, test/3x/torch/quantization/weight_only/test_gptq.py, test/3x/torch/quantization/weight_only/test_rtn.py, test/3x/torch/quantization/weight_only/test_teq.py
Enhance UT
Enhance 3.x torch UT
CI
No
=> Enhance 3.x torch UT

requirements_pt.txt
others  
freeze the pt backend peft version to avoid ut issue
=> freeze the pt backend peft version to avoid ut issue

neural_compressor/torch/utils/environ.py
=> Revert the ipex import change

.azure-pipelines/scripts/ut/env_setup.sh, neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/auto_round.py, neural_compressor/adaptor/torch_utils/weight_only.py, test/adaptor/pytorch_adaptor/test_weight_only_adaptor_pytorch.py
=> Support `auto_round` integration 2.x

neural_compressor/onnxrt/utils/onnx_model.py
bug fix
https://dev.azure.com/lpot-inc/neural-compressor/_build/results?buildId=30172&view=logs&j=3db173ea-5f83-5cb0-6129-41ce50acfd9a&t=a8fc7f89-bea3-558a-5434-6db6a6e4c862&l=17508
=> Fix layer_wise issue caused by onnxruntime1.18

neural_compressor/torch/algorithms/smooth_quant/smooth_quant.py, neural_compressor/torch/algorithms/smooth_quant/utility.py, neural_compressor/torch/algorithms/static_quant/static_quant.py, neural_compressor/torch/quantization/algorithm_entry.py, neural_compressor/torch/quantization/config.py, test/3x/torch/quantization/test_smooth_quant.py, test/3x/torch/quantization/test_static_quant.py
Add 'excluded_precisions'
for static_quant and smooth_quant to use mixed precison
ut passed
=> Add 'excluded_precisions' to static_quant and smooth_quant

examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py, examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt, examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py, examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt, neural_compressor/adaptor/ox_utils/weight_only.py
bug fix 
Update lm-eval evaluate in ort llm example
extention test
no
=> Update lm-eval evaluate in ort llm example

neural_compressor/torch/algorithms/smooth_quant/smooth_quant.py, neural_compressor/torch/algorithms/static_quant/static_quant.py, neural_compressor/torch/quantization/quantize.py, test/3x/torch/quantization/test_smooth_quant.py, test/3x/torch/quantization/test_static_quant.py
bug fix
1. fix sq&static bf16 model=None issue
2. fix sq model.sq
3. add more ut cases
ut passed
=> bug fix for 3.x sq and static quant

docs/3x/PT_DynamcQuant.md
=> Add pt dynamic quant

docs/3x/TF_Quant.md, docs/3x/TF_SQ.md, docs/3x/TensorFlow.md
documentation
1. Modify introduction
2. remove 3x words
PreCI
None
=> Polish Document of INC TF 3x API

test/itex/test_tensorflow_qdq_convert_to_onnx_qdq.py
bug fix
One UT case of tf2onnx should be removed.
PreCI
No
=> Remove Depracated TF2ONNX UT Case

neural_coder/extensions/neural_compressor_ext_lab/.eslintrc.js
bug fix 
no
Modify the security issues of .eslintrc.js
no security issue
no security issue
no
=> Modify the security issues of .eslintrc.js

examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/requirements.txt, examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/requirements.txt
bug fix
fix numpy version for rnnt, 3dunet
extension pass
=> fix numpy versions for 2.x examples

neural_compressor/torch/algorithms/static_quant/utility.py
bug fix
fix acc regression for 3.x ipex sq and static
=> fix act_observer for 3.x ipex sq and static

docs/source/llm_recipes.md
=> Update SQ/WOQ status

.azure-pipelines/docker/Dockerfile.devel
Bug fix
Temp fix nas deps issue, need to revert after nas removed. 
=> temp fix nas deps issue

.azure-pipelines/model-test.yml
validation 
remove pytorch eager mode model test 
=> remove pytorch eager mode model test

examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/main.py, examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/main.py, examples/pytorch/object_detection/ssd_resnet34/quantization/ptq/fx/python/models/utils.py, neural_coder/coders/tensorflow/amp.py, neural_coder/coders/tensorflow/inc.py, neural_compressor/strategy/strategy.py, neural_compressor/torch/algorithms/habana_fp8/fp8_quant.py, test/pruning_with_pt/pruning_2.x/test_auto_excluding_classifier.py, test/pruning_with_pt/pruning_2.x/test_auto_slim.py
=> Remove debug code.

.azure-pipelines/ut-3x-pt-fp8.yml
bug fix
update Gaudi CI baseline artifacts name
=> update Gaudi CI baseline artifacts name

.azure-pipelines/template/docker-template.yml
bug fix
fix CI docker container clean up issue
https://dev.azure.com/lpot-inc/neural-compressor/_build/results?buildId=32541&view=logs&jobId=76edecc6-e396-5caa-ca09-5a528541ba6a&j=a32fed50-dfd5-59a0-4194-521f5260f60d&t=b4413cd6-63e4-5070-046d-187e06d59931 
CI pass
CI
No
=> fix CI docker container clean up issue

requirements_pt.txt, test/3x/torch/requirements.txt
validation 
remove peft version limit
=> remove peft version limit

.github/workflows/Scanner_Bdba.yml, .github/workflows/Scanner_Coverity.yml, .github/workflows/Scanner_McAfee.yml, .github/workflows/probot.yml, .github/workflows/publish.yml
Add top level permission: read-all
=> Add read permission token per security requirement

neural_compressor/torch/quantization/config.py
=> Set `low_gpu_mem_usage=False` for AutoRound

docs/build_docs/source/conf.py, docs/build_docs/sphinx-requirements.txt, docs/build_docs/update_html.py
=> fix online doc search issue

neural_compressor/version.py
bump main version into v3.1
bump main version into v3.1
=> bump main version into v3.1

setup.py
binary build
update 3x pt binary build
=> update 3x pt binary build

neural_compressor/torch/algorithms/weight_only/gptq.py, neural_compressor/torch/algorithms/weight_only/rtn.py, neural_compressor/torch/algorithms/weight_only/save_load.py
feature 
Before 3.x, INC returned qdq model and then packed it with gptq-config. Now, INC directly return a packed model.
=>  Remove the save of gptq config

.azure-pipelines/template/docker-template.yml
update docker image prune rules in CI
update docker image prune rules in CI
=> update docker image prune rules in CI

neural_compressor/transformers/quantization/utils.py
=> Replace FORCE_DEVICE with INC_TARGET_DEVICE [transformers]

examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_dynamic/fx/requirements.txt, test/requirements.txt
=> remove accelerate version in unit test

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/requirements_GPU.txt, examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/requirements_cpu_woq.txt
=> Update auto_round requirements for transformers example

docs/source/validated_model_list.md
=> Update model accuracy

README.md, docs/source/publication_list.md
=> [Doc] Add autoround EMNLP24 paper to pub list

.pre-commit-config.yaml, examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/run_generation_gpu_woq.py, neural_compressor/transformers/generation/__init__.py, neural_compressor/transformers/generation/beam_search.py, neural_compressor/transformers/generation/greedy_search.py
feature
For ipex benchmarking
facebook/opt-125m on MTL 
```python run_generation_gpu_woq.py --model facebook/opt-125m  --eval_batch_size 1 --benchmark --profile_token_latency```
---------- Summary: ----------
Inference latency: 1.32614 sec.
Average throughput: 49.01451487489269 samples/sec
First token average latency: 0.03212 sec.
Average 2... latency: 0.02886 sec.
=> Support generation search for transformers examples

docs/source/3x/PT_FP8Quant.md
=> [Document] Fix broken link to FP8 example

.azure-pipelines/scripts/ut/env_setup.sh, test/3x/torch/requirements.txt, test/requirements.txt
=> Remove autoround limit in unit-test

neural_compressor/transformers/models/modeling_auto.py
=> Adapt autoround format

neural_compressor/torch/utils/utility.py
=> remove transformers import from utility

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/README.md, examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/run_clm_no_trainer.py
example
Enhance example for HPU performance
=> Enhance example for HPU performance

setup.py
bug fix
remove useless code in setup.py
=> remove useless code in setup.py

neural_compressor/transformers/models/modeling_auto.py, neural_compressor/transformers/quantization/utils.py
gpt-j lm_head.weight non-contiguous
=> Support non-contiguous weight saving

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/README.md, neural_compressor/evaluation/lm_eval/models/huggingface.py
=> fix bug and update readme

neural_compressor/torch/utils/environ.py, neural_compressor/torch/utils/utility.py
clean up the code.
no api change.
move the optimum habana available to environ.py, because  other available functions are in environ.py
=> improve optimum-habana available check

.azure-pipelines/scripts/install_nc.sh
=> fixed CI IPEX version

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/README.md, neural_compressor/torch/quantization/config.py
bug fix
To avoid loading error if new config parameter is introduced in later release.
=> Update torch config kwargs

neural_compressor/torch/algorithms/weight_only/autoround.py
=> Check autoround before import it

neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
Change-Id: I33fad5c3e80e017099f300782809f24669765d42
=> [Cherry-pick] Make PatchedVLLMKVCache resiliant to forward API changes

neural_compressor/transformers/quantization/utils.py
bug fix
remove `model.to(float32)`
=> Fix glm-4-9b oom issue on BMG

test/3x/torch/quantization/test_pt2e_quant.py
=> Fix the PT2E UT

neural_compressor/torch/algorithms/layer_wise/utils.py, neural_compressor/torch/algorithms/weight_only/gptq.py, neural_compressor/transformers/quantization/utils.py
load non-quantizable layers to memory
=> Support gptq layerwise on client

neural_compressor/adaptor/pytorch.py, neural_compressor/adaptor/torch_utils/weight_only.py
quant_block_list -> to_quant_block_names
=> Adapt autoround v0.4 [2x]

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/run_generation_gpu_woq.py
bug fix
Set pad_token for the tokenizer to avoid evaluation failures
=> Fix `truthfulqa` task evaluation issue

examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt, examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt
=> Add required library for ONNX example

.azure-pipelines/scripts/ut/3x/run_3x_pt.sh, .azure-pipelines/scripts/ut/3x/run_3x_pt_fp8.sh, .azure-pipelines/scripts/ut/3x/run_3x_tf.sh
=> Add import check

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/README.md, examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/run_clm_no_trainer.py
bug fix
Restrict the `Dim` range for exporting.
None
=> Fixed the PT2E LLM example

examples/3.x_api/pytorch/recommendation/dlrm/static_quant/ipex/run_benchmark.sh
=> fix dlrm when using incbench

.azure-pipelines/scripts/ut/3x/run_3x_pt_fp8.sh
=> Refactor FP8 pytest script

neural_compressor/torch/quantization/config.py
=> Update PT2E default config

test/3x/torch/quantization/weight_only/test_transfomers.py
CI fix
[version 4.47.0 provides different generation results when using quantized awq model · Issue #35286 · huggingface/transformers](https://github.com/huggingface/transformers/issues/35286)
=> workaround transformers issue in version 4.47.0

docs/source/3x/gaudi_version_map.md
=> [Document] Add mapping for v3.2 to Gaudi SW stack v1.19

docs/source/publication_list.md
https://blog.squeezebits.com/intel-gaudi-4-fp8-quantization--40269
=> Update publication list with new blog

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/requirements_cpu_woq.txt
=> Add intel-extension-for-pytorch to Transformers-like API requirements

neural_compressor/common/utils/__init__.py, neural_compressor/torch/algorithms/fp8_quant/_core/quantize.py, neural_compressor/torch/algorithms/fp8_quant/_core/scale.py, neural_compressor/torch/algorithms/fp8_quant/_core/scale_methods/ops_quantizer.py, neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
Change-Id: Ia3cd07195c3d738dcde0d545153024aa658ce437
=> Fixed patched moe

neural_compressor/adaptor/torch_utils/gptq.py, neural_compressor/adaptor/torch_utils/layer_wise_quant/utils.py
bug fix
fix bug of lwq gtpq
None
None
=> fix bug of lwq gtpq

test/adaptor/onnxrt_adaptor/test_layer_wise.py
=> add xfail for onnx test_layer_wise.py

README.md, docs/source/3x/PT_FP8Quant.md
Refer to https://inteltf-jenk.sh.intel.com/view/inc-schedule/job/optimum_habana_weekly_model_test/19/artifact/report.html
=> Doc: Update fp8 accuracy test data.

neural_compressor/transformers/models/modeling_auto.py
ipex-gpu supports transformers==4.44.2
=> Adapt ipex xpu transformers version

examples/.config/model_params_pytorch_3x.json, examples/3.x_api/pytorch/multimodal-modeling/quantization/auto_round/mllm.py, examples/3.x_api/pytorch/multimodal-modeling/quantization/auto_round/requirements.txt, examples/3.x_api/pytorch/multimodal-modeling/quantization/auto_round/run_benchmark.sh, examples/3.x_api/pytorch/multimodal-modeling/quantization/auto_round/run_quant.sh
example for microsoft/Phi-3-vision-128k-instruct"
=> Add phi3 vlm  transformers example

neural_compressor/transformers/quantization/utils.py
=> fix saving issue for group_size=-1

README.md
=> bump into 3.3

neural_compressor/torch/algorithms/fp8_quant/_core/common.py, neural_compressor/torch/algorithms/fp8_quant/_core/measure.py, neural_compressor/torch/algorithms/fp8_quant/_core/quantize.py, neural_compressor/torch/algorithms/fp8_quant/_core/utils.py, test/3x/torch/algorithms/fp8_quant/test_utils.py
=> Skip `mlp.gate` (MoE only)

neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
Change-Id: I41a07985d602936e5d6c4f25a061a009bc251253
=> [CP] Correct `PatchedVLLMKVCache` to measure the entire input

examples/onnxrt/image_recognition/onnx_model_zoo/resnet50/quantization/ptq_static/requirements.txt
=> Add transformers to align onnxruntime-extensions=1.14.0

neural_compressor/torch/algorithms/fp8_quant/_core/common.py, neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
=> Refine R1 WOQ Requant 

test/3x/torch/quantization/fp8_quant/test_layer_wise.py
cherry-pick from https://github.com/habana-internal/neural-compressor-fork/pull/189
=> [SW-218939] fix memory mapping failure in UT

.azure-pipelines/scripts/fwk_version.sh, .azure-pipelines/scripts/install_nc.sh, .azure-pipelines/scripts/models/env_setup.sh, .azure-pipelines/scripts/ut/3x/run_3x_pt.sh, .azure-pipelines/scripts/ut/3x/run_3x_tf.sh, .azure-pipelines/scripts/ut/env_setup.sh, .azure-pipelines/scripts/ut/run_basic_adaptor.sh, .azure-pipelines/template/docker-template.yml, test/3x/torch/requirements.txt
=> update habana docker and PyTorch and related packages to latest versions

neural_compressor/torch/algorithms/smooth_quant/smooth_quant.py, neural_compressor/torch/algorithms/static_quant/static_quant.py, test/3x/torch/quantization/test_smooth_quant.py, test/3x/torch/quantization/test_static_quant.py, test/3x/torch/quantization/weight_only/test_transformers.py
https://jira.devtools.intel.com/browse/ILITV-3913
=> improve 3x ut on bf16 supported machine

neural_compressor/torch/algorithms/fp8_quant/_core/scale_methods/ops_quantizer.py
Change-Id: Ic1b11c25fa7402ab0b4e2c0cca0939a89d20ffa2
=> Fix PTS Acc Issue

neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
=> Correct linear measure

test/algorithm/test_smooth_quant.py
https://jira.devtools.intel.com/browse/ILITV-3924
hf-internal-testing/tiny-random-gptj update the model recently. https://huggingface.co/hf-internal-testing/tiny-random-gptj/commits/main, so I set the revision to use the old commit to keep UT accuracy value.
=> add revision for hf-internal-testing/tiny-random-gptj in UT

neural_compressor/torch/algorithms/fp8_quant/save_load.py
=> add the missed change during cherry-pick

examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/requirements.txt, examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/ipex/requirements.txt
=> restrict lm_eval version to <= 0.4.7

neural_compressor/torch/algorithms/weight_only/autoround.py
=> Adapt autoround v0.5

examples/3.x_api/pytorch/multimodal-modeling/quantization/auto_round/requirements.txt
requirements
transformers>=4.50,<4.52
=> Update transformers version for VLM example

neural_compressor/torch/export/pt2e_export.py, neural_compressor/torch/utils/environ.py
API changed or not: new export function for torch 2.6 and later
None
=> Update export function for torch 2.6

docs/source/3x/gaudi_version_map.md
add mapping entry between v3.4 and v1.21
=> [Doc] add mapping between v3.4 and v1.21

.azure-pipelines/ut-3x-pt-fp8.yml, .azure-pipelines/ut-3x-pt.yml, .azure-pipelines/ut-3x-tf.yml, .azure-pipelines/ut-basic.yml
=> Add continueOnError to avoid baseline stages block CI

neural_compressor/common/base_config.py
Enhancement of config
When updating config attribution, we need to propagate the update to global config and others
=> support update config after initialization

neural_compressor/torch/quantization/quantize.py
Enhancement
collect common code between quantize and prepare function to avoid missing change.
=> add preprocess_quant_config to collect common code

neural_compressor/common/utils/save_load.py, neural_compressor/torch/algorithms/static_quant/utility.py
eval usage is not secure. replace them with re.match
=> fix security issue

docs/source/publication_list.md
update pub list with llama4 blog
=> [doc ]update pub list with llama4 blog

neural_compressor/torch/algorithms/weight_only/save_load.py
Change-Id: I36d1ca10426b65abfe2093091f41906cecf2fcaf
=> Fix WoQ loading for Large Model

docs/source/publication_list.md
=> [Documentation] Add qwen3 blog to pub list

neural_compressor/torch/algorithms/fp8_quant/_quant_common/quant_config.py
The environment variable `INC_MEASUREMENT_DUMP_PATH_PREFIX` specifies the root directory where measurement statistics were saved.
The final path is constructed by joining this root directory with the `dump_stats_path` defined in the quantization JSON file specified by the `QUANT_CONFIG` environment variable.
Example:
```bash
INC_MEASUREMENT_DUMP_PATH_PREFIX=/mnt/disk3/vllm-fork
dump_stats_path (from config): "scripts/nc_workspace_measure_kvache/inc_measure_output"
Resulting full path: "/mnt/disk3/vllm-fork/scripts/nc_workspace_measure_kvache/inc_measure_output_xx"
```
=> Add `INC_MEASUREMENT_DUMP_PATH_PREFIX`

neural_compressor/torch/algorithms/fp8_quant/_quant_common/quant_config.py
=> Fix path check

.azure-pipelines/scripts/ut/3x/run_3x_pt_fp8.sh, .azure-pipelines/template/docker-template.yml, README.md, test/3x/torch/requirements.txt
=> Update habana docker image version and DeepSpeed dependency to 1.21.0

README.md, neural_compressor/version.py
=> Bump release version into v3.4

.azure-pipelines/model-test-3x.yml, .azure-pipelines/scripts/fwk_version.sh, .azure-pipelines/scripts/install_nc.sh, .azure-pipelines/scripts/ut/3x/run_3x_pt.sh
=> update torch to 2.7.0 in CI

neural_compressor/torch/algorithms/fp8_quant/_quant_common/quant_config.py
=> Check patch for quant only

neural_compressor/transformers/models/modeling_auto.py
=> Fix g_idx init for GPTQ

neural_compressor/transformers/models/modeling_auto.py
=> Adapt transformers v4.53.1

neural_compressor/torch/algorithms/fp8_quant/_core/scale_methods/scales_method.py, neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
Change-Id: Ice995de6e1054f1c08c8a7336d7711bd961e4952
=> Force FP32 scale

examples/3.x_api/pytorch/cv/mixed_precision/main.py
https://jira.devtools.intel.com/browse/ILITV-4016
@XuehaoSun  Please help trigger the extension test.
=> Fix Mix Precision Example

neural_compressor/torch/quantization/config.py
bug fix
fix cpu fp8 quant unittest
=> fix cpu fp8 quant unittest

neural_compressor/torch/algorithms/fp8_quant/_core/quantized_func_wrappers/cpu/cpu_quantized_func_wrapper.py, neural_compressor/torch/algorithms/fp8_quant/_quant_common/quant_config.py
bug fix
Fix CPU FP8 per-tensor QDQ
vit and stable-diffusion have this problem
based on https://github.com/intel/neural-compressor/pull/2238
=> Fix CPU FP8 per-tensor QDQ

neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
Dependes on https://github.com/HabanaAI/vllm-hpu-extension/pull/317
=> Update MOE API

examples/.config/model_params_pytorch_3x.json, examples/3.x_api/pytorch/diffusion_model/diffusers/stable_diffusion/fp8_quant/README.md, examples/3.x_api/pytorch/diffusion_model/diffusers/stable_diffusion/fp8_quant/main.py, examples/3.x_api/pytorch/diffusion_model/diffusers/stable_diffusion/fp8_quant/requirements.txt, examples/3.x_api/pytorch/diffusion_model/diffusers/stable_diffusion/fp8_quant/setup.sh
example
Add stable_diffusion example
=> Add stable_diffusion example

neural_compressor/evaluation/lm_eval/accuracy.py, neural_compressor/evaluation/lm_eval/models/huggingface.py
=> fix ImportError when lm_eval >= 0.4.8

.azure-pipelines/scripts/install_nc.sh, .azure-pipelines/scripts/ut/3x/run_3x_pt.sh, .azure-pipelines/scripts/ut/3x/run_3x_pt_fp8.sh, .azure-pipelines/template/docker-template.yml, .azure-pipelines/ut-3x-pt-fp8.yml, .azure-pipelines/ut-3x-pt.yml, README.md, test/3x/torch/requirements.txt
=> Update habana version

neural_compressor/torch/algorithms/fp8_quant/prepare_quant/prepare_model.py
Remove `INC_ENABLE_TP_RANK_INFO `.
Please be aware of this change @czhu15 @yangulei.
=> Use tp group for vllm by default
