intel/neural-compressor

- neural_compressor/model/onnx_model.py
bug fix
**Defect/regression:** 
File "/home/tensorflow/miniconda3/envs/onnxrt-1.13.1-3.8-clx8280/lib/python3.8/site-packages/neural_compressor/model/onnx_model.py", line 406, in topological_sort assert len(nodes) == len(self.model.graph.node) AssertionError
**Profile:** log: 
https://inteltf-jenk.sh.intel.com/blue/rest/organizations/jenkins/pipelines/intel-lpot-validation/runs/216404/nodes/114/log/?start=0
**report:**  https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/3406/artifact/report.html
**commit id ：** 
0b7134309ed1ded5fde9905e5686b70edef4b9ad failed
71b056b53015e05b7ab9289d31edaf4200dca628 pass
**Framework:** onnxrt
**Framework version:** 1.13.1
JIRA ticket: [ILITV-2434](https://jira.devtools.intel.com/browse/ILITV-2434)
extension test: mask-rcnn-qdq
no
> ONNX mask_rcnn_qdq failed with AssertionError

- .github/pull_request_template.md
- neural_compressor/experimental/metric/evaluate_squad.py
- bug fix  
Fixed the docstring typo in experimental/metric
No
Scan result by pydocstyle:
None
> fixed docstring typo in experimental/metric

- docs/adaptor.md
Update the document of adaptor.
No API changed
> Update adaptor document

- neural_compressor/experimental/common/criterion.py
Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>
> add DocString for SelfKnowledgeDistillation

- .azure-pipelines/code-scan.yml
- .azure-pipelines/docker/DockerfileCodeScan.devel
- .azure-pipelines/scripts/codeScan/bandit/bandit.sh
- .azure-pipelines/scripts/codeScan/pydocstyle/pydocstyle.sh
- .azure-pipelines/scripts/codeScan/pylint/pylint.sh
- neural_compressor/experimental/common/__init__.py
- neural_compressor/experimental/pruning.py
validation 
Add docstring check for 'neural_compressor/experimental', could be merged after all the issue cleaned in this path. 
docstring issue in neural_compressor/experimental can be detected. 
Azure CI
No
> support pydocstyle check

- neural_compressor/adaptor/tf_utils/graph_rewriter/int8/fuse_matmul_requantize.py
- neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
bug fix  
JIRA ticket: ILITV-1851
The Time_series_LSTM tuning issue can be fixed.
No.
> Fix Time_series_LSTM tuning issue

- neural_compressor/experimental/common/criterion.py
others
fix master pylint issue
> fix pylint issue

- neural_compressor/experimental/benchmark.py
- test/benchmark/test_benchmark.py
Fixed benchmark error for Tensorflow Keras models
API changed
Benchmark error in some Tensorflow Kerase models
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2443
Run example: resnet101_keras, inception_v3_keras.
> Fixed benchmark error for tensorflow model

- neural_compressor/contrib/strategy/sigopt.py
- neural_compressor/contrib/strategy/tpe.py
- requirements.txt
- setup.py
- test/requirements.txt
Signed-off-by: yiliu30 <yi4.liu@intel.com>
- bug fix
Adjust the `hyperopt` and `sigopt` as extras requirements.
JIRA ticket: [ILITV-2452](https://jira.devtools.intel.com/browse/ILITV-2452)
`hyperopt` and `sigopt`  are not hard dependencies.
Pre-CI
Any library dependency introduced or removed:
- `hyperopt` is required only when the user uses `tpe` strategy.
- `sigopt` is required only when the user uses `sigopt` strategy.
> Adjust the hyperopt and sigopt as extras requirements

- neural_compressor/conf/config.py
- neural_compressor/conf/pythonic_config.py
- neural_compressor/config.py
Set use_bf16 default value to True and Fixed set random seed value error. 
No API changed.
We expect use bf16 by default and set random seed successfully.
local tested
> Set default value for use_bf16 and fixed random seed setting error

- neural_compressor/adaptor/tf_utils/graph_converter.py
- neural_compressor/model/model.py
feature
JIRA ticket: ILITV-2471
Turn off ITEX optimization pass
ITEX optimization has broken INC calibration process. INC should turn off ITEX optimization pass in calibration stage.
UT, Pre-CI and ITEX OOB extension test.
No.
> Turn off ITEX optimization pass

- neural_compressor/adaptor/pytorch.py
Fixed UT error for bf16 op list for QAT mode
API changed
For QAT mode, there is no bf16_op_list, so it will lead to error.
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2474
Run UT successfully in SPR machine.
Local tesed
> Fixed UT error for bf16 op list for QAT mode

- neural_compressor/adaptor/tf_utils/graph_converter.py
- neural_compressor/experimental/benchmark.py
- test/itex/test_tensorflow_itex_basic.py
bug fix  
JIRA ticket: ILITV-2476
ITEX GPU mode only run single instance for now.
UT, Pre-CI test.
No.
> Disable multi instance for ITEX GPU benchmark

- examples/tensorflow/image_recognition/tensorflow_models/quantization/ptq/densenet121.yaml
- examples/tensorflow/image_recognition/tensorflow_models/quantization/ptq/densenet161.yaml
- examples/tensorflow/image_recognition/tensorflow_models/quantization/ptq/densenet169.yaml
bugfix
Add op-wise configs back to densenet models, since removing them leads to failures in tuning with TF spr-base.
JIRA ticket: [ILITV-2444](https://jira.devtools.intel.com/browse/ILITV-2444)
Tuning failure reported in https://jira.devtools.intel.com/browse/ILITV-2444 will be fixed.
https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-mr-extension/3554/
No dependency changed.
> Add op-wise configs back to densenet models

- .azure-pipelines/scripts/codeScan/pyspelling/lpot_dict.txt
- examples/.config/model_params_pytorch.json
- examples/README.md
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/README.md
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/conf.yaml
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/requirements.txt
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_benchmark.sh
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_tuning.sh
Signed-off-by: Wang, Chang1 <chang1.wang@intel.com>
> add examples for  GPTJ

- neural_coder/__main__.py
- neural_coder/docs/PythonLauncher.md
Neural Coder launcher argument name change
Neural Coder mod launcher arg: "strategy" to "approach"
arg name change, no risk
Locally
No
> Neural Coder mod launcher arg: "strategy" to "approach"

- .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
- neural_coder/README.md
- neural_coder/__main__.py
- neural_coder/backends/intel_extension_for_transformers.yaml
- neural_coder/coders/autoinc/autoinc_harness.py
- neural_coder/coders/pytorch/change_trainer_to_nlptrainer.py
- neural_coder/docs/PythonLauncher.md
- neural_coder/interface.py
Signed-off-by: Yao, Kai [kai.yao@intel.com](mailto:kai.yao@intel.com)
Neural Coder enable backend support for ```intel_extension_for_transformers```
Neural Coder enable backend support for ```intel_extension_for_transformers```. Intel Extension for Transformers: https://github.com/intel/intel-extension-for-transformers
The enabling pattern is as follows:
```
from intel_extension_for_transformers import metric, objectives, QuantizationConfig
from intel_extension_for_transformers.optimization.trainer import NLPTrainer
trainer = NLPTrainer(......)
metric = metrics.Metric(name="eval_f1", is_relative=True, criterion=0.01)
objective = objectives.performance
q_config = QuantizationConfig(approach="PostTrainingStatic", metrics=[metric], objectives=[objective])
MODEL_NAME = …
```
> Neural Coder enable backend support for intel_extension_for_transformers

- neural_compressor/contrib/strategy/sigopt.py
- neural_compressor/contrib/strategy/tpe.py
- test/requirements.txt
Signed-off-by: yiliu30 <yi4.liu@intel.com>
- Others: Optimize user experience
Try to import `hyperopt` and `sigopt` from the local environment when user specify the strategy as `tpe` or `sigopt`
Pre-CI
Remove `hyperopt` and `sigopt` from the test requirements list.
> [Strategy] Adjust the hints for import hyperopt and sigopt

- .azure-pipelines/scripts/ut/env_setup.sh
- neural_compressor/adaptor/tf_utils/graph_converter.py
- neural_compressor/adaptor/tf_utils/graph_rewriter/int8/fuse_conv_redundant_dequantize.py
- neural_compressor/adaptor/tf_utils/graph_rewriter/int8/fuse_conv_requantize.py
- test/tfnewapi/test_tensorflow_graph_conv_requantize_fusion.py
- test/tfnewapi/test_tensorflow_graph_qdq_bn_fusion.py
- test/tfnewapi/test_tensorflow_graph_qdq_conv3d_fusion.py
feature
JIRA ticket: ILITV-2475
Support QuantizedConv + BiasAdd + Activation + Dequantize fusion
The _FusedQuantizedConv3D/_FusedQuantizedConv2D/_FusedQuantizedDepthwiseConv2D/_FusedQuantizedDeconv2D/_FusedQuantizedDeconv3D + Dequantize can be fused as bf16 output to improve the performance.
No.
> Support QuantizedConv + BiasAdd + Activation + Dequantize fusion

- .azure-pipelines/model-test.yml
- .azure-pipelines/scripts/ut/run_basic_adaptor.sh
- .azure-pipelines/scripts/ut/run_basic_adaptor_tfnewapi.sh
- .azure-pipelines/scripts/ut/run_basic_ipex.sh
- .azure-pipelines/scripts/ut/run_basic_itex.sh
- .azure-pipelines/scripts/ut/run_basic_others.sh
- .azure-pipelines/scripts/ut/run_ncoder.sh
- .azure-pipelines/scripts/ut/run_ux.sh
validation 
1. Remove resnet50_fashion from test since its performance is not stable on Azure. 
2. Update UT log.
> update azure pipeline

- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/eager/README.md
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/eager/requirements.txt
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/eager/run_glue_tune.py
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/eager/run_tuning.sh
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/requirements.txt
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_tuning.sh
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/README.md
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/requirements.txt
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue_tune.py
- examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_tuning.sh
add export for new API examples
> add export for new API examples

- examples/README.md
- examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/README.md
- examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/README.md
- examples/tensorflow/image_recognition/SavedModel/quantization/ptq/README.md
- examples/tensorflow/image_recognition/keras_models/resnet50_fashion/quantization/ptq/README.md
- examples/tensorflow/image_recognition/tensorflow_models/quantization/ptq/README.md
- examples/tensorflow/object_detection/yolo_v3/quantization/ptq/README.md
documentation 
fix models readme
fix models readme
no
no
> fix models readme

- .azure-pipelines/scripts/ut/collect_log.sh
- .azure-pipelines/ut-basic.yml
- .azure-pipelines/ut-ncoder.yml
fix azure UT Basic artifact error
fix azure UT Basic artifact error:
set condition: succeededOrFailed()
another fix
generate report when coverage failed
UT-Basic succeed,
generate report when coverage failed
no
> azure ut basic fix

- .azure-pipelines/scripts/ut/run_basic_others.sh
- .azure-pipelines/ut-basic.yml
- .azure-pipelines/ut-ncoder.yml
- .azure-pipelines/ut-ux.yml
- test/itex/test_keras_in_keras_out.py
- test/itex/test_tensorflow_itex_basic.py
validation 
1. Use local cached model for dynas ut test, walk around for connection timeout issue. 
2. Fix ITEX ut issue. 
CI pass
CI test
No
> use local cached model for dynas ut test

- neural_compressor/adaptor/pytorch.py
Enhancement benchmark with dataloader for PyTorch framework 
No API changed
Enhancement benchmark with dataloader for PyTorch framework 
Benchmark success with the dataloader for huggingface model
Local test
> Enhancement benchmark with dataloader

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/adaptor/onnxrt_qdq.yaml
- neural_compressor/adaptor/ox_utils/calibration.py
Signed-off-by: Mengni Wang <mengni.wang@intel.com>
task
TRT EP has some limitations, add recipe for it to enable QDQ models with TRT EP.
> Add recipe for TRT EP

- neural_compressor/adaptor/pytorch.py
bug fix
No API changed
For QAT, if torch <1.11, neural_compressor didn't support bf16
QAT successfully in torch <1.11
Local tested
> Fixed bf16 error in QAT for torch version < 1.11

- neural_compressor/adaptor/tf_utils/graph_converter.py
bug fix
JIRA ticket: ILITV-2525
[TF][ITEX]resnetv2_50 failed in tuing with result 0.001
In this pb file, the Add op use 'AddN'. This caused the y-pattern can't match.
ITEX resnetv2_50 tuning accuracy issue can be fixed.
UT, Pre-CI test.
No.
> Fix ITEX resnetv2_50 tuning accuracy issue

- neural_coder/__main__.py
- neural_coder/backends/keras_inc.yaml
- neural_coder/coders/autoinc/domain.py
- neural_coder/docs/PythonLauncher.md
- neural_coder/docs/SupportMatrix.md
- neural_coder/examples/keras/mnist.py
- neural_coder/graphers/model.py
- neural_coder/interface.py
Feature addition: support Keras script-based model as ```keras_inc```
- Enabled support of auto-quantizing Keras script-based model
- Also enabled ```inc_auto``` as a default optimization for launcher and for API: our domain detector will detect whether the code is PT/TF/Keras/ONNX and choose default feature accordingly:
- PyTorch: default dynamic quantization scheme
- TensorFlow/Keras model based: default TensorFlow quantization scheme
- Keras script-based: default Keras script-based static quantization scheme
- ONNX: default dynamic quantization scheme
- Also enabled "enable_only" ```-e``` mode/argument in neural_coder launcher for testing
- Update docs accordingly
Able to **enable INC on Keras script-based model**, for example [this …
> Neural Coder enable support of Keras script-based model

- neural_compressor/training.py
Validation  requirement
No API changed
For preci test, the log is required to indicate successful training 
Print successful log after training. 
Local tested
> Add a flag for preci test of QAT

- neural_compressor/model/tensorflow_model.py
bug fix
JIRA ticket: ILITV-2531
[release1st][tf2.10.0] mobilenetv2_saved,mobilenetv1_saved failed with ValueError
The saved model can be tuned successfully.
UT, Pre-CI test.
No.
> Fix model type not recognized for saved model issue

- test/strategy/test_sigopt.py
bug fix
Fix the failed unit-test `test_run_sigopt_one_trial_new_api` by updating the backend field from framework name to `'default'`;
JIRA ticket: [ILITV-2544](https://jira.devtools.intel.com/browse/ILITV-2544)
UT `test_run_sigopt_one_trial_new_api` pass.
By Pre-CI.
No.
> Fix failed `test_run_sigopt_one_trial_new_api`

- neural_compressor/conf/config.py
- neural_compressor/conf/pythonic_config.py
- neural_compressor/config.py
- neural_compressor/experimental/quantization.py
- test/strategy/test_mse_v2_2.x.py
- test/strategy/test_optimization_level_2.x.py
Signed-off-by: intel-zhangyi <yi5.zhang@intel.com>
Refactor.
Refactor the new API. Remame `optimization_level` to `quant_level`;
The field `optimization_level` is replaced by `quant_level` in all configs.
By PreCI tests.
No.
> Rename `optimization_level` to `quant_level`

- examples/pytorch/recommendation/dlrm/quantization/ptq/eager/dlrm_s_pytorch_tune.py
- examples/pytorch/recommendation/dlrm/quantization/ptq/fx/dlrm_s_pytorch_tune.py
- examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/dlrm_s_pytorch.py
- neural_compressor/adaptor/pytorch.py
- neural_compressor/model/torch_model.py
bug fix
JIRA ticket: https://jira.devtools.intel.com/browse/ILITV-2491
> Fix DLRM OOM issue

- neural_compressor/conf/config.py
- neural_compressor/experimental/distillation.py
- neural_compressor/training.py
Enhancement API 
No API changed
support config list which length is 1
set model.backend for "default" in new API
fixed distillation criterion is none issue for oneshot optimization.
we can pass a list with one config to prepare_compression
local tested
> support config list which length is 1 and add “model.backend" for pruning and distillation config

- neural_compressor/experimental/quantization.py
bug fix
JIRA ticket: [ILITV-2535](https://jira.devtools.intel.com/browse/ILITV-2535)
User defined Process transforms should be registered in the transform registry under `neural_compressor/experimental/data/transforms` but not the `neural_compressor/data/transforms`
Rebuild https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-release-v2.0/99/
None
> Fix the cases when user-defined transforms are not registered in quantization

- neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
bug fix
JIRA ticket: ILITV-2567, ILITV-2568
[release1st][tf2.11.0202250] mobilenetv2 got invalid int8 accuracy with TF spr-base
[release1st][tf2.11.0202250] ssd_resnet50_v1,ssd_resnet50_v1_ckpt can't reach accuracy with TF spr-base on both SPR and CLX
Fix mobilenetv2, ssd_resnet50_v1,ssd_resnet50_v1_ckpt accuracy issue with TF spr-base.
No.
> Fix mobilenetv2 accuracy issue with spr-base

- conda_meta/basic/meta.yaml
- conda_meta/full/meta.yaml
fix conda install deps concflict
JIRA ticket: 
conda install success
local test
no
> set numpy version to fix deps conflict

- examples/pytorch/image_recognition/3d-unet/quantization/ptq/eager/nnUnet/requirements.txt
- examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/requirements.txt
bug fix.
3dunet: https://jira.devtools.intel.com/browse/ILITV-2576
maskrcnn_fx: https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-top-release-v2.0/77/artifact/linux/pytorch/maskrcnn_fx/pytorch-maskrcnn_fx-linux-clx8280-tune.log
> fix numpy version for old_api_example

- examples/tensorflow/image_recognition/tensorflow_models/quantization/ptq/inception_v3.yaml
- examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/bert.yaml
- examples/tensorflow/object_detection/tensorflow_models/quantization/ptq/faster_rcnn_inception_resnet_v2.yaml
- examples/tensorflow/object_detection/tensorflow_models/quantization/ptq/faster_rcnn_resnet101.yaml
bug fix
JIRA ticket: ILITV-2566
inception_v3,bert_large_squad_model_zoo,faster_rcnn_inception_resnet_v2,faster_rcnn_inception_resnet_v2_saved,faster_rcnn_resnet101,faster_rcnn_resnet101_saved can't reach the accuracy goal on SPR with spr-base.
Fix this issue by turning off BF16 conversion.
UT, Pre-CI and model test.
No.
> Turn off BF16 conversion for some models whose accuracy can't reach the goal

- neural_compressor/adaptor/tf_utils/graph_converter.py
bug fix
JIRA ticket: ILITV-2580
[release2nd][tf2.11.0][spr-base]efficientnet_b0 failed with NotFoundError: Op type not registered 'swish_f32'
efficientnet_b0 tuning failed with NotFoundError: Op type not registered 'swish_f32' can be fixed.
No.
> Fix efficientnet_b0 tuning failed with Op type not registered swish_f32

- conda_meta/basic/meta.yaml
- conda_meta/full/meta.yaml
- neural_compressor/version.py
- test/config/test_config.py
others
bump release version into v2.0
> bump release version into v2.0

- neural_compressor/adaptor/torch_utils/util.py
Signed-off-by: XuhuiRen <xuhui.ren@intel.com>
Fix a error that "getattr()" cannot recognize the attribute name during tuning
[GitHub issue #422](https://github.com/intel/neural-compressor/issues/422)
The customer of PyTorch Lightning could quantize the model with INC
Reported by the lightning user
No
> Revision for PyTorch Lightning

- neural_compressor/adaptor/pytorch.py
Signed-off-by: Wang, Chang1 <chang1.wang@intel.com>
bug fix
model : convnext
```
2023-01-10 12:55:34 [ERROR] Unexpected exception AttributeError("'GraphModule' object has no attribute 'features.1.0.layer_scale'") happened during tuning.
Traceback (most recent call last):
File "/home/changwa1/neural-compressor/neural_compressor/experimental/quantization.py", line 177, in execute
self.strategy.traverse()
File "/home/changwa1/neural-compressor/neural_compressor/strategy/strategy.py", line 229, in traverse
self.q_model = self.adaptor.quantize(
File "/home/changwa1/neural-compressor/neural_compressor/utils/utility.py", line 293, in fi
res = func(*args, **kwargs)
File "/home/changwa1/neural-compressor/neural_compressor/adaptor/pytorch.py", line 2889, in quantize …
```
> improve logging of scale and zero_point during fx static quantization

- examples/README.md
documentation 
Mark 1.x API examples with flag to help user quickly find 2.0 API examples, the flag will be removed after API migrate is done.
> mark 1.x API examples with flag

- examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/main.py
- examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
- examples/pytorch/object_detection/ssd_resnet34/quantization/ptq/ipex/infer.py
- examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/dlrm_s_pytorch.py
- neural_compressor/utils/pytorch.py
1. modify benchmark to compare ipex optimized torchscript mode int8 model v.s. ipex optimized torchscript mode fp32 model
2. remove invaild code about get example_input in int8 model load function
> improve ipex example benchmark

- test/adaptor/pytorch_adaptor/test_adaptor_pytorch_1.x.py
The input tensor of middle layer goes to 1E30 with random input, which will cause an overflow sometimes. (No idea why it overflows) 
Anyway, we can reset the input to 1 to avoid this error.
[ILITV-2558(https://jira.devtools.intel.com/browse/ILITV-2558)
UT pass
> fix UT overflow error

- neural_coder/backends/pytorch_inc_dynamic_quant.yaml
- neural_coder/backends/pytorch_inc_dynamic_quant_fp8.yaml
- neural_coder/backends/pytorch_inc_huggingface_optimum_dynamic.yaml
- neural_coder/backends/pytorch_inc_huggingface_optimum_static.yaml
- neural_coder/backends/pytorch_inc_static_quant_fx.yaml
- neural_coder/backends/pytorch_inc_static_quant_fx_fp8.yaml
- neural_coder/backends/pytorch_inc_static_quant_ipex.yaml
- neural_coder/coders/autoinc/eval_func.py
- neural_coder/docs/PythonLauncher.md
- neural_coder/interface.py
- neural_coder/launcher.py
change logic of which default API design to be enabled
1. a change of default adopted optimization API's logic:
- Old logic:
-- Default all use Optimum API for launchers, no matter INC launcher or Optimum launcher
- New logic:
-- If user use INC launcher, then default API is INC API. 
-- If user use Optimum launcher, then default API is Optimum API.
Optimum side's modification is in this [PR](https://github.com/huggingface/optimum-intel/pull/183)
2. also refined some backend yamls
3. also added pre-requisite in Python Launcher example
locally
no
> Neural Coder use INC API by default instead of Optimum

- neural_compressor/adaptor/pytorch.py
Adapt to the latest dynamic qconfig
Resolve embedding miss in dynamic quantization on torch1.13.1
JIRA ticket: [ILITV-2673](https://jira.devtools.intel.com/browse/ILITV-2673)
> adapt to the latest dynamic qconfig

- docs/source/pruning.md
Signed-off-by: spycsh <sihan.chen@intel.com>
documentation
If you read https://github.com/intel/neural-compressor/blob/master/docs/source/pruning.md
there is a broken link
fix that broken link
None
None
> Fix a broken link in pruning.md

- neural_compressor/adaptor/tf_utils/graph_converter.py
feature
JIRA ticket: ILITV-2711
The memory usage can be reduced for performance only mode.
Pre-CI, model test and OOB test.
No,
> Reuse the fp32 model to reduce the memory usage for performance only mode

- neural_compressor/adaptor/torch_utils/util.py
bug fix.
ipex only support asym + quint8 and sym + qint8 now.
the input force dtype and activation observer dtype is mismatched,
```
"9": {
"op_type": "<method 'add' of 'torch._C._TensorBase' objects>",
"op_type_is_module": false,
"fqn": "",
"input_tensor_infos": [
{
"id": 8,
"orig_dtype": "torch.float32",
"inf_dtype": "torch.float32",    
"force_dtype": "torch.float32",
"scale": [
0.014584152959287167
],
"zero_point": [
121
]
},
{
"id": 9,
"orig_dtype": "torch.float32",
"inf_dtype": "torch.qint8",     # input force dtype is torch.qint8
"force_dtype": "torch.qint8",
"scale": [
0.037025969475507736
],
"zero_point": [
161
]
}
],
"weight_tensor_infos": [],
"output_tensor_infos": [
{
"id": 10,
"orig_dtype": "torch.float32",
"inf_dtype": "torch.float32",
"scale": [
0.04625902697443962
], …
```
> Fix IPEX config json changed according to tune_cfg

- examples/README.md
- examples/onnxrt/nlp/onnx_model_zoo/bert-squad/quantization/ptq/main.py
- examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq/gpt2.py
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/eval_lambada.py
- examples/tensorflow/image_recognition/SavedModel/mobilenet_v2/quantization/ptq/main.py
- examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/main.py
- examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/main.py
- examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/main.py
- examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/main.py
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/main.py
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/main.py
- examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/main.py
- examples/tensorflow/object_detection/yolo_v3/quantization/ptq/infer_detections.py
- examples/tensorflow/recommendation/wide_deep_large_ds/quantization/ptq/inference.py
others
Remove the unnecessary op wise setting(verified with both basic and new auto strategy), and tune with the new strategy. 
If it doesn't work on SPR machine, we will add back. 
Models may failed tuning on SPR machine. 
CI
No
> op wise setting remove

- docs/source/export.md
- examples/.config/model_params_pt2onnx.json
- examples/pytorch/image_recognition/torchvision_models/export/fx/README.md
- examples/pytorch/image_recognition/torchvision_models/export/fx/main.py
- examples/pytorch/image_recognition/torchvision_models/export/fx/onnx_evaluation.py
- examples/pytorch/image_recognition/torchvision_models/export/fx/requirements.txt
- examples/pytorch/image_recognition/torchvision_models/export/fx/run_benchmark.sh
- examples/pytorch/image_recognition/torchvision_models/export/fx/run_export.sh
- examples/pytorch/nlp/huggingface_models/text-classification/export/fx/README.md
- examples/pytorch/nlp/huggingface_models/text-classification/export/fx/onnx_evaluation.py
- examples/pytorch/nlp/huggingface_models/text-classification/export/fx/requirements.txt
- examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_benchmark.sh
- examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_export.sh
- examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_glue.py
- neural_compressor/conf/config.py
- neural_compressor/experimental/export/torch2onnx.py
add two export examples to validate accuracy and performance of export API.
JIRA ticket: [ILITV-2643](https://jira.devtools.intel.com/browse/ILITV-2643)
> add two export examples to validate accuracy and performance of export API.

- .azure-pipelines/scripts/ut/run_basic_others.sh
- .azure-pipelines/scripts/ut/run_basic_pruning.sh
- .azure-pipelines/template/docker-template.yml
- .azure-pipelines/ut-basic.yml
- setup.py
> fix ut coverage

- neural_compressor/adaptor/pytorch.py
- neural_compressor/model/torch_model.py
- neural_compressor/training.py
- neural_compressor/utils/pytorch.py
- neural_compressor/utils/utility.py
- test/adaptor/pytorch_adaptor/test_adaptor_pytorch_1.x.py
- test/adaptor/pytorch_adaptor/test_adaptor_pytorch_2.x.py
Adapt to PyTorch 2.0 version  
No API changed
Since PyTorch 2.0 changed some quantization API name, so we need to change code to adapt to it.
JIRA ticket: [#2762](https://jira.devtools.intel.com/browse/ILITV-2762)
quantization successful with PyTorch 2.0. 
Local tested
> Adapt to PyTorch 2.0 version

- neural_compressor/adaptor/tf_utils/graph_converter.py
API changed or not: No
JIRA ticket: [ILITV-2759](https://jira.devtools.intel.com/browse/ILITV-2759)
the expected behavior that triggered by this PR : TF backend will not request a "__len__" method from dataloaders 
how to reproduce the test (including hardware information): Preci
any library dependency introduced or removed: No
> Modify the Check on Length of Dataloader for TF Backend

- docs/source/mixed_precision.md
- neural_compressor/adaptor/onnxrt.py
- neural_compressor/config.py
- neural_compressor/mix_precision.py
- test/mixed_precision/test_mixed_precision.py
> Fix mix precision

- README.md
- docs/build_docs/build.sh
- docs/source/api-doc/adaptor/torch_utils.rst
- docs/source/api-doc/adaptor/torch_utils/onnx.rst
- docs/source/user_guide.md
documentation
Fix the error to break online doc building:
remove neural_compressor.adaptor.torch_utils.onnx.py, but no remove it in rst file.
It break the online doc building.
Fix the link issue in user guide and welcome page in online document
> fix error of building doc and user guide link issue

- neural_compressor/adaptor/torch_utils/util.py
- neural_compressor/experimental/export/torch2onnx.py
- neural_compressor/quantization.py
- neural_compressor/utils/pytorch.py
- test/export/test_torch2onnx.py
redirect weight for fine-grained fx modules and fix export bug.
[AttributeError: 'GraphModule' object has no attribute 'weight' - flan-t5-small dynamic quantization](https://github.com/huggingface/optimum-intel/issues/212)
Fix export bug raised by [PR642](https://github.com/intel/neural-compressor/pull/642)
> add weight for fx_model and fix export bug

- neural_compressor/quantization.py
Fixed case error for without tuning
No API changed
In 2.x API, if user didn't set eval_func, eval_dataloader and eval_metric, then neural compressor should not to tune with accuracy. 
Quantized model without tuning if user doesn't set eval_func, eval_dataloader and eval_metric. 
Local tested
> Fixed case error for without tuning

- neural_compressor/benchmark.py
bug fix
Pytorch model runs benchmark on Windows reported no 'call_one' interface.
Pytorch and Tensorflow benchmark can run successfully on Windows.
Pre-CI and Pytorch, TF model benchmark test on Windows.
No.
> Fix pytorch windows benchmark issue

- examples/README.md
remove incomplete models from README
remove old API examples maskrcnn_fx, wav2vec_fx, rnnt, blendcnn,   
will be target next release. 
No
No
No
> remove incomplete models from README

- neural_compressor/adaptor/tf_utils/graph_converter.py
bug fix
Tensorflow only enable bf16 mixed precision on BF16 machine.
The BF16 is enabled on BF16 machine and disabled on non-BF16 machine. 
UT and Pre-CI test.
No.
> Disable bf16 mixed precision on non-bf16 machine for TF

- neural_compressor/adaptor/torch_utils/bf16_convert.py
- neural_compressor/utils/pytorch.py
Add log for bfloat16 for the PyTorch framework  
No API changed
Add log for bfloat16 for PyTorch framework 
It will print the bf16 log when HW supports bfloat16.
Local tested
> Add log for bfloat16 data type for PyTorch framework

- examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_static/fx/requirements.txt
bug fix
limit the torchaudio version to +cpu, not +rocm.
https://jira.devtools.intel.com/browse/ILITV-2798
> fix torchaudio example requirements

- neural_compressor/adaptor/tf_utils/graph_rewriter/generic/pre_optimize.py
- test/adaptor/tensorflow_adaptor/test_tensorflow_graph_conv_fusion.py
bug fix
Change the order of MoveSqueezeAfterReluOptimizer and InjectDummyBiasAddOptimizer so that the former one can be done firstly.
It will makes Conv2D + Squeeze + BiasAdd + Relu pattern be correctly fused.
Fix a fusion pattern on TF backend
Preci
No
> Change the Order of Two Pre-optimizer for TF Backend

- neural_compressor/mix_precision.py
- test/mixed_precision/test_mixed_precision_keras_model.py
bug fix
ILITV-2805: Keras model mix precision convert has graph_def not defined issue.
Keras in Keras out doesn't support mix precision.
For mix precision feature, convert Keras model to saved_model for mix precision handling.
The Keras model mix precision convert issue can be fixed.
No.
> Fix Keras model mix precision convert issue

- examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/main.py
bug fix
ILITV-2799: [3rd release test][spr][ITF2.11.0] inception_v3 failed in tune3.
inception_v3 tuning issue can be fixed on SPR. 
Pre-CI and model test on CLX and SPR.
No.
> Fix inception_v3 tuning issue on SPR with ITF2.11.0

- docs/source/smooth_quant.md
- examples/README.md
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/eval_lambada.py
documentation fix and example
add an example of running sq alpha-tuning on gpt-j model and fix some md typos.
> add gptj alpha-tuning example and fix md typo

- neural_compressor/adaptor/tf_utils/graph_rewriter/int8/freeze_value.py
bug fix
ITEX OOB100 arttrack-coco-multi FBN int8 not freeze value.
All the OOB100 models can be well quantized for FBN.
pre-CI and OOB extension test.
No.
> Fix ITEX OOB100 FBN regression issue

- neural_compressor/mix_precision.py
- neural_compressor/model/model.py
bug fix
ILITV-2398: During studying this issue, I found current design would convert SavedModel to KerasModel on Tensorflow backend, it will cause the quantization fail. We should support KerasModel just on Keras backend.
TFHub saved model can be quantized successfully on stock tensorflow.
Pre-CI and TFHub saved model test.
None.
> Support KerasModel just on Keras backend

- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/smooth_quant.py
- neural_compressor/algorithm/algorithm.py
- test/algorithm/test_smooth_quant.py
support smoothquant only with calibration func, w/o calibration_dataloader.
usage:
```
conf = PostTrainingQuantConfig(
recipes={"smooth_quant": True,
"smooth_quant_args": {'alpha': 'auto', 'folding': False}}
)
fp32_model = Model()
q_model = quantization.fit(
fp32_model,
conf,
calib_func=calib_func,
)
```
> enable smoothquant with calibration func

- test/requirements.txt
DyNAS-T 1.1 has OFA dependency that causes issues when used with Torch 2.0. DyNAS-T 1.2 replaces OFA dependency with a built-in OFA-related code that has a fix addressing this issue.
Signed-off-by: Maciej Szankin <maciej.szankin@intel.com>
> Update DyNAS-T to 1.2

- neural_compressor/adaptor/tf_utils/graph_util.py
bug fix
ILITV-2850: [regression][ITF2.11.0]TF OOB DynamicMemory quantize failed
gen_valid_sampling_log has an issue of calculate final result, the step size is 9. It must be even for min and max.
The OOB DynamicMemory model can be quantized successfully.
Pre-CI and OOB extension test.
No.
> Fix OOB DynamicMemory model quantize issue

- neural_compressor/adaptor/tf_utils/transform_graph/rerange_quantized_concat.py
bug fix
ILITV-2735: Tensorflow-mobilenetv3, OverflowError: cannot convert float infinity to integer
When strategy trigger 5th time tuning for MobileNet-V3 for test purpose, the freezed min and max value are both 0 of one Conv2D. It caused the scales value become float infinity since the scales value is calculated from the freezed min and max value.
The MobileNet-V3 tuning will not crash.
No.
> Fix MobileNet-V3 bias convert to int32 OverflowError issue

- examples/keras/image_recognition/inception_resnet_v2/quantization/ptq/main.py
- examples/keras/image_recognition/inception_v3/quantization/ptq/main.py
- examples/keras/image_recognition/mobilenet_v2/quantization/ptq/main.py
- examples/keras/image_recognition/resnet101/quantization/ptq/main.py
- examples/keras/image_recognition/resnetv2_101/quantization/ptq/main.py
- examples/keras/image_recognition/resnetv2_50/quantization/ptq/main.py
- examples/keras/image_recognition/xception/quantization/ptq/main.py
- examples/tensorflow/semantic_image_segmentation/3dunet-mlperf/quantization/ptq/run_accuracy.py
bug fix
Clean incorrect usage of fit for Keras examples
The quantization fit API usage is correct for Keras examples.
No.
> Clean incorrect usage of fit for Keras examples

- neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
- test/pruning_2.x/test_auto_excluding_classifier.py
Bugfix.
Please refer to [this ticket](https://jira.devtools.intel.com/browse/ILITV-2888)
Fix a bug for excluding classifier head (does not have gradient) during pruning. 
Examples run without classifier pruning bugs
PreCI
None
> Fix bugs when automatically exclude classifier heads in pruning.

- neural_compressor/adaptor/pytorch.py
- test/ipex/test_adaptor_ipex.py
bug fix
We cannot fallback op_type, like add&add, before, but can get it in stats table, so fix it.
BTW, add a warning for SmoothQuant mixing bf16.
ipex op_type name is the same as stats table op_type name. UT pass
local test
> Unify ipex fallback op_type with stats table

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/quantization.py
- test/strategy/test_mse_v2_2.x.py
feature
Support msev2 for onnxrt adaptor
onnxrt adaptor supports msev2 strategy
how to reproduce the test (including hardware information)pre-ci, extension test
no
> Support msev2 for onnxrt adaptor

- neural_compressor/adaptor/tf_utils/graph_rewriter/onnx/onnx_graph.py
bug fix 
ILITV-2909: TF2ONNX ssd_mobilenet_v1 failed due to 'NoneType' object has no attribute 'get_tensor_value'
Tensorflow ssd_mobilenet_v1 int8 model can be exported to onnx int8 model.
Pre-CI and ssd_mobilenet_v1 model export test.
None.
> Fix TF2ONNX ssd_mobilenet_v1 failed to export int8 issue

- examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/main.py
bug fix
ILITV-2908: TF2ONNX vgg16 failed due to 'Metric' object has no attribute 'update'
This issue is caused by Metric change, needs to adapt it.
TF2ONNX vgg16 can be done successfully.
Pre-CI and TF2ONNX example test.
No.
> Fix TF2ONNX vgg16 failed due to Metric change

- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/model_wrapper.py
- test/algorithm/test_smooth_quant.py
to enable t5 series smooth quant.
to avoid inference failed. https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L318
```
-> isinstance(self.wo.weight, torch.Tensor)
(Pdb) self.wo.weight
*** AttributeError: 'SQLinearWrapper' object has no attribute 'weight'
(Pdb) self.wo
SQLinearWrapper(
  (sq_linear): Linear(in_features=2816, out_features=1024, bias=False)
)
```
> Add weight attribute to SQLinearWrapper class

- neural_compressor/adaptor/pytorch.py
bug fix
Ipex tune will fallback all tuned ops, not only the selected one. fix it.
The accu/perf of manual fallback is the same as tuned.
local test
N/A
> fix fallback bug in ipex tune

- neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
bug fix
[ILITV-2913](https://jira.devtools.intel.com/browse/ILITV-2913): [ITEX][INT8] Quantize/ Dequantize before BN should be s8, rather than u8
The Quantize/ Dequantize before BN change to s8.
Local test icv-emotions-recognition-0002 model, pre-CI and OOB extension test.
No.
> Fix ITEX Quantize/ Dequantize before BN u8 issue

- examples/tensorflow/nlp/transformer_lt_mlperf/quantization/ptq/run_inference.py
bug fix
The transformer_lt mlperf fp32 model has two outputs, but the quantized int8 model only has one output.
The quantized int8 model has two outputs 'model/Transformer/strided_slice_15', 'model/Transformer/strided_slice_16'
transformer_lt mlperf model test, pre-CI and extension test.
No.
> Fix transformer_lt mlperf model two outputs issue

- neural_compressor/adaptor/pytorch.py
- test/ipex/test_adaptor_ipex.py
Support dictionary inputs for IPEX quantization 
No API changed
Support dictionary inputs for IPEX quantization, since IPEX had support it in master branch.
Quantize model  successfully with IPEX backend and dictionary inputs.
UT tested
IPEX commit ID: 2.1.0+gite5b169e
> Support dictionary inputs for IPEX quantization

- neural_compressor/config.py
- test/mixed_precision/test_mixed_precision.py
feature: add op name/type dict option to `MixPrecisionConfig` api, the request from [How to ignore custom layer during quantization · Issue #953 · intel/neural-compressor (github.com)](https://github.com/intel/neural-compressor/issues/953)
set the op to fp32 datatype when mixprecision quantization
usage:
```
op_name_dict = {"fc":{
"activation": {"dtype": ["fp32"]},
"weight": {"dtype": ["fp32"]},
}
}
conf = MixedPrecisionConfig(op_name_dict=op_name_dict)
output_model = mix_precision.fit(
model,
conf,
eval_func=eval,
)
op_type_dict = {"Linear":{
"activation": {"dtype": ["fp32"]},
"weight": {"dtype": ["fp32"]},
}
}
conf = MixedPrecisionConfig(op_type_dict=op_type_dict)
output_model = mix_precision.fit(
model,
conf,
eval_func=eval,
)
```
CI pass
CI & local test
No
> Support mixed precision op name/type dict option

- README.md
- docs/source/CODE_OF_CONDUCT.md
- docs/source/CONTRIBUTING.md
- docs/source/releases_info.md
Documentation change
This pull request implements changes to the documentation by updating email references with `mailto` links. The specific modifications include: 
- Adding `mailto` link on the [release info page](https://intel.github.io/neural-compressor/latest/docs/source/releases_info.html). 
- Adding `mailto` link on the [welcoming page](https://intel.github.io/neural-compressor/latest/docs/source/Welcome.html#research-collaborations).
- Adding `mailto` link on the [Code of Conduct page](https://intel.github.io/neural-compressor/latest/docs/source/Welcome.html#research-collaborations). 
- Fixing a broken email link on the [Contribution page](https://intel.github.io/neural-compressor/latest/docs/source/CONTRIBUTING.html#support).
Links are pointing to emails.
Checking the above …
> Update email display to mailto links in markdown files

- examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/requirements.txt
bug fix
limit transformers version <= 4.29.2 for TF examples due to transformers 4.30.0 compatible issue
example test pass
extension test
No
> limit transformers version for TF examples due to compatible issue

- examples/onnxrt/nlp/bert/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/bert/quantization/ptq_static/main.py
- examples/onnxrt/nlp/distilbert/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/distilbert/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/requirements.txt
- examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/requirements.txt
- examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/main.py
- examples/onnxrt/nlp/mobilebert/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/mobilebert/quantization/ptq_static/main.py
- examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/gpt2.py
- examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/roberta/quantization/ptq_static/main.py
- neural_compressor/adaptor/ox_utils/operators/gather.py
- neural_compressor/adaptor/ox_utils/quantizer.py
- neural_compressor/model/onnx_model.py
bug fix
API not change
1. onnxruntime 1.14.1 optimize failed in some NLP models. The bug is fixed in https://github.com/microsoft/onnxruntime/issues/14959. In this PR, the optimized model will be checked for validity. If the optimized model is invalid, optimizer will be skipped.
2. refine block_wise info query in ORT.
3. refine int8 tensor recalculation in Gather op.
- [ILITV-2928](https://jira.devtools.intel.com/browse/ILITV-2928) [release test v2.2rc1][onnxrt v1.14.1] hf_deberta/hf_deberta_dynamic can't reach accuracy goal
- [ILITV-2927](https://jira.devtools.intel.com/browse/ILITV-2927) [release test v2.2rc1][onnxrt v1.14.1] hf_layoutlmv3 can't reach accuracy goal
pass extension test for onnx NLP models
extension test 
no
> Fix bug in ONNXRT NLP example for onnxruntime1.14.1

- neural_compressor/adaptor/torch_utils/smooth_quant.py
Bug fix
When Smoothquant is on and folding is True, model tracing for obtaining quantizable ops does not work when the input is a dictionary.
Smoothquant will work when the input to the model is dictionary.
> Fixed trace issue when input is dictionary

- examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
- neural_compressor/adaptor/torch_utils/mixed_precision.py
- neural_compressor/config.py
- neural_compressor/strategy/auto_mixed_precision.py
- neural_compressor/strategy/strategy.py
- test/ipex/test_adaptor_ipex.py
feature: 
1. add `example_inputs` for `MixPrecisionConfig` api.
2. improve ipex backend mix precision quantization, use `ipex.optimize()` to get bfloat16 model and make it to torchscript mode.
3. accept `tuple` and `dict` type as example_inputs to make torchscript model for mixed precision.
4. improve QA ipex example（support bert and distilbert）to make mixed precision now.
usage:
```
conf = MixedPrecisionConfig(backend="ipex", example_inputs=torch.randn(1, 3, 224, 224))
output_model = mix_precision.fit(
self.pt_model,
conf,
eval_func=eval,  #optional
)
```
`example_inputs` is necessary for ipex mixed precision quantization.
> Support ipex mixed precision

- neural_compressor/adaptor/torch_utils/smooth_quant.py
bug fix
detail description:
fix the skip-connection bugs when set folding=True.  When an op(e.g layernorm) outputs to multiple modules and one of them is not absorbable, this op should not be transformed by smoothquant. This pr fixes one scenario of this issue; solution of other scenarios is WIP.
no behavior expected to trigger by this PR 
do alpha=auto smoothquant on opt350m. fp32 acc remains unchanged after performing sq.
no
> fix skipconnection bugs when folding=true

- neural_compressor/adaptor/pytorch.py
Copy the model for smoothquant in quantization  
No API changed
The smoothquant method needs a deep copy of the model in the process of getting quantizable ops, so we also add a deep copy in the quantization process.
Quantize flan-t5 successfully with smoothquant. 
Local tested
> Copy the model for smoothquant in quantization

- neural_compressor/adaptor/torch_utils/smooth_quant.py
root cause: `torch.isclose()` doesn't support `torch.isclose(tuple(),tuple())`.
check equal out_pre_sq and out_post_sq is necessary, we will improve the calculate method later, welcome to raise a PR if you have a good idea @maktukmak , this PR just provide the workaround for output style is tuple(tuple()).
> Improve sq equal check with out_pre_sq and out_post_sq

- neural_compressor/adaptor/pytorch.py
This reverts commit ca10b33dcc0c6932b2c9ce843d67d2cddf5ac82f.
No API changed
For performance_only, we don't copy the model in the quantization process, but in the process of get_quantizable_ops, it need to improve the behavior in IPEX.
> Revert "Copy the model for smoothquant in quantization (#1001)"

- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/smooth_quant.py
- test/algorithm/test_smooth_quant_onnx.py
bug fix
opt-125m requires large atol when checking output, to avoid this error again, we remove recover func and use log instead.
UT pass
local test
N/A
> remove recover when sq check failed

- neural_compressor/adaptor/pytorch.py
bug fix
root cause: when `folding=True` and `eval_func` doesn't provide, the SQ input is ipex prepared model, it used `aten::alias` wrap the op and cause the `linear` and `conv` not to be recognized.
improve: add the deepcopy for this condition, because `folding=False` also need `deepcopy`, so remove the ipex version limitation.
remaining:
there is a remaining curious issue in UT `python test_smooth_quant.py TestSqLinearOpFuse.test_sq_quant_ipex`, for actual models(such as bloom, llama), `tmp_model` and `model` should use the same address. But the previous ut pass, the reason shows `tmp_model=model` create 2 address for `tmp_model` and `model` when get_quantizable ops, I think may be due to the small size, please root cause @xin3he 
the expected behavior that triggered …
> add deepcopy for SQ folding=True

- neural_compressor/adaptor/tf_utils/smooth_quant_calibration.py
Bug fix
transformer_lt has unsupported output nodes that need to be excluded when doing smooth calibration
transformer_lt/transformer_lt_mlperf test pass
[ILITV-2936](https://jira.devtools.intel.com/browse/ILITV-2936)
None
> Fix transformer_lt retval already set issue

- neural_compressor/strategy/bayesian.py
bug fix
API no change
Fixed reshape issue for Bayesian strategy.
Replace reshape(1, -1) with flatten().
no
> Fix reshape issue for Bayesian strategy

- examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/requirements.txt
- examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py
bug fix
The slimed model cannot be loaded using the form_pertrain() method. In order to solve the situation that the model is not compatible with the downstream examples, consider directly converting the slimed_model to jit_model.
> Adding jit trace to llm example

- neural_compressor/adaptor/torch_utils/util.py
remove the invalid print.
the pre_op_out may not in the q_op_info, it will cause not find the pre_op, we don't need to modify the pre_op_output optype for the condtion.
the print cause some confuse, so remove it.
> remove invalid print

- test/strategy/test_distributed_tuning.py
UT bug fix  
API changed or not: none
- The "use_distributed_tuning" field is no longer used in the codebase and has become obsolete. It was removed from UT in this PR.
- Added distributed debugging test output to enhance the debugging process. This allows for better analysis and identification of issues during testing.
Only test in an environment with mpi4py installed.
Pre-CI & Offline Test
none
> Remove distributed tuning flag from Unit Test

- neural_compressor/adaptor/tensorflow.py
- neural_compressor/adaptor/tensorflow.yaml
- neural_compressor/adaptor/tf_utils/graph_converter.py
- neural_compressor/adaptor/tf_utils/graph_converter_without_calib.py
- neural_compressor/adaptor/tf_utils/graph_rewriter/generic/convert_add_to_biasadd.py
- neural_compressor/adaptor/tf_utils/util.py
- test/tfnewapi/test_tensorflow_graph_conv_fusion.py
bug fix
Support new spr-base version 2.11.0202323;
Update the max support tensorflow version to 2.12.0;
Fix version check issue on SPR for '1.15.0-up3'.
New spr-base version supported and version issue fixed.
UT and pre-CI test.
No.
> Support new spr-base version and fix version check issue

- neural_compressor/adaptor/keras.yaml
Bug fix
Remove unsupported layers, such as GRU, LSTM.
That models having such layers will not meet an error when applying mix-precision.
PreCI
No
> Update the List of Supported Layers for Keras Mix-precision

- neural_compressor/experimental/strategy/strategy.py
- neural_compressor/strategy/auto.py
- neural_compressor/strategy/strategy.py
- test/strategy/test_quant_level.py
Enhancement
- Enhance the exit policy
Before: quant_level = auto & max_trials = 1 & ACC not meet at the first trial -> O0
After: quant_level = auto & max_trials = 1 & ACC not meet at the first trial -> return None
- Fixed the batch_size is None
For accelerate's DataLoaderShard, use `total_batch_size` instead of `batch_size`
Pre-CI and Ext-test
None
> Enhance strategy exit policy

- conda_meta/basic/meta.yaml
- conda_meta/neural_insights/meta.yaml
- conda_meta/neural_solution/meta.yaml
- neural_compressor/version.py
- neural_solution/version.py
- requirements.txt
others
1. replace opencv with opencv-python-headless
2. enhance pycocotools installation
3. bump release version into v2.2.1
To avoid issue 'ImportError: libGL.so.1' cased by opencv-python. Support for ONNXRT integration https://github.com/microsoft/onnxruntime/pull/16288 
CI and minimal release test. 
Yes, but they build from the some source code, so no need to update the BoM.
> replace opencv with opencv-python-headless

- neural_compressor/adaptor/tf_utils/graph_converter.py
- neural_compressor/metric/metric.py
feature & bug fix
The TopK metric will check shape before updating predictions and labels.
While doing the check, a tuple or list with tf.Tensor inside it will be expanded to unexpected dimension.
Therefore, we need to extract contents from tf.Tensor before applying the check.
Labels with tf.Tensor will reports no error when checking shape.
PreCI
No
> Support tf.Tensor as Labels for TopK Metric

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/adaptor/ox_utils/quantizer.py
- test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
bug fix
API not change
Fix bug in ONNXRT adapter where _rename_node function fails with model size > 2 GB
_rename_node function in ONNXRT adapter can handle ONNX models with size > 2 GB
CI test
no
> Fix bug in ONNXRT adapter where _rename_node function fails with model size > 2 GB

- neural_compressor/strategy/utils/constant.py
- test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
bug fix
API not change
```
config = PostTrainingQuantConfig(backend='onnxrt_cuda_ep', device='gpu', quant_level=1)
q_model = quantization.fit(model, config, calib_dataloader=dataloader)
```
failed with error:
Fix the failure
onnx bert_base_MRPC example with CUDA EP
No
> Fix precision tuning bug for ONNX CUDA EP

- examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
Bug fix
The API of 'tf2onnx.tfonnx.fold_constants_using_tf' is changed after 1.10.1. We need to use tf2onnx>=1.10.1.
Fix Examples
Extension Test
No
> Fix Regression of TF2ONNX Examples

- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/smooth_quant.py
- test/algorithm/test_smooth_quant.py
bug fix
unifiy weight_amax for modules same input, or qkv will get different scale and got wrong accuracy.
facebook/opt125m gets correct accuracy on ipex2.1, folding=False.
local test
> [SQ bug] unifiy weight_amax for modules same input

- .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
- docs/source/smooth_quant.md
- docs/source/tuning_strategies.md
Documentation update
- Update the introduction
- Clarify the fwk capability and `op_name_dict`/`op_type_dict` 
- Add sq'alpha tuning doc
Pre-CI
None
> Update the strategy docs

- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/smooth_quant.py
- test/algorithm/test_smooth_quant.py
bug fix
when folding=False and QKV is not fully converted to SQLinear.
UT pass
local test
> fix bug in TorchSmoothQuant

- examples/README.md
- examples/notebook/onnxruntime/Quick_Started_Notebook_of_INC_for_ONNXRuntime.ipynb
documentation
API not change
Add the link of quick started notebook to examples README.md
Users can jump to the link of quick started notebook through examples README.md
CI test
no
> Add quick started notebook to examples README.md

- examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
bug fix
tf2onnx examples failed because of conflicts of libraries.
Update limitation to requirements.txt to avoid this.
fix tf2onnx models
Extension test
No
> Update Version Limitation for tf2onnx Examples

- docs/source/releases_info.md
- neural_compressor/adaptor/keras_utils/conv2d.py
- neural_compressor/adaptor/keras_utils/depthwise_conv2d.py
- neural_compressor/adaptor/keras_utils/separable_conv2d.py
bug fix
Keras API changed for tf 2.13.0, adapt the API for different tensorflow versions.
The Keras model can be quantized successfully for TF 2.13.0 and other TF versions.
Potential Risk:
There is an open issue for Keras 2.13.0.
https://github.com/tensorflow/tensorflow/issues/61211
raise ValueError(
ValueError: Requested the deserialization of a Lambda layer with a Python `lambda` inside it. This carries a potential risk of arbitrary code execution and thus it is disallowed by default. If you trust the source of the saved model, you can pass `safe_mode=False` to the loading function in order to allow Lambda layer loading.
2023-08-23 03:37:46 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.
UT, example test …
> Fix tf2.13.0 Keras model quantization failed issue

- examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/run_benchmark.sh
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/run_quant.sh
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_benchmark.sh
- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_quant.sh
bug fix
API bot change
Fix bugs:
1. ONNXRT hf question answering examples failed with `dataclasses.FrozenInstanceError: cannot assign to field do_eval`
2. ONNXRT hf language modeling examples failed with `AttributeError: 'Namespace' object has no attribute 'no_cuda'`
fix bugs
extension test
no
> Fix bugs in ONNXRT hf examples

- .azure-pipelines/ut-basic-no-cover.yml
- .azure-pipelines/ut-basic.yml
- examples/tensorflow/nlp/distilbert_base/quantization/ptq/requirements.txt
- neural_compressor/benchmark.py
bug fix
CI jobs title update and CVE fix 
CI pass 
CI
No
> CI jobs title update and CVE fix 

- neural_compressor/adaptor/ox_utils/weight_only.py
enhancement
API not change
In ONNXRT `awq_quantize` and `gptq_quantize` functions,  set `n_sample=-1` to calibrate all samples. 
`n_sample=-1`  will be used in INT4 enabling to ONNXRuntime.
CI test, local test
no
> Support all calibration samples for ONNXRT weight only

- examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
bug fix
Remove version limits for tf2onnx examples because the dependency conflicts has been solved in the newest version.
Run tf2onnx examples with newest version of dependencies.
Extension test
NA
> Remove Version Limits for tf2oonx Examples

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/model/model.py
- test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
bug fix
API not change
1. If backend is not TensorrtExecutionProvider, set `os.environ["ORT_TENSORRT_UNAVAILABLE"] = "1"` to do not load TensorRT
2. Force provider to `CPUExecutionProvider` when get model framework and detect domain to avoid warning like `Failed to create  XXXExecutionProvider`
CI test and extension test of CUDA EP
no
> Enhance ONNXRT backend setting

- neural_compressor/adaptor/pytorch.py
bug fix
- error log
neural_compressor/adaptor/pytorch.py", line 920, in model_calibration
if hasattr(dataloader, "batch_size") and calib_sampling_size % dataloader.batch_size != 0:
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'
- when dataloader.batch_size = None, operand `%` will report error.
Pre-CI
None
> Fix pytorch dataloader batchsize issue

- examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/README.md
- examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/main.py
Use tensorflow as the default backend for this example instead of ITEX.
PreCI, Extension.
No
> Use TF as default Backend for ViT Example

- neural_compressor/adaptor/tf_utils/smooth_quant_calibration.py
bug fix
tensor.shape.dims is None and check_shape cause an issue
check_shape return True when tensor.shape.dims is None
recipes={"smooth_quant": True, "smooth_quant_args": {'alpha': 0.5}} in PTQConfig, test bert_base_mrpc 
None
> Fix bert_base_mrpc smoothquant check_shape issue

- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/gptq.py
- neural_compressor/adaptor/torch_utils/weight_only.py
- test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
- test/quantization/test_weight_only_quantization.py
enhance
- move seqlen attribute to config. (Done)
- unified the dataloader's form with unfixed/fixed sequence length. (Done)
Normal functions in modified uts
PreCI
None
> Unify GPTQ dataloader with fixed/unfixed length data

- test/adaptor/tensorflow_adaptor/test_bf16_convert.py
bug fix
BF16 convert on stock tensorflow only support ['Conv2D', 'Conv3D', 'MatMul', 'BatchMatMul', 'MaxPool', 'MaxPool3D', 'AvgPool', 'AvgPool3D', 'DepthwiseConv2dNative'], no 'Log' op. 'Log' op can only be converted to bf16 on SPR based tensorflow. Therefore, check for 'Log' op is skipped here. In addition, there should be no cast here.
UT pass
trigger this ut
None
> Fix UT for stock TF adaptor bf16 convert

- examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/README.md
- examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/main.py
- examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/prepare_model.py
- examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/requirements.txt
- examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/README.md
- examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/prepare_model.py
- examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/requirements.txt
Example
This PR is a follow-up to [PR 1221](https://github.com/intel/neural-compressor/pull/1121).
We will not be able to upstream this model because of the licensing restrictions. Users need to fine-tune it by themselves.
Once we have the fine-tuned model, the `prepare_model.py`  can be tested manually.
Pre-CI and Ext test
None
> Align the model preparation for Codebert

- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
- neural_compressor/adaptor/torch_utils/gptq.py
bug fix
ChatGLM's source code, whose forwarding functions take several positional arguments, besides fixed "hidden_states". However, current GPTQ API only collects keyword arguments automatically. Thus, this pr is to add positional arguments automatic collection. 
Execute GPTQ quantization on ChatGLM2-6B automatically. 
PreCI
no
> Support GPTQ on ChatGLM2-6B

- neural_compressor/adaptor/pytorch.py
bug fix
[model with Conv failed in woq mode](https://github.com/intel/neural-compressor/issues/1100)
It's a history issue. we plan to support Conv in woq mode before, but finally decide to skip Conv.
> remove Conv2d in white list in WOQ adaptor

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/adaptor/ox_utils/util.py
- neural_compressor/model/onnx_model.py
- test/model/test_onnx_model.py
feature
API not change
Reduce memory consumption in ONNXRT adaptor:
- Delete unnecessry InferenceSession
- Refine check function for large models 
local test
no
> Reduce memory consumption in ONNXRT adaptor

- neural_compressor/utils/utility.py
Bug fix
Some Windows users may install w64devkit that and set path to its /bin will have `find` command path as `<path to w64devkit-xxx>/w64devkit/bin/find.exe`, and it does not accept -C as a parameter.
More robust by providing the full path to `find`
Related PR https://github.com/intel/intel-extension-for-transformers/pull/377
```
from intel_extension_for_transformers.transformers import AutoModel, WeightOnlyQuantConfig
```
None
> Fix find command on Windows with full path

- examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/main.py
bug fix
Three Conv2D Ops is changed from qint8 to quint8 after this commit: https://github.com/intel/neural-compressor/commit/7fb76c450b95c19d0eba1b52d0dac8633e0e2319. 
Then, the accuracy dropped a lot.
This PR is to fallback them to fp32 so that the accuracy will be correct.
Maybe we should consider adding 'qint8' or quint8 for op_wise_config.
Fix bug and accuracy.
No
> Fix Regression of ssd_resnet50_v1 Example for TF New API

- examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/requirements.txt
bug fix
fix TF 2.13 incompatible keras engine invocation with older transformers
SQ example pass
Baseline | Tune 1 result
0.6389   |    0.6342
SQ test
None
> fix TF 2.13 incompatible keras engine invocation with older transformers

- examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/main.py
- examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/main.py
- neural_compressor/adaptor/tf_utils/graph_converter.py
- neural_compressor/adaptor/tf_utils/graph_converter_without_calib.py
bug fix
Fix importing issue of object detection models caused by TF2.14 API change.
Extension test
No
> Adapt Example for TF2.14 AutoTrackable API Change

- neural_compressor/adaptor/torch_utils/smooth_quant.py
- test/algorithm/test_smooth_quant.py
bug fix
The auto alpha cannot handle multi formats of calib_dataloader and batch_size != 1 situation.
fix it
https://jira.devtools.intel.com/browse/ILITV-3173
UT pass
local test
> fix bug in smoothquant for auto alpha

- .azure-pipelines/scripts/ut/env_setup.sh
- .azure-pipelines/scripts/ut/run_basic_api.sh
- .azure-pipelines/scripts/ut/run_basic_others.sh
- test/requirements.txt
This version of DyNAS-T updates OFA super-network registry with new URLs (old ones are no longer valid) and mostly focuses on code improvements and documentation.
Tests previously disabled due to OFA URL change are reinstated.
> Update DyNAS-T to 1.6

- neural_insights/README.md
- neural_insights/docs/pytorch_nlp_cli_mode.md
- neural_insights/docs/source/pytorch_nlp_cli_mode.md
Documentation
Documentation with example of tensor dump for tensor dump using Neural Insights CLI.
User should be able to dump tensor using this instruction.
Manual execution of commands included in readme.
None
> Add example of PyTorch model tensor dump with Neural Insights

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/adaptor/ox_utils/weight_only.py
feature
Support MatMulFpQ4 for onnxruntime 1.16.0
> Support MatMulFpQ4 for onnxruntime 1.16.0

- README.md
- docs/source/publication_list.md
documentation 
1. update publication  
2. add discord channel link    
3. fix some hyper link issue caused by github logical update
https://github.com/orgs/community/discussions/16925 
NA
CI
No
> publication update and hyper link fix

- examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/requirements.txt
Bug fix
Fix tensorflow and transformers versions for gpt2-medium
gpt2-medium with the latest version of transformers get the input signature <input_ids, attention_mask, token_type_ids> but the token_type_ids should not occur.
Currently the only way to deal with it is to use old version transformers.
python main.py --model_name_or_path gpt2-medium
None
> Fix tensorflow and transformers versions

- examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
- examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
- examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/README.md
- examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py
- examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt
bug fix
API not change
1. Update ITREX version in ONNXRT WOQ example since ITREX v1.2 was released.
2. Fix accuracy tuning failed of huggingface question answering models
2.1 Update outdated models on test machines (exported with torch1.13 -> exported with torch2.0)
2.2 Update PostTrainingQuantConfig setting
CI, extension test
no
> Update ITREX version in ONNXRT WOQ example and fix bugs in hf models

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/adaptor/ox_utils/weight_only.py
feature
Support MatMulNBit op for ort 1.17
> Support MatMulNBit op for ort 1.17

- setup.cfg
- setup.py
others
Refine release binary build for 3.0 API, install cmd update as following:   
- `pip install neural-compressor`, install 2.x API.   
- `pip install neural-compressor[tf]`, install 2.x API + 3.x TensorFlow API. 
- `pip install neural-compressor[pt]`, install 2.x API + 3.x PyTorch API. 
- `pip install neural-compressor[ort]`, install 2.x API + 3.x ONNXRT API. 
- `conda install neural-compressor -c conda-forge -c intel`, one binary for all APIs. 
- `python setup.py install`, install 2.x API. 
- `python setup.py tf install`, install 3.x TensorFlow API only. 
- `python setup.py pt install`, install 3.x PyTorch API only. 
- `python setup.py ort install`, install 3.x ONNXRT API only. 
This PR won't impact current CI and 2.x API build logical, so CI should pass. 
Local build and …
> refine release binary build for 3.0 API

- neural_compressor/adaptor/torch_utils/model_wrapper.py
- neural_compressor/adaptor/torch_utils/smooth_quant.py
bug fix, related to latest torch modification.
[NLPTOOLKIU-861](https://jira.devtools.intel.com/browse/NLPTOOLKIU-861)
Fake quantized model for smoothquant on torch backend cannot be reload correctly.
```shell
(Pdb) m = torch.nn.quantized.Quantize(1, 0, dtype=torch.uint8)    
(Pdb) m.scale.dtype                                                    
torch.int64  # cannot load float scale
(Pdb) m = torch.nn.quantized.Quantize(1.0, 0, dtype=torch.uint8)       
(Pdb) m.scale.dtype                 
torch.float32
```
reload model accuracy recover
local tested
> fix bug in sq torch backend

- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
- neural_compressor/adaptor/torch_utils/gptq.py
Enhancement
However, Baichuan, chatglm2-6b's evaluation currently not supported. \
Some unique characteristics for chatglm-6b and phi-1: 
- chatglm-6b **requires some specific token id (bos_token_id = 1300xx, etc.)** for successful inference. Thus, direct truncation on tokenized data is not suitable for this model. However, when untruncated sequences are input, the function runs properly.
- phi-1's torch.nn.Sequential object does not only contain the transformer stack but also embedding layers and final heads. Thus, I add a temporary function to trace the proper layers that can be quantized under GPTQ context.
> Support wider range of models, especially CHN LLMs.

- neural_compressor/adaptor/onnxrt.yaml
- neural_compressor/adaptor/ox_utils/operators/direct_q8.py
- neural_compressor/adaptor/ox_utils/operators/gather.py
- test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
feature
API not change
Support more ONNX INT8 ops: 
- GatherElements
- GatherND
- Tile
- CenterCropPad (requires opset version 18)
CI, extension test
no
> Support more ONNX INT8 ops 

- README.md
- The installation + FAQ links are broken, and do not work. This PR fixes this.
> Fix broken installation + faq links

- neural_compressor/adaptor/pytorch_cpu.yaml
bug fix
to support falcon, falcon model's linear is named FalconLinear, not Linear.
add default for WOQ to support custom Linear
> add default for WOQ to support custom Linear

- neural_compressor/adaptor/torch_utils/bf16_convert.py
- neural_compressor/config.py
- neural_compressor/strategy/strategy.py
the current PyTorch MixedPrecision is fx graph model, change it to eager mode.
> Support PyTorch eager mode BF16 MixedPrecision

- examples/.config/model_params_tensorflow.json
- examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/requirements.txt
Version fix
The new release of Transformers  fixes the signature bug, so we do not need to limit the version for gpt-medium
gpt2-medium quantization SQ passed
gpt2-medium SQ test
None
> remove unnecessary version limitation

- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/weight_only.py
- test/quantization/test_weight_only_quantization.py
feature
No API changed
Support fp16 model to weight-only quantization for PyTorch framework.
Quantization fp16 model successfully.
local tested
> Support fp16 model to weight-only quantization for PyTorch framework

- neural_compressor/adaptor/onnxrt.py
- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/tensorflow.py
- neural_compressor/adaptor/torch_utils/smooth_quant.py
- neural_compressor/algorithm/smooth_quant.py
- neural_compressor/strategy/strategy.py
- test/algorithm/test_smooth_quant.py
code update
make weight_clipping a default_on option when calculating scales for quantization
> [SmoothQuant] make weight_clipping a default_on option

- neural_compressor/adaptor/torch_utils/util.py
remove the invalid print
```
2023-11-15 19:40:40 [INFO] []
2023-11-15 19:40:40 [INFO] Pass query framework capability elapsed time: 19496.57 ms
2023-11-15 19:40:40 [INFO] Do not evaluate the baseline and quantize the model with default configuration.
2023-11-15 19:40:40 [INFO] Quantize the model with default config.
/home/changwa1/itrex/examples/huggingface/pytorch/text-generation/quantization/nc_workspace/2023-11-15_19-29-59/ipex_config_tmp.json
/home/changwa1/anaconda3/envs/rc4/lib/python3.9/site-packages/intel_extension_for_pytorch/quantization/_quantization_state_utils.py:454: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the …
```
> remove the ipex adaptor invalid print

- neural_compressor/utils/pytorch.py
- test/algorithm/test_smooth_quant.py
feature
support for restoring ipex quantized model from json
Pre-CI
None
> support for restoring ipex model from json

- neural_compressor/benchmark.py
- neural_compressor/utils/utility.py
Enhancement
add quantization support on MacOS, which will fix
https://github.com/intel/neural-compressor/issues/1278 and https://github.com/intel/neural-compressor/issues/1275
add quantization support on MacOS
Run the example neural-compressor/examples/onnxrt/nlp/bert/quantization/ptq_static
on a Apple M2 Pro
None
> add quantization support on MacOS

- docs/source/smooth_quant.md
documentation
In the QuantizationFundamentals section of the smooth_quant.md file, there are several python typos/bugs (e.g. wrong argument names). They are fixed in this PR.
The smooth_quant.md file will be updated.
Local test
No dependency change
> fix python script typos in smooth_quant.md

- neural_compressor/adaptor/pytorch.py
ipex 2.1.0 requests observer object, but ipex 2.1.1 requests observer class.
ipex 2.1.0 code
https://github.com/intel-innersource/frameworks.ai.pytorch.ipex-cpu/blob/v2.1.0%2Bcpu-rc4/intel_extension_for_pytorch/quantization/_smooth_quant.py#L85
ipex 2.1.1 code
https://github.com/intel-innersource/frameworks.ai.pytorch.ipex-cpu/blob/v2.1.100%2Bcpu-rc0/intel_extension_for_pytorch/quantization/_smooth_quant.py#L75
> Fix smoothquant minmax observer init

- neural_compressor/adaptor/tensorflow.py
- neural_compressor/adaptor/tf_utils/smooth_quant_calibration.py
Remove unnecessary configs for TF smooth quantization.
Remove tune_cfg and black_nodes which are useless in TF smooth quantization.
PreCI
No
> Remove unnecessary configs for TF Smooth Quantization

- neural_compressor/model/tensorflow_model.py
bug fix
Remove version check for tf.estimator because it has been added back in tf2.14&tf2.15.
the bug of bert_base_mrpc will be fixed.
Extension test, PreCI
No
> Remove Version Check for tf.estimator

- neural_compressor/adaptor/torch_utils/smooth_quant.py
bug fix  
No API changed
Fixed inputs error for sq, if inputs is tuple, we need set inputs to specified device and return a tuple, but it will return list type before.
Quantize T5 model with ipex sq successfully. 
Local tested
> Fixed inputs error for smoothquant example_inputs

- neural_compressor/strategy/conservative.py
Bug fix 
The issue was caused by incorrectly judging `mul` as `matmul`.
[log](https://inteltf-jenk.sh.intel.com/job/intel-lpot-validation-windows/2094/artifact/onnxrt-ssd_mobilenet_v1-windows-meteor_lake-tune.log)
Pre-CI, EXT
None
> Fixed the type-matching check

- docs/source/tuning_strategies.md
- neural_compressor/adaptor/ox_utils/util.py
- neural_compressor/strategy/strategy.py
- test/algorithm/test_smooth_quant.py
- test/algorithm/test_smooth_quant_onnx.py
After trying all alpha values, the sq tuning process will stop early, returning the current best qmodel, even if the current best accuracy does not meet the accuracy criterion.
For example:
```python
alpha = [0.1, 0.5]
acc_baseline = 1
acc_alpha1 = 0.8  # alpha is 0.1
acc_alpha2 = 0.9  # alpha is 0.5
```
Pre-CI
None
> Narrow the tuning space of sq auto-tune

- neural_compressor/adaptor/torch_utils/util.py
- test/ipex/test_adaptor_ipex.py
bug fix
IPEX backend got wrong number of quantizable add ops when detecting. 
Quantizable add ops should be detected in gptj but not in opt model.
```
"q_op_infos": {
"0": {
"op_type": "<method 'add' of 'torch._C._TensorBase' objects>",
"op_type_is_module": false,
"fqn": "",
"input_tensor_infos": [
{
"id": 0,
"orig_dtype": "torch.float32",
"inf_dtype": "torch.float32",
"force_dtype": "torch.float32",
"scale": [
0.007949741557240486
],
"zero_point": [
219
]
},
{
"id": 0,
"orig_dtype": "torch.float32",
"inf_dtype": "torch.float32",
"force_dtype": "torch.float32",
"scale": [
0.007949741557240486
],
"zero_point": [
219
]
}
],
```
local test on models
N/A
> [bug fix] update quantizable add ops detection on IPEX backend

- neural_compressor/adaptor/pytorch.py
https://jira.devtools.intel.com/browse/IPB-2106?filter=-2, the issue is IPEX linear smoothquant observer doesn't work with  model loaded from json.
due to the above issue fixed by IPEX 2.1.100, we should reset the smoothquant linear scale infos after calibration.
> Fix llm model accuracy regression with IPEX 2.1.100

- docs/source/llm_recipes.md
documentation 
fix the recipes link
> fix the recipes link

- neural_compressor/utils/pytorch.py
> Add version condition for IPEX prepare init

- neural_compressor/utils/utility.py
Fix https://github.com/intel/intel-extension-for-transformers/issues/762
`lscpu | grep 'Socket(s)' | cut -d ':' -f 2` may not fetch correct Socket number on non-english system, because `Socket(s)` may be translated to different language, as shown in `https://github.com/intel/intel-extension-for-transformers/issues/762#issuecomment-1873773702`.
What we can do is an alternative `cat /proc/cpuinfo | grep 'physical id' | sort -u | wc -l`, which should be in pure English to fetch.
As above.
Original UT will be enough.
None
> Fix wrong socket number retrieval for non-english system

- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/main.py
- neural_compressor/adaptor/torch_utils/autoround/__init__.py
- neural_compressor/adaptor/torch_utils/autoround/autoround.py
- neural_compressor/adaptor/torch_utils/autoround/export.py
- neural_compressor/adaptor/torch_utils/autoround/model_wrapper.py
- test/adaptor/pytorch_adaptor/test_autoround.py
- test/algorithm/test_autoround.py
> add export funcs for autoround and fix incorrect hype-parameters in example

- neural_compressor/adaptor/torch_utils/model_wrapper.py
user experience enhancement
WeightOnlyLinear keeps self.weight after recover due to recover is too slow.
UT pass
> WeightOnlyLinear keeps self.weight after recover

- examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/README.md
- examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_sparsegpt.py
- examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/scripts/run_llm_sparsegpt.sh
> Change the calibration dataset to pile-10k

- neural_compressor/onnxrt/algorithms/weight_only/algo_entry.py
- neural_compressor/onnxrt/quantization/config.py
- neural_compressor/onnxrt/quantization/quantize.py
- neural_compressor/onnxrt/utils/onnx_model.py
- neural_compressor/onnxrt/utils/utility.py
- test/3x/onnxrt/quantization/weight_only/test_rtn.py
- test/3x/onnxrt/test_config.py
bug fix 
Fix logger import for onnxrt
Fix utils imoprt.
```python
from neural_compressor.common.utilily import RTN
->
from neural_compressor.common.utils import RTN
```
Pre-CI
None
> Fix common import for onnxrt

- neural_coder/extensions/neural_compressor_ext_lab_alibaba/DEVELOP.md
documentation 
remove pip install for neural coder extension, remove the invalid description.
> remove pip install for neural coder extension

- neural_coder/extensions/neural_compressor_ext_vscode/src/extension.ts
security fix: Hardcoded encryption keys can compromise security in a way that is not easy to remedy.
no
rename key to pythonPath
no security warning
no security warning
no
> rename key to pythonPath

- examples/onnxrt/image_recognition/onnx_model_zoo/mnist/quantization/ptq_static/main.py
- examples/tensorflow/nlp/bert_base_mrpc/quantization/ptq/prepare_dataset.py
- neural_compressor/data/datasets/dataset.py
- neural_compressor/experimental/data/datasets/dataset.py
- test/data/test_exp_transformers.py
- test/data/test_transform.py
security issue fix
define the default SSL context
> define the default SSL context

- .azure-pipelines/scripts/ut/3x/collect_log_3x.sh
- neural_compressor/common/__init__.py
- neural_compressor/common/base_config.py
- neural_compressor/common/base_tuning.py
- neural_compressor/common/utils/__init__.py
- neural_compressor/common/utils/logger.py
- neural_compressor/onnxrt/algorithms/weight_only/algo_entry.py
- neural_compressor/onnxrt/quantization/config.py
- neural_compressor/onnxrt/quantization/quantize.py
- neural_compressor/onnxrt/utils/onnx_model.py
- neural_compressor/onnxrt/utils/utility.py
- neural_compressor/tensorflow/algorithms/static_quantize/keras.py
- neural_compressor/tensorflow/quantization/quantize.py
- neural_compressor/torch/algorithms/weight_only_algos.py
- neural_compressor/torch/quantization/autotune.py
- neural_compressor/torch/quantization/layers.py
- neural_compressor/torch/quantization/quantize.py
- neural_compressor/torch/utils/utility.py
- test/3x/onnxrt/quantization/weight_only/test_rtn.py
- test/3x/onnxrt/test_config.py
- test/3x/tensorflow/test_config.py
- test/3x/torch/quantization/weight_only/test_gptq_algo.py
- test/3x/torch/quantization/weight_only/test_rtn.py
- test/3x/torch/test_autotune.py
- test/3x/torch/test_config.py
- test/3x/torch/test_logger.py
- test/3x/torch/test_utils.py
API changed or not:  None
```python
from neural_compressor.common import logger
logger.info("Log info: %s", log_str)
from neural_compressor.common import Logger
from neural_compressor.common.utils import Logger
logger = Logger().get_logger()
logger.info("Log info: %s", log_str)
```
Pre-CI
None
> Unify the `logger` usage

- neural_compressor/common/base_tuning.py
- neural_compressor/torch/quantization/__init__.py
- neural_compressor/torch/quantization/autotune.py
- neural_compressor/torch/quantization/quantize.py
- test/3x/torch/test_autotune.py
feature
API changed or not: add API to get the default set
```python
from neural_compressor.torch.quantization import TuningConfig, autotune, get_rtn_double_quant_config_set
def eval_acc_fn(model) -> float:
...
custom_tune_config = TuningConfig(config_set=get_rtn_double_quant_config_set())
q_model = autotune(model=build_simple_torch_model(), tune_config=custom_tune_config, eval_fns=eval_acc_fn)
```
Pre-CI
None
> Support double quant tuning

- .azure-pipelines/scripts/ut/env_setup.sh
- .azure-pipelines/scripts/ut/run_itrex.sh
- neural_compressor/utils/load_huggingface.py
ticket: https://jira.devtools.intel.com/browse/ILITV-3414
root cause, transformers 4.37.2 limits pytorch_model.bin loading by https://github.com/huggingface/transformers/blob/v4.37.2/src/transformers/modeling_utils.py#L530
"model.safetensors" only support tensor values, the state_dict not only includes weight key and value but also has inc quantization config(str) with pytorch fx mode, so still keep the "pytorch_model.bin".
> adapt transformers 4.37 loading

- neural_compressor/model/tensorflow_model.py
Feature
Using saved_model parse function as a backup in the whole workflow of parsing keras model.
PreCI
No
> Optimize the Workflow of Parsing Keras Model

- neural_compressor/torch/algorithms/weight_only/awq.py
- neural_compressor/torch/algorithms/weight_only/teq.py
- neural_compressor/torch/utils/auto_accelerator.py
- test/3x/torch/quantization/weight_only/test_woq_on_cuda.py
feature: Support auto device for TEQ and AWQ  
Follow-up to https://github.com/intel/neural-compressor/pull/1622.
```bash
pytest test_woq_on_cuda.py -k test_awq
pytest test_woq_on_cuda.py -k test_teq
```
Pre-CI
None
> Support auto device for TEQ and AWQ  

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/habana_fp8/run_llm.py
- neural_compressor/torch/algorithms/habana_fp8/modules.py
- neural_compressor/torch/amp/fp8/functions.py
[feature] support hardware scale for gaudi2
I found the cause of hardware scale failure before, it's because that I'm using scale=None for torch.matmul/bmm. 
It seems that all scales should be set when using hardware scales.
UT pass
> support hardware scale for gaudi2

- .azure-pipelines/scripts/ut/env_setup.sh
- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/weight_only.py
- test/adaptor/pytorch_adaptor/test_weight_only_adaptor_pytorch.py
- test/quantization/test_weight_only_quantization.py
- test/requirements.txt
feature
add one arg "export_args" to recipes["autoround_args"]
example:
```
recipes={
"autoround_args": {
"n_samples": 20,
"amp": False,
"seq_len": 10,
"iters": 10,
"scale_dtype": "fp32",
"device": "cpu",
"export_args": {"format": "itrex", "inplace": False},
},
},
```
> Enable autoround export [2.x]

- .azure-pipelines/scripts/ut/env_setup.sh
- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/weight_only.py
- neural_compressor/model/torch_model.py
- test/adaptor/pytorch_adaptor/test_weight_only_adaptor_pytorch.py
- test/quantization/test_weight_only_quantization.py
- test/requirements.txt
feature
Remove `amp`, `device`, `export_args`. 
Update AutoRound version (6815f8b66be456ecbef2d0beb33dbc4efeefdc04)
> Support automatic detection of amp and device Autoround [2.x]

- .azure-pipelines/scripts/ut/env_setup.sh
- neural_compressor/adaptor/pytorch.py
- neural_compressor/adaptor/torch_utils/weight_only.py
- neural_compressor/model/torch_model.py
- test/requirements.txt
feature
follow autoround updates
> Follow AutoRound updates [2.x]

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
bug fix
Fixed gptq acc gap.
1. Because run.args must be a tuple.
2. 3x use mse search
> Fix WOQ example accuracy gap between 2x and 3x

- neural_compressor/tensorflow/keras/layers/conv2d.py
- neural_compressor/tensorflow/keras/layers/depthwise_conv2d.py
- neural_compressor/tensorflow/keras/layers/quantizer.py
- neural_compressor/tensorflow/keras/layers/separable_conv2d.py
- neural_compressor/tensorflow/utils/model_wrappers.py
- test/3x/tensorflow/keras/test_config.py
- test/3x/tensorflow/quantization/test_smooth_quant.py
- test/3x/tensorflow/test_autotune.py
bug fix
There are multiple issues caused by Keras3 changes in tf2.16.1.
This PR is to fix them.
UT
NO
> Fix Keras3 Issues in TF 2.16.1 for 3.0 new API

- neural_compressor/utils/pytorch.py
bug fix
falcon_7b_woq_gptq_int4 
```
if eval(config["module_type"]) == MulLinear:
File "<string>", line 1
transformers_modules.tiiuae.falcon-7b-instruct.cf4b3c42ce2fdfe24f753f0f0d179202fea59c99.modeling_falcon.FalconLinear
^
SyntaxError: invalid decimal literal
```
> Fix comparison of module_type and MulLinear 

- requirements.txt
set "numpy < 2.0" for scikit-learn request "numpy >=1.19.5,<2.0"
https://pypi.org/project/numpy/2.0.0b1/ just released, pip can't resolve second level deps conflict. 
So if no this version limit, it will be failed when neural-compressor installed by ITREX.
> set numpy < 2.0 for scikit-learn request

- neural_compressor/adaptor/torch_utils/weight_only.py
bug fix
Fix OOM when export compressed model.
root cause: a) quantized weight `type` is not  an in-place operation. b)WeightOnlyLinear objects also occupy memory.
solution: a) return origin type
> Fix export compressed model OOM

- neural_compressor/utils/pytorch.py
[[NLPTOOLKIU-1299] smoothquant qconfig restore error - IT JIRA (Supports IC/ITS Data) (intel.com)](https://jira.devtools.intel.com/browse/NLPTOOLKIU-1299)
bloom 1b7 and mistral 7b due to INC missing model.eval() and model.config.torchscript=True
dolly_v2 and gpt_neox failed by quant with position_ids but restore missing.
the itrex fixed PR: https://github.com/intel/intel-extension-for-transformers/pull/1406
> Fix model restore loading

- examples/tensorflow/image_recognition/tensorflow_models/distillation/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
- examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
- examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
Bug fix
Because of quick version updates of tf2onnx related libraries, the tf2onnx examples often crash. Therefore, we are going to make the version fixed.
And the TF distillation examples meet issue because of tf2.16.1 use Keras3 instead of Keras2. We will limit the version. 
No
> Limit the Version of TF2ONNX and TF Distillation Examples

- docs/source/llm_recipes.md
> update LLM recipes

- neural_compressor/common/utils/utility.py
- requirements_ort.txt
- requirements_pt.txt
- test/3x/common/test_utility.py
Test
```bash
python test ./3x/common/test_utility.py  -k test_cpu_info
python test ./3x/common/test_utility.py  -k TestLazyImport
python test ./3x/common/test_utility.py  -k test_singleton_decorator
```
cpuinfo
psutil
> Port more helper classes from 2.x

- neural_compressor/adaptor/torch_utils/weight_only.py
bug fix
Issue: `FalconLinear` is not quantized.
root cause: falcon model 's linear is built-in by itself, not used torch.nn.linear, the issue depends on INC return model
solution: change supported layers name string to isinstance checking.
> Fix  RTN supported layer checking condition

- neural_compressor/torch/algorithms/weight_only/rtn.py
bug fix
follow 2.x https://github.com/intel/neural-compressor/pull/1705
> Fix RTN supported layer checking condition [3.x]

- neural_compressor/model/torch_model.py
> Improve WOQ autoround export

- neural_compressor/adaptor/onnxrt.py
> Fix ut failure for GPU backend

- neural_compressor/common/base_config.py
bug fix
re.match expected string but got non-str type  when ipex fallback
```
-> if re.match(op_name_pattern, op_name):
(Pdb) op_name_pattern
'add'
(Pdb) op_name
((' ', 'q_op_infos', '0'),)
```
> Add non-str `op_name` match workaround for IPEX

- neural_compressor/adaptor/torch_utils/gptq.py
Set default value for the `pad_max_length` attribute to avoid the case where it's set to `None` as done here https://github.com/intel/neural-compressor/blob/ba479850d3365fa8fae145b1376f104211af8b66/neural_compressor/adaptor/pytorch.py#L4531 by default as it'll results in issue when comparing its value during quantization like done here https://github.com/intel/neural-compressor/blob/v2.5/neural_compressor/adaptor/torch_utils/gptq.py#L307
An other solution could be to modify `framework_specific_info["recipes"]`
> Fix case where pad_max_length set to None

- neural_compressor/torch/algorithms/smooth_quant/utility.py
- neural_compressor/torch/algorithms/static_quant/static_quant.py
- neural_compressor/torch/algorithms/static_quant/utility.py
- neural_compressor/torch/quantization/config.py
bug fix
fixed tune_cfg loading problem for 3.x static quant API
UT passed
> fix tune_cfg issue for 3.x static quant

- examples/onnxrt/image_recognition/beit/quantization/ptq_static/prepare_model.py
bug fix
API Changed
This pull request addresses an urgent security issue where a live Azure Storage SAS token was inadvertently exposed in the codebase. The exposed secret has been removed to prevent any unauthorized access to Microsoft's resources.
The file prepare_model.py within the onnxrt/image_recognition/beit/quantization/ptq_static directory previously contained a hardcoded Azure Storage SAS token, which is against best practices and could potentially compromise the security of our services.
The token has been revoked to ensure the security of our services. As an additional measure, I have replaced the URL with a placeholder to prompt the user to insert their own credentials.
The expected behavior after this PR is merged is that the code will no longer contain any live secrets, and …
> Update model ckpt download url in prepare_model.py

- .azure-pipelines/model-test-3x.yml
- .github/checkgroup.yml
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/requirements.txt
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
- examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/requirements.txt
- examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_sparsegpt.py
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/requirements.txt
- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
upgrade following ITREX
ITREX is upgrading lm_eval version to 0.4.2 and INC examples using ITREX's evaluate need to be updated.
https://github.com/intel/intel-extension-for-transformers/pull/1462
pre-ci pass
local test
lm_eval upgrade
> upgrade lm_eval to 0.4.2 following ITREX

- neural_compressor/common/base_config.py
- neural_compressor/torch/utils/utility.py
- test/3x/common/test_common.py
- test/3x/torch/test_config.py
Enhancement
```python
fc1_config = RTNConfig(bits=6, dtype="int8")
quant_config.set_local(torch.nn.Linear, fc1_config)
quant_config.set_local(torch.add, fc1_config)
```
Pre-CI
None
> Enhance the `set_local` for operator type

- neural_compressor/onnxrt/algorithms/layer_wise/core.py
- requirements_ort.txt
- test/3x/onnxrt/requirements.txt
bug fix
Remove version limitation of transformers for ort layer-wise
CI
No
> Remove version limitation of transformers for ort layer-wise

- neural_compressor/torch/algorithms/__init__.py
- neural_compressor/torch/algorithms/base_algorithm.py
- neural_compressor/torch/algorithms/static_quant/__init__.py
- neural_compressor/torch/algorithms/static_quant/static_quant.py
- neural_compressor/torch/algorithms/weight_only/awq.py
- neural_compressor/torch/algorithms/weight_only/rtn.py
- neural_compressor/torch/quantization/__init__.py
- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/quantize.py
- neural_compressor/torch/utils/utility.py
- test/3x/torch/quantization/test_static_quant.py
feature: Refactor PT 3.x static quant API
API changed or not: yes
Refactor PT 3.x static quant API
- Add new user-facing API: `from neural_compressor.torch.quantization import prepare` and `from 
neural_compressor.torch.quantization import convert`
- Add base class: `Quantizer`. Any algorithm needs to inherit `Quantizer` base class.
- Modify internal algorithm entry to call member functions of algorithm Quantizer class.
**static quant**
```diff
- from neural_compressor.torch.quantization import get_default_static_config, quantize
+ from neural_compressor.torch.quantization import get_default_static_config, prepare, convert
quant_config = get_default_static_config()
example_inputs = self.input
- q_model = quantize(fp32_model, quant_config=quant_config, run_fn=run_fn, …
```
> Refactor PT 3.x  API: static_quant & rtn

- neural_compressor/torch/algorithms/weight_only/rtn.py
- neural_compressor/torch/algorithms/weight_only/utility.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/weight_only/test_rtn.py
feature
https://jira.devtools.intel.com/browse/ILITV-3505
support fp8 cast WOQ using official PyTorch >= 2.2
Torch supports 4 fp8 dtypes as shown below. In INC, we use short strings for mapping.
```
FP8_MAPPING = {
"fp8_e5m2": torch.float8_e5m2,
"fp8_e5m2fnuz": torch.float8_e5m2fnuz,
"fp8_e4m3fn": torch.float8_e4m3fn,
"fp8_e4m3fnuz": torch.float8_e4m3fnuz,
}
```
An introduction to the differences between FP8 data types: 
Float8E4M3FN, Float8E4M3FNUZ, Float8E5M2, Float8E5M2FNUZ
[stablehlo/rfcs/20230321-fp8_fnuz.md at main · openxla/stablehlo (github.com)](https://github.com/openxla/stablehlo/blob/main/rfcs/20230321-fp8_fnuz.md)
local test
> support fp8 cast WOQ

- neural_compressor/torch/utils/auto_accelerator.py
enhancement
Add xpu accelerator in 3x
Currently, we don't have CI for XPU.
> add xpu accelerator in 3x

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/habana_fp8/run_llm.py
- neural_compressor/common/utils/save_load.py
- neural_compressor/torch/quantization/load_entry.py
- test/3x/torch/quantization/habana_fp8/test_fp8.py
- test/3x/torch/quantization/test_smooth_quant.py
- test/3x/torch/quantization/test_static_quant.py
refine 3.x ipex backend load API
move load API from algorithm to quantization
`from neural_compressor.torch.algorithms.static_quant import load` --> `from neural_compressor.torch.quantization import load`
ut passed
> refine load API for 3.x ipex backend

- neural_compressor/torch/utils/auto_accelerator.py
The cpu and cuda do not have `mark_step`, reuse the `Auto_Accelerator`'s `mark_step` (return None).
Local test on machine with cuda.
None
> Remove `mark_step` for cuda and cpu

- neural_compressor/torch/algorithms/weight_only/autoround.py
- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/weight_only/test_autoround.py
> Add prepare/convert ut for autoround

- neural_compressor/common/base_config.py
- neural_compressor/common/base_tuning.py
- neural_compressor/common/tuning_param.py
- neural_compressor/torch/quantization/algorithm_entry.py
- test/3x/common/test_common.py
- test/3x/torch/quantization/weight_only/test_mixed_algos.py
Pre-CI
Test
```bash
pytest -sv ./test/3x/common/test_common.py  -k test_config_loader_skip_verified_config
```
None
> Skip the verified config

- docs/source/coding_style.md
Docs
> 2.2 Imports
Use import statements for packages and modules only, not for individual types, classes, or functions.
https://google.github.io/styleguide/pyguide.html#22-imports
None
> Update the coding style doc

- neural_compressor/torch/quantization/__init__.py
- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/test_autotune.py
feature
API changed or not: `get_woq_tuning_config`
Add torch WOQ tuning
https://github.com/intel/neural-compressor/blob/master/docs/source/quantization_weight_only.md#woq-algorithms-tuning
Pre-CI
None
> Add torch WOQ tuning 

- neural_compressor_ort/algorithms/layer_wise/core.py
- neural_compressor_ort/constants.py
- neural_compressor_ort/quantization/config.py
- neural_compressor_ort/quantization/tuning.py
- test/utils/test_general.py
> Fix type hints

- neural_compressor/torch/algorithms/pt2e_quant/__init__.py
- neural_compressor/torch/algorithms/pt2e_quant/core.py
- neural_compressor/torch/quantization/__init__.py
- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/config.py
- neural_compressor/torch/utils/constants.py
- neural_compressor/torch/utils/environ.py
- neural_compressor/torch/utils/utility.py
- test/3x/torch/algorithms/pt2e_quant/test_pt2e_w8a8.py
- test/3x/torch/quantization/test_pt2e_quant.py
feature
```python
model = UserModel()
example_inputs = ...
from neural_compressor.torch.quantization import get_default_dynamic_config, prepare, convert
from neural_compressor.torch.export import export
dynamic_shapes = {"input_ids": (None, Dim("seq_len"))}
exported_model = export(model, example_inputs=example_inputs, dynamic_shapes=dynamic_shapes)
quant_config = get_default_dynamic_config()
prepare_model = prepare(model, quant_config)
run_fn(prepare_model)
converted_model = convert(prepare_model)
opt_model = torch.compile(converted_model)
out = opt_model(*example_inputs)
```
> Add pt2e dynamic quantization

- neural_compressor/torch/algorithms/weight_only/gptq.py
- neural_compressor/torch/algorithms/weight_only/modules.py
- test/3x/torch/quantization/weight_only/test_gptq.py
> [3x] fix bug in gptq g_idx

- test/3x/torch/quantization/weight_only/test_gptq.py
> Enhance GPTQ `act_order` UT

- examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
bug fix
missing tokenizer when using lm_eval==0.4.2
[detail description](https://jira.devtools.intel.com/browse/ILITV-3586)
> fix bug in run_clm_no_trainer.py

- neural_compressor/torch/algorithms/mix_precision/half_precision_convert.py
- neural_compressor/torch/algorithms/weight_only/awq.py
- neural_compressor/torch/algorithms/weight_only/gptq.py
- neural_compressor/torch/algorithms/weight_only/modules.py
- neural_compressor/torch/algorithms/weight_only/rtn.py
- neural_compressor/torch/algorithms/weight_only/teq.py
- neural_compressor/torch/algorithms/weight_only/utility.py
- neural_compressor/torch/utils/auto_accelerator.py
- neural_compressor/torch/utils/environ.py
- test/3x/torch/quantization/weight_only/test_awq.py
- test/3x/torch/quantization/weight_only/test_gptq.py
- test/3x/torch/quantization/weight_only/test_mixed_algos.py
- test/3x/torch/quantization/weight_only/test_rtn.py
- test/3x/torch/quantization/weight_only/test_teq.py
- test/3x/torch/test_auto_accelerator.py
feature 
RTN UTs now can run successfully on Gaudi2 (HPU)
WOQ UTs now can run on CUDA/HPU automatically
we keep the same priority as auto_accelerator used. if CUDA and CPU exists, we will only use CUDA.
RTN UTs ran successfully on Gaudi2 (HPU) and A100 (GPU)
> support RTN on Gaudi2 and make UTs auto detect device

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
3.x example bug fix
pass extension test
> fix 3.x IPEX examples failed with evaluate

- neural_compressor/model/tensorflow_model.py
bug fix
The Estimator APIs have been removed after TF2.16. An error will be reported if calling related APIs. We are going to add a version check to fix it on 2x.
fix bug
PreCI
No
> Fix INC TF 2x Estimator Issue on TF2.16

- examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/benchmark.py
- examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/main.py
bug fix
The environment variable `TF_USE_LEGACY_KERAS` is set to be `True` when loading the gpt2_medium_sq or opt_125m_sq example model from `Transformers`. We need to set it back so that we can still use `tf.keras` API without installing `tf_keras`.
The `TF_USE_LEGACY_KERAS` is set to be `False` after the models have been loaded.
Extension Test
No
> Fix TF 2x LLM SQ Legacy Keras Environment Variable Issue

- neural_compressor/torch/algorithms/weight_only/modules.py
bug fix
if `self.compression_dtype`  is torch.int32, then `unpacked_tensor`'s dtype will be int32
> Fix `dtype` of `unpacked tensor` 

- neural_compressor/adaptor/torch_utils/model_wrapper.py
- neural_compressor/torch/algorithms/weight_only/modules.py
bug fix
solution: use numpy for pack_tensor/unpack_tensor
As we found that cuda is more quick than cpu in some cases, we use below behavior as default.
```
def pack_tensor():
if 'cuda' in self.device:  # may be xpu also needs it
pack_tensor_with_torch()
else:
pack_tensor_with_numpy()
```
local test on Xeon(R) 6248
code: https://github.com/intel/intel-extension-for-transformers/tree/main/examples/huggingface/pytorch/text-generation/quantization
cmd: `python run_generation_cpu_woq.py  --model Phi-3-mini-4k-instruct     --woq     --woq_algo Rtn 2>&1 | tee test_np.log`
original result
```
2024-05-29 10:27:16 [INFO] Pass quantize model elapsed time: 1050.21 ms
2024-05-29 10:27:16 [INFO] Save tuning history to /home2/kaihuita/code/intel-extension-for-transformers/examples/huggingface/pytorch/tex …
```
> Fix WOQ Linear pack/unpack slow issue 2x

- neural_compressor/torch/algorithms/weight_only/hqq/quantizer.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/weight_only/hqq/test_hqq_cpu.py
feature 
API changed or not:
```python
quant_config = HQQConfig().set_local("fc1", HQQConfig(dtype="fp32"))
qmodel = convert(prepare(model=ToyModel(), quant_config=quant_config))
```
Pre-CI
None
> Add fallback support for HQQ

- neural_compressor/torch/algorithms/weight_only/awq.py
- neural_compressor/torch/algorithms/weight_only/utility.py
- test/3x/torch/quantization/weight_only/test_awq.py
bug fix
Currenly, AWQ UTs doesn't set return_dict/torchscript for transformers model, so the GraphTrace is always failed.
MulLinear will be inserted to help AWQ work, and is not necessary. 
Ber this PR, return_dict is automatically set and make AWQ ease-of-use. 
UT pass
> set automatic return_dict=False for GraphTrace

- neural_coder/interface.py
- neural_coder/utils/device.py
- neural_coder/utils/handle_user_input.py
bug fix
https://github.com/intel/neural-compressor/security/code-scanning/26
https://github.com/intel/neural-compressor/security/code-scanning/25
https://github.com/intel/neural-compressor/security/code-scanning/24
https://github.com/intel/neural-compressor/security/code-scanning/23
fix issues
NA
No
> Fix CodeQL Security Issue for Neural Coder

- neural_compressor/torch/algorithms/mx_quant/mx.py
- test/3x/torch/algorithms/mx_quant/test_mx_utility.py
- test/3x/torch/quantization/test_mx_quant.py
UT
Name                                                      Stmts   Miss  Cover
neural_compressor/torch/algorithms/mx_quant/__init__.py       0      0   100%
neural_compressor/torch/algorithms/mx_quant/mx.py            59      5    92%
neural_compressor/torch/algorithms/mx_quant/utils.py        272     33    88%
TOTAL                                                       331     38    89%
> Add UT and remove unused code for torch MX quant

- neural_solution/backend/scheduler.py
- neural_solution/frontend/fastapi/main_server.py
- neural_solution/frontend/utility.py
- neural_solution/test/backend/test_scheduler.py
- neural_solution/test/frontend/fastapi/test_main_server.py
- neural_solution/test/frontend/fastapi/test_task_submitter.py
- neural_solution/test/frontend/fastapi/test_utils.py
> Fix Neural Solution security issue

- neural_compressor/torch/algorithms/smooth_quant/utility.py
- neural_compressor/torch/algorithms/static_quant/utility.py
- test/3x/torch/quantization/test_static_quant.py
bug fix
fix 3x ipex static quant regression
cannot fallback with op type name ('linear')
dump wrong op stats (no 'Linear&relu' op type)
> fix 3x ipex static quant regression

- requirements_ort.txt
- requirements_pt.txt
> Limit numpy versions

- neural_compressor/torch/algorithms/weight_only/gptq.py
bug fix
`FalconLinear` is not quantized
> Fix GPTQ layers match

- neural_compressor/torch/algorithms/weight_only/utility.py
- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/utils/utility.py
- requirements_pt.txt
> Add op statistics dump for woq

- README.md
This PR fixes a bug in the documentation for running a Gaudi container and fixes a misspelling (`Gauid2` ➡️  `Gaudi2`).
The `docker run` command is using `-it` which will run the container with an interactive shell. The two commands after the `docker run` (`docker ps` and `docker exec`) aren't needed since you are already in the container at that point, and they will fail if the user tries to do run them:
```
$ docker run -it --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.1:latest
* Starting OpenBSD Secure Shell server sshd …
```
> Update the Gaudi container example in the README and fix a typo

- neural_solution/frontend/utility.py
bug fix
SQL injection 
When submitting task through gRPC, it calls to the function `TaskSubmitterServicer.SubmitTask` which then calls to `submit_task_to_db` to do the job. The sql is constructed at run time with the `task` parameter and most attributes of the `task` can be controlled by attacker (e.g. script_url field), which results in SQL injection.
> Fix sql injection for Neural Solution gRPC

- neural_compressor/torch/algorithms/weight_only/gptq.py
- neural_compressor/torch/algorithms/weight_only/modules.py
- neural_compressor/torch/algorithms/weight_only/rtn.py
- neural_compressor/torch/utils/utility.py
- test/3x/torch/quantization/weight_only/test_gptq.py
- test/3x/torch/quantization/weight_only/test_rtn.py
bug fix
UT pass on CUDA device
> [3x] support automatic host2device on RTN and GPTQ

- neural_compressor/version.py
> bump version into v3.0

- neural_compressor/torch/algorithms/weight_only/teq.py
> Add export support for TEQ

- docs/3x/PyTorch.md
> Update PyTorch Supported Matrix

- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/test_static_quant.py
implement TorchBaseConfig
Re-write func `_get_op_name_op_type_config` in BaseConfig to fallback op_type with string.
Reason:
UTs pass
> implement TorchBaseConfig

- neural_compressor/torch/algorithms/weight_only/utility.py
- neural_compressor/torch/quantization/autotune.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/weight_only/test_woq_utils.py
> Support woq Autotune

- neural_compressor/torch/algorithms/weight_only/awq.py
- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/weight_only/test_awq.py
> Support absorb dict for awq

- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/autotune.py
- neural_compressor/torch/quantization/config.py
- neural_compressor/torch/utils/environ.py
- neural_compressor/torch/utils/utility.py
docstring for torch.quantization and torch.utils
> add docstring for torch.quantization and torch.utils

- neural_compressor/torch/algorithms/layer_wise/utils.py
- neural_compressor/torch/utils/__init__.py
- neural_compressor/torch/utils/utility.py
bug fix 
import accelerate and transformers when import neural_compressor.torch.utils
> Fix unused pkgs  import

- .azure-pipelines/scripts/install_nc.sh
- README.md
- docs/source/installation_guide.md
- requirements_pt.txt
update 3x torch installation
provide multiple torch install choice for different platform
CI pass
CI
No
> update 3x torch installation

- .azure-pipelines/model-test-3x.yml
- .azure-pipelines/model-test.yml
- .azure-pipelines/scripts/models/generate_report.sh
validation update
New results or previous results could not find all raise issues in CI model test, so the test will raise accuracy regression on time. 
> new results or previous results could not find all raise issues in CI model test

- README.md
- docs/build_docs/build.sh
documentation
fix the links issues in welcome.html
> fix welcome.html link issue

- .azure-pipelines/model-test-3x.yml
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/run_quant.sh
bug fix
issue
```log
File "/home/sdp/miniforge3/envs/pytorch-2.3.0+cpu-3.10-spr/lib/python3.10/site-packages/neural_compressor/torch/algorithms/weight_only/gptq.py", line 813, in fasterquant
H = torch.linalg.cholesky(H)
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 1 is not positive-definite).
```
solution: increase percentage of damp
> Fix `opt_125m_woq_gptq_int4_dq_ggml` issue

- README.md
- docs/source/llm_recipes.md
- examples/.config/model_params_tensorflow_3x.json
- examples/3.x_api/README.md
Add 3.x examples readme
Update LLM models accuracy
> Add 3.x readme

- docs/source/3x/PT_MixedPrecision.md
- docs/source/3x/TF_Quant.md
- docs/source/3x/TF_SQ.md
- docs/source/3x/quantization.md
documentation
Fix broken link in docs
> Fix broken link in docs

- .azure-pipelines/scripts/ut/run_itrex.sh
- .azure-pipelines/ut-3x-pt-fp8.yml
- README.md
- docs/source/CONTRIBUTING.md
1. update main page
2. fix fp8 ut coverage
> update main page

- README.md
- docs/source/3x/PT_FP8Quant.md
- docs/source/3x/PyTorch.md
documentation
update readme for fp8
> update readme for fp8

- neural_compressor/torch/algorithms/pt2e_quant/utility.py
- neural_compressor/torch/utils/environ.py
- test/3x/torch/quantization/test_pt2e_quant.py
bug fix 
Some pt2e-related tests requires torch 2.5
> Skip some tests for torch 2.4

- .azure-pipelines/scripts/fwk_version.sh
- .azure-pipelines/scripts/install_nc.sh
- .azure-pipelines/scripts/models/env_setup.sh
- .azure-pipelines/scripts/ut/3x/run_3x_pt.sh
- .azure-pipelines/scripts/ut/run_basic_pt_pruning.sh
- .azure-pipelines/template/docker-template.yml
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/requirements.txt
- neural_compressor/torch/algorithms/pt2e_quant/utility.py
- neural_compressor/torch/utils/environ.py
- test/3x/torch/quantization/test_pt2e_quant.py
> Fix UT env

- .azure-pipelines/scripts/install_nc.sh
- .azure-pipelines/scripts/ut/3x/run_3x_pt_fp8.sh
- neural_compressor/torch/algorithms/fp8_quant/_core/utils.py
- setup.py
validation
update installation and ci test for 3x api
> update installation and ci test for 3x api

- neural_compressor/torch/algorithms/weight_only/utility.py
bug fix
dtype initialization in global is not compatible with old torch version.
fix it with `hasattr` check
UT pass with old torch version
> add hasattr check for torch fp8 dtype

- neural_compressor/torch/algorithms/pt2e_quant/utility.py
- test/3x/torch/quantization/test_pt2e_quant.py
feature:    [PerChannelMinMaxObserver](https://pytorch.org/docs/stable/generated/torch.ao.quantization.observer.PerChannelMinMaxObserver.html#perchannelminmaxobserver)
> Add `PerChannelMinMaxObserver` for PT2E

- README.md
- docs/source/publication_list.md
> Add recent publications

- docs/source/3x/PyTorch.md
- neural_compressor/torch/utils/auto_accelerator.py
- test/3x/torch/quantization/weight_only/test_hqq.py
- test/3x/torch/utils/test_auto_accelerator.py
documentation
add INC_FORCE_DEVICE introduction
> add INC_FORCE_DEVICE introduction

- neural_compressor/torch/algorithms/weight_only/utility.py
- neural_compressor/transformers/models/modeling_auto.py
- neural_compressor/transformers/quantization/utils.py
- neural_compressor/transformers/utils/quantization_config.py
- test/3x/torch/quantization/weight_only/test_transfomers.py
to load awq model quantized by autoawq and inference by IPEX kernel.
> add repack_awq_to_optimum_format function

- docs/source/3x/transformers_like_api.md
> Add transformers-like api doc

- neural_compressor/torch/algorithms/weight_only/awq.py
- neural_compressor/torch/algorithms/weight_only/save_load.py
> Adapt transformers 4.45.1

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/mx_quant/requirements.txt
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/mx_quant/run_clm_no_trainer.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/requirements.txt
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/run_clm_no_trainer.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/ipex/requirements.txt
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/ipex/run_clm_no_trainer.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/requirements.txt
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/run_clm_no_trainer.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/llm_quantization_recipes.md
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/run_generation_cpu_woq.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/run_generation_gpu_woq.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/requirements.txt
> Remove itrex dependency for 3x example

- README.md
documentation 
render [page](https://github.com/intel/neural-compressor/blob/thuang6/update-readme/README.md)
> [Doc]Add transformers-like api link in readme

- .azure-pipelines/scripts/ut/run_itrex.sh
- examples/.config/model_params_pytorch_3x.json
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/README.md
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/run_benchmark.sh
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/run_clm_no_trainer.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/run_quant.sh
feature
AWQ/TEQ/AutoRound/AutoTune
> Add woq examples

- docs/source/3x/transformers_like_api.md
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/README.md
- neural_compressor/transformers/quantization/utils.py
cherry pick master 61f1e393b6374703b6516fe9406bafb0cc088009
> Cherry pick support quant procedure on XPU (#2026)

- docs/source/3x/gaudi_version_map.md
documentation 
rendered [page ](https://github.com/intel/neural-compressor/blob/thuang6/update_ver_map/docs/source/3x/gaudi_version_map.md)
> [Document] Update Gaudi version mapping table for v3.1

- neural_compressor/evaluation/lm_eval/accuracy.py
- neural_compressor/evaluation/lm_eval/models/huggingface.py
- neural_compressor/evaluation/lm_eval/utils.py
feature
add buckets argument for lm_eval, it is used by HPU to limit static input length range.
By default, `buckets: Optional[list] = [64, 128, 256, 512, 1024, 2048, 4096]`
If default buckets are not enough to hold input length, it will cause error.
If used buckets is too many, it will take too much memory. (Each used bucket will cause the model to be copied)
> add buckets setting for lm_eval

- neural_compressor/torch/algorithms/weight_only/gptq.py
bug fix
some memory is not released due to lack of `torch.hpu.synchronize()` and `gc.collect()`
Making sure the process is working as below:
llama2-70b works on one Gaudi2 card.
> fix GPTQ oom issue on HPU

- .azure-pipelines/model-test.yml
- .azure-pipelines/scripts/fwk_version.sh
- .azure-pipelines/scripts/install_nc.sh
- .azure-pipelines/ut-3x-pt-fp8.yml
- .azure-pipelines/ut-3x-pt.yml
- .azure-pipelines/ut-basic.yml
- neural_compressor/torch/algorithms/static_quant/utility.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/test_pt2e_quant.py
- test/3x/torch/quantization/weight_only/test_transfomers.py
- test/model/test_onnx_model.py
static quant
HistogramObserver: remove `upsample_rate`
ipex 
op_type_config_dict[name] = config
gptq 
output update
> Adapt torch and ipex 2.5

- neural_compressor/torch/utils/utility.py
request from optimum-intel https://github.com/huggingface/optimum-intel/pull/1018#discussion_r1866211746
to make `load_empty_model` have the same input kwargs with `AutoModelForCausalLM.from_pretrained`
load_empty_function couldn't pass the **loading_kwargs from `AutoModelForCausalLM.from_pretrained` , because we initialize the config first, and then initialize the model in load_empty_model function. some loading_kwargs like "subfolder", "revision" doesn't be accepted by `AutoConfig.from_pretrained` kwargs.
https://github.com/intel/neural-compressor/blob/e2696603f45f5796f1c048aab33eef11aaeb2cdb/neural_compressor/torch/utils/utility.py#L356
when the **loading_kwargs passed, config initialization will raise error like the following.
how to …
> improve load_empty_model function.

- docs/source/faq.md
documentation 
```
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite. 
```
this is a known issue https://github.com/AutoGPTQ/AutoGPTQ/issues/196
> Add gptq known issue

- examples/3.x_api/pytorch/diffusion_model/diffusers/stable_diffusion/smooth_quant/run_benchmark.sh
- examples/3.x_api/pytorch/diffusion_model/diffusers/stable_diffusion/smooth_quant/sdxl_smooth_quant.py
bug fix
- error
```AttributeError: 'StableDiffusionXLPipelineSQ' object has no attribute 'do_classifier_free_guidance'```
- solution
Set the config attribute of the quantized UNet to match the original UNet's config.
> Fix sdxl `q_unet` config

- neural_compressor/torch/algorithms/weight_only/modules.py
> remove synchronize for `pack_unpack_tensor_with_numpy`

- neural_compressor/torch/algorithms/weight_only/save_load.py
- test/3x/torch/quantization/weight_only/test_transfomers.py
bug fix
```
raise EnvironmentError(
OSError: hugging-quants/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 does not appear to have a file named model.safetensors. Checkout 'https://huggingface.co/hugging-quants/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4/tree/main' for available files.
```
is_sharded not changed 
> Fix `is_sharded` setting for loading quant model

- test/3x/torch/algorithms/fp8_quant/unit_tests/test_functions/test_config_json.py
https://jira.habana-labs.com/browse/SW-214087
https://jira.devtools.intel.com/browse/ILITV-3839
The root cause is not the code itself but rather the environment. The IDC machine（local machine） uses Docker with Python 3.12.3, while the unit test's expected error message is based on Python 3.10. This discrepancy leads to an assertion error.
the python new unboundlocalerror message is introduced by python 3.11, https://github.com/python/cpython/blob/30efede33ca1fe32debbae93cc40b0e7e0b133b3/Python/ceval_macros.h#L351
In Python 3.12.3: UnboundLocalError: "cannot access local variable 'fname_base' where it is not associated with a value"
In Python 3.10.12: UnboundLocalError: "local variable 'fname_base' referenced before assignment"
how to …
> [SW-214087] Fix error message for different python version

- .azure-pipelines/template/docker-template.yml
- README.md
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/requirements-autoround-hpu.txt
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/run_benchmark.sh
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/weight_only/run_clm_no_trainer.py
- neural_compressor/evaluation/lm_eval/models/huggingface.py
- test/3x/torch/requirements.txt
> fix woq example and update document for v1.19.0

- neural_compressor/transformers/models/modeling_auto.py
bug fix
Business impact: The int4 llama model runs into crash with IPEX LLM workload.
Defect/regression: The error message is shown below:
The root cause is that `hf_device_map` is assigned to `dict(device_map)` in [Accelerate ](https://github.com/huggingface/accelerate/blob/main/src/accelerate/big_modeling.py#L502)while `device_map` is changed to "cpu" in [INC](https://github.com/intel/neural-compressor/blob/master/neural_compressor/transformers/models/modeling_auto.py#L168). StaticCache's device is initialized by `hf_device_map` and is "cpu" while the other tensor's device is "xpu".
solution: add `hf_device_map` setting after quantization
any library dependency introduced or …
> Fix hf_device_map setting for transformers-like api

- neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
https://jira.devtools.intel.com/browse/ILITV-3885
internal repo already fixed this issue, I cherry pick it to public repo.
> [SW-219274] - Changing the quant method name in lm-head (#150)

- .pre-commit-config.yaml
- neural_compressor/torch/algorithms/fp8_quant/_core/common.py
- neural_compressor/torch/algorithms/fp8_quant/_core/quantize.py
- neural_compressor/torch/algorithms/fp8_quant/_core/scale.py
- neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
feature
Enable layer-by-layer convert for vllm Deepseek model
> Enable layer-by-layer convert for vllm Deepseek model

- requirements_pt.txt
upgrade numpy from 1.23.5 to 1.26.4 for pytorch 3x
> upgrade numpy from 1.23.5 to 1.26.4

- .azure-pipelines/scripts/ut/env_setup.sh
- examples/onnxrt/image_recognition/onnx_model_zoo/resnet50/quantization/ptq_static/requirements.txt
- test/requirements.txt
Freeze 2x package versions in requirements.txt to ensure compatibility
> Freeze 2x package versions

- README.md
- neural_compressor/version.py
- test/requirements.txt
> bump into v3.3.1

- neural_compressor/torch/algorithms/weight_only/save_load.py
> [SW-223106] change code with robust implementation

- neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
workaround
Update PatchedVLLMKVCache for deepseek performance
> Update PatchedVLLMKVCache for deepseek performance

- neural_compressor/torch/utils/environ.py
feature 
When we set the environment variable `INC_TARGET_DEVICE` in the code, this setting does not take effect and the previously cached accelerator from lru_cache is used instead.
> Reset `accelerator` when `INC_TARGET_DEVICE` is set in code

- examples/pytorch/nlp/huggingface_models/text-to-image/quantization/README.md
- Simple bug fix (in documentation)
- API not changed
Example in README is crashing due to invalid argument passing
**Before fix:**
Output **Error**:
```bash
Traceback (most recent call last):
File "/root/flux_peft_fp8/neural-compressor/examples/pytorch/nlp/huggingface_models/text-to-image/quantization/run_diffusion.py", line 337, in <module>
main()
File "/root/flux_peft_fp8/neural-compressor/examples/pytorch/nlp/huggingface_models/text-to-image/quantization/run_diffusion.py", line 290, in main
quantization_config = PostTrainingQuantConfig(
File "/usr/local/lib/python3.10/dist-packages/neural_compressor/config.py", line 1322, in __init__
self.approach = approach
File "/usr/local/lib/python3.10/dist-packages/neural_compressor/config.py", line 1337, in approach
if _check_value("approach", …
```
> Fix text-to-image example

- neural_compressor/transformers/quantization/utils.py
bug fix
```
error:
[ERROR][modeling_auto.py:128] index 133 is out of bounds for dimension 0 with size 128
[ERROR][modeling_auto.py:129] Saved low bit model loading failed, please check your model.
```
add `update_g_idx` flag to avoid secondary value updates.
note:
waiting for the release of ipex-gpu v2.7 ...
related PR: https://github.com/intel-innersource/frameworks.ai.pytorch.ipex-gpu/pull/5411
results:
meta-llama/Meta-Llama-3-8B-Instruct on PVC
|    Tasks     |Version|Filter|n-shot|  Metric  |   |Value |   |Stderr|
|--------------|------:|------|-----:|----------|---|-----:|---|-----:|
|lambada_openai|      1|none  |     0|acc       |↑  |0.7093|±  |0.0063|
|              |       |none  |     0|perplexity|↓  |3.5535|±  |0.0997|
how to …
> Add `update_g_idx` flag for setting qweight&g_idx

- .azure-pipelines/scripts/ut/3x/collect_log_3x.sh
- neural_compressor/__init__.py
- setup.py
> [SW-219134] dynamically remove  2x content

- .azure-pipelines/scripts/ut/3x/collect_log_3x.sh
- neural_compressor/__init__.py
- setup.py
Discussed with @ulivne 
This is not a good approach because it can introduce changes to the development environment and cause unintentional commits.
> Revert "[SW-219134] dynamically remove  2x content"

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/run_generation_cpu_woq.py
bug fix 
model: meta-llama/Llama-3.1-8B-Instruct
`add_bos_token` default is False.
If the model was trained or fine-tuned with a BOS token, this may lead to incorrect results.
> Add `add_bos_token` for Llama3 evaluation

- README.md
- docs/source/3x/PyTorch.md
- docs/source/faq.md
- docs/source/quantization.md
- examples/3.x_api/pytorch/image_recognition/torchvision_models/quantization/static_quant/ipex/README.md
- examples/3.x_api/pytorch/nlp/huggingface_models/question-answering/quantization/static_quant/ipex/README.md
- examples/README.md
> replace XPU with Intel GPU

- neural_compressor/transformers/models/modeling_auto.py
- neural_compressor/transformers/quantization/utils.py
bug fix 
error:
```
The size of tensor a (4096) must match the size of tensor b (128) at non-singleton dimension 0
```
When loading a GPTQ INT8 model, g_idx should be either None or a correct value, rather than a tensor of zeros.
> Fix `g_idx` init in transformers-like API

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/run_generation_gpu_woq.py
example
model: meta-llama/Llama-3.1-8B-Instruct
add_bos_token default is False.
If the model was trained or fine-tuned with a BOS token, this may lead to incorrect results.
> Add `add_bos_token` for Llama3(Instruct) xpu evaluation

- neural_compressor/torch/algorithms/fp8_quant/_core/fp_utils.py
- neural_compressor/torch/algorithms/fp8_quant/_core/scale_methods/scale_method_factory.py
- neural_compressor/torch/algorithms/fp8_quant/_quant_common/quant_config.py
- neural_compressor/torch/utils/environ.py
> Naive Scaling

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/README.md
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/requirements.txt
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/run_clm_no_trainer.py
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/run_quant.sh
example
Since IPEX will drop SQ INT8 feature in future version and SQ was upstream to TorchAO. Need to fix IPEX in old version. 
> Freeze IPEX version for INT8 SQ support

- neural_compressor/utils/utility.py
> Replace all pickle load with safe load

- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/weight_only/test_autoround.py
bug fix
Runtime error: mix dtype (on spr bf16 machine)
assert Key "scale" error
vlm calib error: no data cache
> Fix autoround CI with amp

- docs/source/3x/PT_FP8Quant.md
document
add CPU FP8 QDQ doc
depend on https://github.com/intel/neural-compressor/pull/2238
> add CPU FP8 QDQ doc

- neural_compressor/torch/algorithms/weight_only/save_load.py
- neural_compressor/torch/utils/utility.py
- neural_compressor/transformers/models/modeling_auto.py
- neural_compressor/transformers/quantization/utils.py
- test/3x/torch/algorithms/pt2e_quant/test_pt2e_w8a8.py
- test/3x/torch/quantization/test_pt2e_quant.py
adapt transformers 4.56.0
transformers==4.56.0 changed the import path, we now need to use transformers.pytorch_utils.Conv1D instead of transformers.modeling_utils.Conv1D
1. Use `transformers.pytorch_utils.Conv1D` instead of `transformers.modeling_utils.Conv1D`
2. use `_set_default_dtype` instead of `_set_default_torch_dtype`
3. fix pt2e ut: from transformers.integrations.executorch import export_with_dynamic_cache
> Adapt transformers 4.56.0

- .azure-pipelines/scripts/install_nc.sh
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/requirements_cpu_woq.txt
Use --index-url instead of --extra-index-url for oneccl_bind_pt, fix the code attack risk.  
If the attacker release a oneccl_bind_pt in pypi, the pip will pull the code from the attacker controlled package (released in pypi)! This leads to remote code execution.    
https://intelait.intel.com/nav_to.do?uri=%2Fx_volt2_csi_product_vulnerability.do%3Fsys_id%3Deaea4203df2fa21068deb094c23889ee%26sysparm_view%3Dcsi%26sysparm_view_forced%3Dtrue 
Restrict the oneccl_bind_pt source. 
CI test. 
> Use --index-url instead of --extra-index-url for oneccl_bind_pt

- neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py
@yiliu30 please for review, thanks
> add chunk moe support on INC

- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/README.md
- examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/transformers/weight_only/text-generation/requirements_cpu_woq.txt
bug fix
`--index-url` always be global setting in `requirements.txt`, so it could not be set directly in `requirements_cpu_woq.txt`. But in this case, we are not allowed to use `--extra-index-url` for `oneccl_bind_pt`, see https://github.com/intel/neural-compressor/pull/2273. So have to install `oneccl_bind_pt` separately. 
> Remove index-url global setting in requirements.txt

- neural_compressor/torch/algorithms/weight_only/autoround.py
- neural_compressor/torch/quantization/algorithm_entry.py
- neural_compressor/torch/quantization/config.py
- test/3x/torch/quantization/weight_only/test_autoround.py
- test/3x/torch/requirements.txt
```
fp32_model = copy.deepcopy(self.gptj)
quant_config = AutoRoundConfig(nsamples=32, seqlen=10, iters=10, amp=False ,scale_dtype="fp16", 
scheme=scheme, export_format="llm_compressor")
logger.info(f"Test AutoRound with config {quant_config}")
model = prepare(model=fp32_model, quant_config=quant_config)
run_fn(model, self.dataloader)
q_model = convert(model)
```
> Support autoround v0.7

- neural_compressor/torch/export/pt2e_export.py
- neural_compressor/torch/utils/environ.py
Signed-off-by: yiliu30 <yi4.liu@intel.com>
> Fix export for pt 2.8

- .github/workflows/pr-agent.yml
___
Enhancement
___
- Added PR Agent workflow configuration
- Configured job to run on specific PR events
- Set up environment variables for API access
- Included steps to check LLM server and run PR-Agent
___
```mermaid
flowchart LR
init["Initialize PR Agent Workflow"] -- "Configure Events" --> events["Pull Request Events"]
events -- "Set Permissions" --> permissions["Read Contents, Write PRs & Issues"]
permissions -- "Define Steps" --> check_llm["Check LLM Server"]
check_llm -- "Run PR-Agent" --> run_agent["Execute PR-Agent Actions"]
``` …
> Support PR Agent

- .azure-pipelines/scripts/ut/3x/run_3x_pt.sh
- .azure-pipelines/scripts/ut/3x/run_3x_pt_fp8.sh
- .azure-pipelines/scripts/ut/3x/run_3x_tf.sh
___
Enhancement
___
- Added beautifulsoup4 dependency for unit tests
___
```mermaid
flowchart LR
A["Add beautifulsoup4"] -- "to run scripts" --> B["Unit Test Scripts"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>run_3x_pt.sh</strong><dd><code>Add beautifulsoup4 to run_3x_pt.sh</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Fix pytest version
